load("@prelude//toolchains/android/tools:build_rules.bzl", "buck_java_test")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

buck_java_test(
    name = "ddplist",
    srcs = glob(["*.java"]),
    resources = glob(["test-files/*.plist"]),
    deps = [
        "prelude//toolchains/android/third-party:dd-plist",
        "prelude//toolchains/android/third-party:junit",
    ],
)
