load("@fbcode//buck2:proto_defs.bzl", "rust_protobuf_library")
load("@fbcode//grpc_fb/codegen:buck_macros.bzl", "grpc_library")
load("@fbsource//tools/build_defs:glob_defs.bzl", "glob")

oncall("buck2")

rust_protobuf_library(
    name = "buck2_subscription_proto",
    srcs = glob(["src/**/*.rs"]),
    build_script = "build.rs",
    doctests = False,  # FIXME
    protos = ["subscription.proto"],
    deps = [
        "fbsource//third-party/rust:derive_more",
        "fbsource//third-party/rust:serde",
        "//buck2/allocative/allocative:allocative",
    ],
)

grpc_library(
    name = "subscription",
    srcs = [
        "subscription.proto",
    ],
    languages = [
        "py",
    ],
)
