load("@fbcode//buck2:proto_defs.bzl", "proto_srcs", "rust_protobuf_library_prost_0134")
load("@fbcode//grpc_fb/codegen:buck_macros.bzl", "grpc_library")
load("@fbcode_macros//build_defs:export_files.bzl", "export_file")

oncall("build_infra")

rust_protobuf_library_prost_0134(
    name = "buck2_subscription_proto",
    srcs = glob(["src/**/*.rs"]),
    build_script = "build.rs",
    proto_srcs = ":buck2_subscription_proto.proto",
    deps = [
        "fbsource//third-party/rust:derive_more",
        "fbsource//third-party/rust:serde",
        "//buck2/allocative/allocative:allocative",
    ],
)

proto_srcs(
    name = "buck2_subscription_proto.proto",
    srcs = ["subscription.proto"],
    visibility = ["PUBLIC"],
)

grpc_library(
    name = "subscription",
    srcs = [
        "subscription.proto",
    ],
    languages = [
        "py",
    ],
)

export_file(
    name = "subscription.proto",
)
