// @generated
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: worker.proto

// Protobuf Java Version: 3.25.6
package com.facebook.buck.worker.model;

/**
 * Protobuf type {@code worker.ExecuteEvent}
 */
@javax.annotation.Generated(value="protoc", comments="annotations:ExecuteEvent.java.pb.meta")
public final class ExecuteEvent extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:worker.ExecuteEvent)
    ExecuteEventOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ExecuteEvent.newBuilder() to construct.
  private ExecuteEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExecuteEvent() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ExecuteEvent();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.facebook.buck.worker.model.WorkerProto.internal_static_worker_ExecuteEvent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.facebook.buck.worker.model.WorkerProto.internal_static_worker_ExecuteEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.facebook.buck.worker.model.ExecuteEvent.class, com.facebook.buck.worker.model.ExecuteEvent.Builder.class);
  }

  private int dataCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object data_;
  public enum DataCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    COMMAND(1),
    CANCEL(2),
    DATA_NOT_SET(0);
    private final int value;
    private DataCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DataCase valueOf(int value) {
      return forNumber(value);
    }

    public static DataCase forNumber(int value) {
      switch (value) {
        case 1: return COMMAND;
        case 2: return CANCEL;
        case 0: return DATA_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public DataCase
  getDataCase() {
    return DataCase.forNumber(
        dataCase_);
  }

  public static final int COMMAND_FIELD_NUMBER = 1;
  /**
   * <code>.worker.ExecuteCommand command = 1;</code>
   * @return Whether the command field is set.
   */
  @java.lang.Override
  public boolean hasCommand() {
    return dataCase_ == 1;
  }
  /**
   * <code>.worker.ExecuteCommand command = 1;</code>
   * @return The command.
   */
  @java.lang.Override
  public com.facebook.buck.worker.model.ExecuteCommand getCommand() {
    if (dataCase_ == 1) {
       return (com.facebook.buck.worker.model.ExecuteCommand) data_;
    }
    return com.facebook.buck.worker.model.ExecuteCommand.getDefaultInstance();
  }
  /**
   * <code>.worker.ExecuteCommand command = 1;</code>
   */
  @java.lang.Override
  public com.facebook.buck.worker.model.ExecuteCommandOrBuilder getCommandOrBuilder() {
    if (dataCase_ == 1) {
       return (com.facebook.buck.worker.model.ExecuteCommand) data_;
    }
    return com.facebook.buck.worker.model.ExecuteCommand.getDefaultInstance();
  }

  public static final int CANCEL_FIELD_NUMBER = 2;
  /**
   * <code>.worker.ExecuteCancel cancel = 2;</code>
   * @return Whether the cancel field is set.
   */
  @java.lang.Override
  public boolean hasCancel() {
    return dataCase_ == 2;
  }
  /**
   * <code>.worker.ExecuteCancel cancel = 2;</code>
   * @return The cancel.
   */
  @java.lang.Override
  public com.facebook.buck.worker.model.ExecuteCancel getCancel() {
    if (dataCase_ == 2) {
       return (com.facebook.buck.worker.model.ExecuteCancel) data_;
    }
    return com.facebook.buck.worker.model.ExecuteCancel.getDefaultInstance();
  }
  /**
   * <code>.worker.ExecuteCancel cancel = 2;</code>
   */
  @java.lang.Override
  public com.facebook.buck.worker.model.ExecuteCancelOrBuilder getCancelOrBuilder() {
    if (dataCase_ == 2) {
       return (com.facebook.buck.worker.model.ExecuteCancel) data_;
    }
    return com.facebook.buck.worker.model.ExecuteCancel.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (dataCase_ == 1) {
      output.writeMessage(1, (com.facebook.buck.worker.model.ExecuteCommand) data_);
    }
    if (dataCase_ == 2) {
      output.writeMessage(2, (com.facebook.buck.worker.model.ExecuteCancel) data_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (dataCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.facebook.buck.worker.model.ExecuteCommand) data_);
    }
    if (dataCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.facebook.buck.worker.model.ExecuteCancel) data_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.facebook.buck.worker.model.ExecuteEvent)) {
      return super.equals(obj);
    }
    com.facebook.buck.worker.model.ExecuteEvent other = (com.facebook.buck.worker.model.ExecuteEvent) obj;

    if (!getDataCase().equals(other.getDataCase())) return false;
    switch (dataCase_) {
      case 1:
        if (!getCommand()
            .equals(other.getCommand())) return false;
        break;
      case 2:
        if (!getCancel()
            .equals(other.getCancel())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (dataCase_) {
      case 1:
        hash = (37 * hash) + COMMAND_FIELD_NUMBER;
        hash = (53 * hash) + getCommand().hashCode();
        break;
      case 2:
        hash = (37 * hash) + CANCEL_FIELD_NUMBER;
        hash = (53 * hash) + getCancel().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.facebook.buck.worker.model.ExecuteEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.facebook.buck.worker.model.ExecuteEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.facebook.buck.worker.model.ExecuteEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.facebook.buck.worker.model.ExecuteEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.facebook.buck.worker.model.ExecuteEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.facebook.buck.worker.model.ExecuteEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.facebook.buck.worker.model.ExecuteEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.facebook.buck.worker.model.ExecuteEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.facebook.buck.worker.model.ExecuteEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.facebook.buck.worker.model.ExecuteEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.facebook.buck.worker.model.ExecuteEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.facebook.buck.worker.model.ExecuteEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.facebook.buck.worker.model.ExecuteEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code worker.ExecuteEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:worker.ExecuteEvent)
      com.facebook.buck.worker.model.ExecuteEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.facebook.buck.worker.model.WorkerProto.internal_static_worker_ExecuteEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.facebook.buck.worker.model.WorkerProto.internal_static_worker_ExecuteEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.facebook.buck.worker.model.ExecuteEvent.class, com.facebook.buck.worker.model.ExecuteEvent.Builder.class);
    }

    // Construct using com.facebook.buck.worker.model.ExecuteEvent.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (commandBuilder_ != null) {
        commandBuilder_.clear();
      }
      if (cancelBuilder_ != null) {
        cancelBuilder_.clear();
      }
      dataCase_ = 0;
      data_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.facebook.buck.worker.model.WorkerProto.internal_static_worker_ExecuteEvent_descriptor;
    }

    @java.lang.Override
    public com.facebook.buck.worker.model.ExecuteEvent getDefaultInstanceForType() {
      return com.facebook.buck.worker.model.ExecuteEvent.getDefaultInstance();
    }

    @java.lang.Override
    public com.facebook.buck.worker.model.ExecuteEvent build() {
      com.facebook.buck.worker.model.ExecuteEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.facebook.buck.worker.model.ExecuteEvent buildPartial() {
      com.facebook.buck.worker.model.ExecuteEvent result = new com.facebook.buck.worker.model.ExecuteEvent(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.facebook.buck.worker.model.ExecuteEvent result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(com.facebook.buck.worker.model.ExecuteEvent result) {
      result.dataCase_ = dataCase_;
      result.data_ = this.data_;
      if (dataCase_ == 1 &&
          commandBuilder_ != null) {
        result.data_ = commandBuilder_.build();
      }
      if (dataCase_ == 2 &&
          cancelBuilder_ != null) {
        result.data_ = cancelBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.facebook.buck.worker.model.ExecuteEvent) {
        return mergeFrom((com.facebook.buck.worker.model.ExecuteEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.facebook.buck.worker.model.ExecuteEvent other) {
      if (other == com.facebook.buck.worker.model.ExecuteEvent.getDefaultInstance()) return this;
      switch (other.getDataCase()) {
        case COMMAND: {
          mergeCommand(other.getCommand());
          break;
        }
        case CANCEL: {
          mergeCancel(other.getCancel());
          break;
        }
        case DATA_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getCommandFieldBuilder().getBuilder(),
                  extensionRegistry);
              dataCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getCancelFieldBuilder().getBuilder(),
                  extensionRegistry);
              dataCase_ = 2;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int dataCase_ = 0;
    private java.lang.Object data_;
    public DataCase
        getDataCase() {
      return DataCase.forNumber(
          dataCase_);
    }

    public Builder clearData() {
      dataCase_ = 0;
      data_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilderV3<
        com.facebook.buck.worker.model.ExecuteCommand, com.facebook.buck.worker.model.ExecuteCommand.Builder, com.facebook.buck.worker.model.ExecuteCommandOrBuilder> commandBuilder_;
    /**
     * <code>.worker.ExecuteCommand command = 1;</code>
     * @return Whether the command field is set.
     */
    @java.lang.Override
    public boolean hasCommand() {
      return dataCase_ == 1;
    }
    /**
     * <code>.worker.ExecuteCommand command = 1;</code>
     * @return The command.
     */
    @java.lang.Override
    public com.facebook.buck.worker.model.ExecuteCommand getCommand() {
      if (commandBuilder_ == null) {
        if (dataCase_ == 1) {
          return (com.facebook.buck.worker.model.ExecuteCommand) data_;
        }
        return com.facebook.buck.worker.model.ExecuteCommand.getDefaultInstance();
      } else {
        if (dataCase_ == 1) {
          return commandBuilder_.getMessage();
        }
        return com.facebook.buck.worker.model.ExecuteCommand.getDefaultInstance();
      }
    }
    /**
     * <code>.worker.ExecuteCommand command = 1;</code>
     */
    public Builder setCommand(com.facebook.buck.worker.model.ExecuteCommand value) {
      if (commandBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        commandBuilder_.setMessage(value);
      }
      dataCase_ = 1;
      return this;
    }
    /**
     * <code>.worker.ExecuteCommand command = 1;</code>
     */
    public Builder setCommand(
        com.facebook.buck.worker.model.ExecuteCommand.Builder builderForValue) {
      if (commandBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        commandBuilder_.setMessage(builderForValue.build());
      }
      dataCase_ = 1;
      return this;
    }
    /**
     * <code>.worker.ExecuteCommand command = 1;</code>
     */
    public Builder mergeCommand(com.facebook.buck.worker.model.ExecuteCommand value) {
      if (commandBuilder_ == null) {
        if (dataCase_ == 1 &&
            data_ != com.facebook.buck.worker.model.ExecuteCommand.getDefaultInstance()) {
          data_ = com.facebook.buck.worker.model.ExecuteCommand.newBuilder((com.facebook.buck.worker.model.ExecuteCommand) data_)
              .mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        if (dataCase_ == 1) {
          commandBuilder_.mergeFrom(value);
        } else {
          commandBuilder_.setMessage(value);
        }
      }
      dataCase_ = 1;
      return this;
    }
    /**
     * <code>.worker.ExecuteCommand command = 1;</code>
     */
    public Builder clearCommand() {
      if (commandBuilder_ == null) {
        if (dataCase_ == 1) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
      } else {
        if (dataCase_ == 1) {
          dataCase_ = 0;
          data_ = null;
        }
        commandBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.worker.ExecuteCommand command = 1;</code>
     */
    public com.facebook.buck.worker.model.ExecuteCommand.Builder getCommandBuilder() {
      return getCommandFieldBuilder().getBuilder();
    }
    /**
     * <code>.worker.ExecuteCommand command = 1;</code>
     */
    @java.lang.Override
    public com.facebook.buck.worker.model.ExecuteCommandOrBuilder getCommandOrBuilder() {
      if ((dataCase_ == 1) && (commandBuilder_ != null)) {
        return commandBuilder_.getMessageOrBuilder();
      } else {
        if (dataCase_ == 1) {
          return (com.facebook.buck.worker.model.ExecuteCommand) data_;
        }
        return com.facebook.buck.worker.model.ExecuteCommand.getDefaultInstance();
      }
    }
    /**
     * <code>.worker.ExecuteCommand command = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.facebook.buck.worker.model.ExecuteCommand, com.facebook.buck.worker.model.ExecuteCommand.Builder, com.facebook.buck.worker.model.ExecuteCommandOrBuilder> 
        getCommandFieldBuilder() {
      if (commandBuilder_ == null) {
        if (!(dataCase_ == 1)) {
          data_ = com.facebook.buck.worker.model.ExecuteCommand.getDefaultInstance();
        }
        commandBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.facebook.buck.worker.model.ExecuteCommand, com.facebook.buck.worker.model.ExecuteCommand.Builder, com.facebook.buck.worker.model.ExecuteCommandOrBuilder>(
                (com.facebook.buck.worker.model.ExecuteCommand) data_,
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      dataCase_ = 1;
      onChanged();
      return commandBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.facebook.buck.worker.model.ExecuteCancel, com.facebook.buck.worker.model.ExecuteCancel.Builder, com.facebook.buck.worker.model.ExecuteCancelOrBuilder> cancelBuilder_;
    /**
     * <code>.worker.ExecuteCancel cancel = 2;</code>
     * @return Whether the cancel field is set.
     */
    @java.lang.Override
    public boolean hasCancel() {
      return dataCase_ == 2;
    }
    /**
     * <code>.worker.ExecuteCancel cancel = 2;</code>
     * @return The cancel.
     */
    @java.lang.Override
    public com.facebook.buck.worker.model.ExecuteCancel getCancel() {
      if (cancelBuilder_ == null) {
        if (dataCase_ == 2) {
          return (com.facebook.buck.worker.model.ExecuteCancel) data_;
        }
        return com.facebook.buck.worker.model.ExecuteCancel.getDefaultInstance();
      } else {
        if (dataCase_ == 2) {
          return cancelBuilder_.getMessage();
        }
        return com.facebook.buck.worker.model.ExecuteCancel.getDefaultInstance();
      }
    }
    /**
     * <code>.worker.ExecuteCancel cancel = 2;</code>
     */
    public Builder setCancel(com.facebook.buck.worker.model.ExecuteCancel value) {
      if (cancelBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        cancelBuilder_.setMessage(value);
      }
      dataCase_ = 2;
      return this;
    }
    /**
     * <code>.worker.ExecuteCancel cancel = 2;</code>
     */
    public Builder setCancel(
        com.facebook.buck.worker.model.ExecuteCancel.Builder builderForValue) {
      if (cancelBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        cancelBuilder_.setMessage(builderForValue.build());
      }
      dataCase_ = 2;
      return this;
    }
    /**
     * <code>.worker.ExecuteCancel cancel = 2;</code>
     */
    public Builder mergeCancel(com.facebook.buck.worker.model.ExecuteCancel value) {
      if (cancelBuilder_ == null) {
        if (dataCase_ == 2 &&
            data_ != com.facebook.buck.worker.model.ExecuteCancel.getDefaultInstance()) {
          data_ = com.facebook.buck.worker.model.ExecuteCancel.newBuilder((com.facebook.buck.worker.model.ExecuteCancel) data_)
              .mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        if (dataCase_ == 2) {
          cancelBuilder_.mergeFrom(value);
        } else {
          cancelBuilder_.setMessage(value);
        }
      }
      dataCase_ = 2;
      return this;
    }
    /**
     * <code>.worker.ExecuteCancel cancel = 2;</code>
     */
    public Builder clearCancel() {
      if (cancelBuilder_ == null) {
        if (dataCase_ == 2) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
      } else {
        if (dataCase_ == 2) {
          dataCase_ = 0;
          data_ = null;
        }
        cancelBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.worker.ExecuteCancel cancel = 2;</code>
     */
    public com.facebook.buck.worker.model.ExecuteCancel.Builder getCancelBuilder() {
      return getCancelFieldBuilder().getBuilder();
    }
    /**
     * <code>.worker.ExecuteCancel cancel = 2;</code>
     */
    @java.lang.Override
    public com.facebook.buck.worker.model.ExecuteCancelOrBuilder getCancelOrBuilder() {
      if ((dataCase_ == 2) && (cancelBuilder_ != null)) {
        return cancelBuilder_.getMessageOrBuilder();
      } else {
        if (dataCase_ == 2) {
          return (com.facebook.buck.worker.model.ExecuteCancel) data_;
        }
        return com.facebook.buck.worker.model.ExecuteCancel.getDefaultInstance();
      }
    }
    /**
     * <code>.worker.ExecuteCancel cancel = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.facebook.buck.worker.model.ExecuteCancel, com.facebook.buck.worker.model.ExecuteCancel.Builder, com.facebook.buck.worker.model.ExecuteCancelOrBuilder> 
        getCancelFieldBuilder() {
      if (cancelBuilder_ == null) {
        if (!(dataCase_ == 2)) {
          data_ = com.facebook.buck.worker.model.ExecuteCancel.getDefaultInstance();
        }
        cancelBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.facebook.buck.worker.model.ExecuteCancel, com.facebook.buck.worker.model.ExecuteCancel.Builder, com.facebook.buck.worker.model.ExecuteCancelOrBuilder>(
                (com.facebook.buck.worker.model.ExecuteCancel) data_,
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      dataCase_ = 2;
      onChanged();
      return cancelBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:worker.ExecuteEvent)
  }

  // @@protoc_insertion_point(class_scope:worker.ExecuteEvent)
  private static final com.facebook.buck.worker.model.ExecuteEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.facebook.buck.worker.model.ExecuteEvent();
  }

  public static com.facebook.buck.worker.model.ExecuteEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExecuteEvent>
      PARSER = new com.google.protobuf.AbstractParser<ExecuteEvent>() {
    @java.lang.Override
    public ExecuteEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ExecuteEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExecuteEvent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.facebook.buck.worker.model.ExecuteEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

