// @generated
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: worker.proto

package com.facebook.buck.worker.model;

/**
 * Protobuf type {@code worker.ExecuteResponse}
 */
@javax.annotation.Generated(value="protoc", comments="annotations:ExecuteResponse.java.pb.meta")
public  final class ExecuteResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:worker.ExecuteResponse)
    ExecuteResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ExecuteResponse.newBuilder() to construct.
  private ExecuteResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExecuteResponse() {
    stderr_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ExecuteResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            exitCode_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            stderr_ = s;
            break;
          }
          case 24: {

            timedOutAfterS_ = input.readUInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.facebook.buck.worker.model.WorkerProto.internal_static_worker_ExecuteResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.facebook.buck.worker.model.WorkerProto.internal_static_worker_ExecuteResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.facebook.buck.worker.model.ExecuteResponse.class, com.facebook.buck.worker.model.ExecuteResponse.Builder.class);
  }

  public static final int EXIT_CODE_FIELD_NUMBER = 1;
  private int exitCode_;
  /**
   * <code>int32 exit_code = 1;</code>
   */
  public int getExitCode() {
    return exitCode_;
  }

  public static final int STDERR_FIELD_NUMBER = 2;
  private volatile java.lang.Object stderr_;
  /**
   * <code>string stderr = 2;</code>
   */
  public java.lang.String getStderr() {
    java.lang.Object ref = stderr_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      stderr_ = s;
      return s;
    }
  }
  /**
   * <code>string stderr = 2;</code>
   */
  public com.google.protobuf.ByteString
      getStderrBytes() {
    java.lang.Object ref = stderr_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stderr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMED_OUT_AFTER_S_FIELD_NUMBER = 3;
  private long timedOutAfterS_;
  /**
   * <code>uint64 timed_out_after_s = 3;</code>
   */
  public long getTimedOutAfterS() {
    return timedOutAfterS_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (exitCode_ != 0) {
      output.writeInt32(1, exitCode_);
    }
    if (!getStderrBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, stderr_);
    }
    if (timedOutAfterS_ != 0L) {
      output.writeUInt64(3, timedOutAfterS_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (exitCode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, exitCode_);
    }
    if (!getStderrBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, stderr_);
    }
    if (timedOutAfterS_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, timedOutAfterS_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.facebook.buck.worker.model.ExecuteResponse)) {
      return super.equals(obj);
    }
    com.facebook.buck.worker.model.ExecuteResponse other = (com.facebook.buck.worker.model.ExecuteResponse) obj;

    if (getExitCode()
        != other.getExitCode()) return false;
    if (!getStderr()
        .equals(other.getStderr())) return false;
    if (getTimedOutAfterS()
        != other.getTimedOutAfterS()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EXIT_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getExitCode();
    hash = (37 * hash) + STDERR_FIELD_NUMBER;
    hash = (53 * hash) + getStderr().hashCode();
    hash = (37 * hash) + TIMED_OUT_AFTER_S_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimedOutAfterS());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.facebook.buck.worker.model.ExecuteResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.facebook.buck.worker.model.ExecuteResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.facebook.buck.worker.model.ExecuteResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.facebook.buck.worker.model.ExecuteResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.facebook.buck.worker.model.ExecuteResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.facebook.buck.worker.model.ExecuteResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.facebook.buck.worker.model.ExecuteResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.facebook.buck.worker.model.ExecuteResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.facebook.buck.worker.model.ExecuteResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.facebook.buck.worker.model.ExecuteResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.facebook.buck.worker.model.ExecuteResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.facebook.buck.worker.model.ExecuteResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.facebook.buck.worker.model.ExecuteResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code worker.ExecuteResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:worker.ExecuteResponse)
      com.facebook.buck.worker.model.ExecuteResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.facebook.buck.worker.model.WorkerProto.internal_static_worker_ExecuteResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.facebook.buck.worker.model.WorkerProto.internal_static_worker_ExecuteResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.facebook.buck.worker.model.ExecuteResponse.class, com.facebook.buck.worker.model.ExecuteResponse.Builder.class);
    }

    // Construct using com.facebook.buck.worker.model.ExecuteResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      exitCode_ = 0;

      stderr_ = "";

      timedOutAfterS_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.facebook.buck.worker.model.WorkerProto.internal_static_worker_ExecuteResponse_descriptor;
    }

    @java.lang.Override
    public com.facebook.buck.worker.model.ExecuteResponse getDefaultInstanceForType() {
      return com.facebook.buck.worker.model.ExecuteResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.facebook.buck.worker.model.ExecuteResponse build() {
      com.facebook.buck.worker.model.ExecuteResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.facebook.buck.worker.model.ExecuteResponse buildPartial() {
      com.facebook.buck.worker.model.ExecuteResponse result = new com.facebook.buck.worker.model.ExecuteResponse(this);
      result.exitCode_ = exitCode_;
      result.stderr_ = stderr_;
      result.timedOutAfterS_ = timedOutAfterS_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.facebook.buck.worker.model.ExecuteResponse) {
        return mergeFrom((com.facebook.buck.worker.model.ExecuteResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.facebook.buck.worker.model.ExecuteResponse other) {
      if (other == com.facebook.buck.worker.model.ExecuteResponse.getDefaultInstance()) return this;
      if (other.getExitCode() != 0) {
        setExitCode(other.getExitCode());
      }
      if (!other.getStderr().isEmpty()) {
        stderr_ = other.stderr_;
        onChanged();
      }
      if (other.getTimedOutAfterS() != 0L) {
        setTimedOutAfterS(other.getTimedOutAfterS());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.facebook.buck.worker.model.ExecuteResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.facebook.buck.worker.model.ExecuteResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int exitCode_ ;
    /**
     * <code>int32 exit_code = 1;</code>
     */
    public int getExitCode() {
      return exitCode_;
    }
    /**
     * <code>int32 exit_code = 1;</code>
     */
    public Builder setExitCode(int value) {
      
      exitCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 exit_code = 1;</code>
     */
    public Builder clearExitCode() {
      
      exitCode_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object stderr_ = "";
    /**
     * <code>string stderr = 2;</code>
     */
    public java.lang.String getStderr() {
      java.lang.Object ref = stderr_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stderr_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string stderr = 2;</code>
     */
    public com.google.protobuf.ByteString
        getStderrBytes() {
      java.lang.Object ref = stderr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stderr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string stderr = 2;</code>
     */
    public Builder setStderr(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      stderr_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string stderr = 2;</code>
     */
    public Builder clearStderr() {
      
      stderr_ = getDefaultInstance().getStderr();
      onChanged();
      return this;
    }
    /**
     * <code>string stderr = 2;</code>
     */
    public Builder setStderrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      stderr_ = value;
      onChanged();
      return this;
    }

    private long timedOutAfterS_ ;
    /**
     * <code>uint64 timed_out_after_s = 3;</code>
     */
    public long getTimedOutAfterS() {
      return timedOutAfterS_;
    }
    /**
     * <code>uint64 timed_out_after_s = 3;</code>
     */
    public Builder setTimedOutAfterS(long value) {
      
      timedOutAfterS_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 timed_out_after_s = 3;</code>
     */
    public Builder clearTimedOutAfterS() {
      
      timedOutAfterS_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:worker.ExecuteResponse)
  }

  // @@protoc_insertion_point(class_scope:worker.ExecuteResponse)
  private static final com.facebook.buck.worker.model.ExecuteResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.facebook.buck.worker.model.ExecuteResponse();
  }

  public static com.facebook.buck.worker.model.ExecuteResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExecuteResponse>
      PARSER = new com.google.protobuf.AbstractParser<ExecuteResponse>() {
    @java.lang.Override
    public ExecuteResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ExecuteResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ExecuteResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExecuteResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.facebook.buck.worker.model.ExecuteResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

