load("@prelude//cfg/modifier:conditional_modifier.bzl", "conditional_modifier")

oncall("build_infra")

# This is for testing `conditional_modifier` rule builds. The bxl tests will test that the produced values
# do what we expect them to do for modifier resolution

constraint(
    name = "test",
    default = "unspecified",
    values = [
        "test1",
        "test2",
        "unspecified",
    ],
    visibility = [],
)

conditional_modifier(
    name = "test_conditional_modifier",
    modifier = {
        # Test different types of relative target labels for modifiers
        "DEFAULT": ":test[test1]",
        "ovr_config//os:linux": "//buck2/tests/e2e/configurations/cfg_constructor/conditional_modifier:test[test2]",
    },
)

conditional_modifier(
    name = "test_nested_conditional_modifier",
    modifier = {
        "DEFAULT": {
            "ovr_config//cpu:arm64": ":test[test2]",
            "ovr_config//cpu:x86_64": ":test[test1]",
        },
        "ovr_config//os:linux": None,
    },
)

conditional_modifier(
    name = "test_conditional_modifier_with_relative_key",
    modifier = {
        ":test[test1]": "ovr_config//cpu/constraints:arm64",
        "DEFAULT": None,
    },
)

# Test that cell aliases work correctly for both key and value.
# config// is an alias for ovr_config//.
conditional_modifier(
    name = "test_cell_alias_conditional_modifier",
    modifier = {
        "DEFAULT": "config//build_mode:sanitizer_type[tsan]",
        "config//os:windows": None,
    },
)
