load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "cmp_any",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    autocargo = {
        "cargo_toml_config": {
            "package": {
                "authors": ["Facebook"],
                "categories": ["rust-patterns"],
                "description": "Comparison for &dyn types",
                "documentation": "https://docs.rs/cmp_any",
                "version": "0.8.1",
            },
        },
    },
    deps = [],
)
