load("@fbcode_macros//build_defs:rust_library.bzl", "rust_library")
load("@fbsource//tools/build_defs:glob_defs.bzl", "glob")

oncall("build_infra")

rust_library(
    name = "cmp_any",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    deps = [
    ],
)
