load("@fbcode//buck2/tests/prelude:py_assertion.bzl", "py_assertion")

oncall("golang")

prelude = native

prelude.go_binary(
    name = "bin",
    srcs = ["main.go"],
    deps = [
        "//buck2/tests/prelude/go/binary/library:lib",
    ],
)

py_assertion(
    name = "check_output",
    script = """
import subprocess
import sys
assert (
    subprocess.check_output([sys.argv[1]]).decode().strip()
    == "hello world"
)
""",
    script_args = ["$(exe_target :bin)"],
)

py_assertion(
    name = "check_exe_extension",
    script = """
import sys
from pathlib import Path
import platform
if platform.system() == "Windows":
    assert (
        Path(sys.argv[1]).suffix == ".exe"
    )
""",
    script_args = ["$(exe_target :bin)"],
)
