load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "buck2_protoc_dev",
    srcs = glob(["src/**/*.rs"]),
    rustc_flags = [
        "--cfg=buck2_build",
    ],
    deps = [
        "fbsource//third-party/rust:tonic-build",
    ],
)

rust_library(
    name = "buck2_protoc_dev-tonic",
    srcs = glob(["src/**/*.rs"]),
    crate = "buck2_protoc_dev",
    rustc_flags = [
        "--cfg=buck2_build",
    ],
    deps = [
        "fbsource//third-party/rust:tonic-build-0-12-3",
    ],
)
