load("@fbcode_macros//build_defs:rust_library.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "buck2_protoc_dev",
    srcs = glob(["src/**/*.rs"]),
    rustc_flags = [
        "--cfg=buck2_build",
    ],
    deps = [
        "fbsource//third-party/rust:tonic-build",
    ],
)
