load(
    "@prelude//toolchains/android/tools:build_rules.bzl",
    "buck_java_test",
)
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

buck_java_test(
    name = "workertool_grpc",
    srcs = glob(["*Test.java"]),
    deps = [
        "prelude//toolchains/android/src/com/facebook/buck/jvm/cd/workertool/grpc:workertool_grpc",
        "prelude//toolchains/android/src/com/facebook/buck/workertool/resources/proto:worker-model",
        "prelude//toolchains/android/third-party:grpc-api",
        "prelude//toolchains/android/third-party:grpc-netty",
        "prelude//toolchains/android/third-party:junit",
        "prelude//toolchains/android/third-party:mockito",
        "prelude//toolchains/android/third-party:netty",
    ],
)
