load("@prelude//toolchains/android/tools:build_rules.bzl", "buck_kotlin_test")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

buck_kotlin_test(
    name = "util",
    srcs = glob(["*.kt"]),
    deps = [
        "prelude//toolchains/android/src/com/facebook/buck/android/agent/util:util",
        "prelude//toolchains/android/test/com/facebook/buck/testutil/integration:util",
        "prelude//toolchains/android/third-party:guava",
        "prelude//toolchains/android/third-party:junit",
    ],
)
