load("@fbcode//buck2/tests:buck_e2e.bzl", "buck2_e2e_test")

oncall("build_infra")

buck2_e2e_test(
    name = "test_select_types",
    srcs = ["test_select_types.py"],
    data_dir = "test_select_types_data",
    use_compiled_buck2_client_and_tpx = True,
)
