# @lint-ignore BUCKLINT missing-oncall-call-severe This file is unowned and will be deleted without notice (due to not having an owner to contact).  Do not depend on this file
load("//go:rules.bzl", "go_binary")

go_binary(
    name = "main",
    srcs = glob(["*.go"]),
    toolchain = "toolchains//:go",
    deps = [],
)
