load(":export_file.bzl", "export_file")
load(":toolchain.bzl", "go_toolchain", "toolchain_config")

export_file(
    name = "symlink.bat",
    src = "symlink.bat",
)

go_toolchain(
    name = "go",
    archive_extension = toolchain_config.archive_extension,
    platform = toolchain_config.platform,
    sha1 = toolchain_config.sha1,
    version = toolchain_config.version,
    visibility = ["PUBLIC"],
)
