load("@prelude//configurations:constraint_alias.bzl", "constraint_with_aliases")

constraint_with_aliases(
    name = "folly_demangle_macos_use_iberty_constraint",
    aliases = {
        "folly_demangle_macos_disable_iberty": "disable",
    },
    default = "unspecified",
    values = [
        "disable",
        "unspecified",
    ],
    visibility = ["PUBLIC"],
)

config_setting(
    name = "folly_demangle_macos_disable_iberty_config",
    constraint_values = [
        "prelude//os/constraints:os[macos]",
        ":folly_demangle_macos_use_iberty_constraint[disable]",
    ],
    visibility = ["PUBLIC"],
)
