load("@prelude//configurations:constraint_alias.bzl", "constraint_with_aliases")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("build_infra")

source_listing()

# Used by open source projects to support `prelude//`

constraint_with_aliases(
    name = "cpu",
    aliases = {
        "arm32": "arm32",
        "arm64": "arm64",
        "arm64_32": "arm64_32",
        "riscv64": "riscv64",
        "wasm32": "wasm32",
        "x86_32": "x86_32",
        "x86_64": "x86_64",
    },
    default = "unspecified",
    values = [
        "x86_64",
        "x86_32",
        "arm64",
        "arm64_32",
        "arm32",
        "wasm32",
        "riscv64",
        "unspecified",
    ],
    visibility = ["PUBLIC"],
)
