load("@fbcode//buck2/tests:buck_e2e.bzl", "buck2_e2e_test")
load("@fbcode_macros//build_defs:python_library.bzl", "python_library")

oncall("tae")

python_library(
    name = "fdb_e2e_types",
    srcs = ["types.py"],
    deps = [
        "//buck2/tests/e2e_util/api:api",
    ],
)

buck2_e2e_test(
    name = "test_fdb_project",
    srcs = [
        "test_fdb_bxl_java.py",
    ],
    test_with_compiled_buck2 = False,
    test_with_deployed_buck2 = True,
    deps = [
        ":fdb_e2e_types",
        "//buck2/tests/e2e_util:utils",  # @autodeps2-fixme-manual
    ],
)
