/*
 * Copyright 2019 The Starlark in Rust Authors.
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//! Proc macro for `#[type_matcher]` attribute.
//!
//! This attribute is placed on `impl TypeMatcher for X` blocks and generates:
//! 1. `unsafe impl TypeMatcherRegistered for X {}` - for both generic and non-generic impls
//! 2. For non-generic types only: an inventory vtable registration for
//!    `TypeCompiledImplAsStarlarkValue<X>`
//!
//! Generic matchers (e.g., `impl<T: TypeMatcher> TypeMatcher for IsListOf<T>`)
//! need no per-instantiation registration: every monomorphization linked into
//! the binary registers its AValue vtable through a load-time constructor
//! emitted by `TypeCompiled::alloc`, and its typetag through
//! `#[pagable_typetag(TypeMatcherDyn)]` on the wrapper struct definition.

use proc_macro2::TokenStream;
use quote::quote;
use syn::spanned::Spanned;

fn derive_type_matcher_impl(_attr: TokenStream, input: TokenStream) -> syn::Result<TokenStream> {
    let item_impl: syn::ItemImpl = syn::parse2(input)?;

    // Verify this is an impl for TypeMatcher trait
    let trait_path = item_impl
        .trait_
        .as_ref()
        .map(|(path, _)| path)
        .ok_or_else(|| {
            syn::Error::new(
                item_impl.span(),
                "#[type_matcher] must be applied to an `impl TypeMatcher for ...` block",
            )
        })?;

    // Check that the trait is TypeMatcher (just check the last segment)
    let trait_name = trait_path
        .segments
        .last()
        .map(|seg| seg.ident.to_string())
        .unwrap_or_default();
    if trait_name != "TypeMatcher" {
        return Err(syn::Error::new(
            trait_path.span(),
            "#[type_matcher] must be applied to an `impl TypeMatcher for ...` block",
        ));
    }

    // Get the Self type
    let self_ty = &item_impl.self_ty;

    // Get the generics from the impl block
    let generics = &item_impl.generics;

    // Check if the impl block has generic type parameters (not just lifetimes)
    let has_type_params = generics.type_params().next().is_some();

    let (impl_generics, _ty_generics, where_clause) = generics.split_for_impl();

    // Generate TypeMatcherRegistered impl for both generic and non-generic types.
    let registered_impl = quote! {
        // SAFETY: This impl is generated by the #[type_matcher] macro, which
        // guarantees vtable registration: concrete matchers register below,
        // and generic matchers register each monomorphization through the
        // load-time constructor emitted by `TypeCompiled::alloc` (put
        // `#[pagable_typetag(TypeMatcherDyn)]` on the wrapper struct for the
        // matching per-monomorphization typetag registration).
        unsafe impl #impl_generics starlark::values::typing::TypeMatcherRegistered
            for #self_ty #where_clause
        {}
    };

    // Concrete matchers register their vtable via inventory here; generic
    // matchers register per monomorphization at image load instead, so there
    // is no source site to submit from (and nothing further to write).
    let vtable_registration = if has_type_params {
        quote! {}
    } else {
        quote! {
            starlark::register_simple_vtable_entry!(
                starlark::values::typing::TypeCompiledImplAsStarlarkValue<#self_ty>
            );
        }
    };

    // Return the original impl block plus the generated code
    Ok(quote! {
        #item_impl
        #registered_impl
        #vtable_registration
    })
}

pub fn derive_type_matcher(
    attr: proc_macro::TokenStream,
    input: proc_macro::TokenStream,
) -> proc_macro::TokenStream {
    match derive_type_matcher_impl(attr.into(), input.into()) {
        Ok(tokens) => tokens.into(),
        Err(err) => err.to_compile_error().into(),
    }
}
