load("@prelude//toolchains/android/tools:build_rules.bzl", "buck_kotlin_library", "java_binary")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

buck_kotlin_library(
    name = "applicability-lib",
    srcs = glob(
        ["*.kt"],
    ),
    labels = ["codegen_rule"],
    provided_deps = [
        "prelude//toolchains/android/third-party:kotlin-compiler",
    ],
    tests = [
        "fbsource//fbandroid/javatests/com/facebook/kotlin/compilerplugins/kosabi/applicability:applicability-test",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "prelude//toolchains/android/src/com/facebook/buck/jvm/kotlin/compilerplugins/kosabi/applicability/common:common",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/kotlin/compilerplugins/kosabi/applicability/k1:k1",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/kotlin/compilerplugins/kosabi/applicability/k2:k2",
    ],
)

java_binary(
    name = "applicability",
    visibility = ["PUBLIC"],
    deps = [":applicability-lib"],
)
