load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "buck2_embedded_section",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    compatible_with = [
        "ovr_config//os:linux",
    ],
    deps = [
        "fbsource//third-party/rust:object-0-39",
        "fbsource//third-party/rust:zstd",
        "//buck2/app/buck2_error:buck2_error",
    ],
)
