load("@fbcode_macros//build_defs:rust_library.bzl", "rust_library")
load("@fbsource//tools/build_defs:glob_defs.bzl", "glob")

oncall("buck2")

rust_library(
    name = "buck2_build_api_tests",
    srcs = glob(["src/**/*.rs"]),
    test_deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:assert_matches",
        "fbsource//third-party/rust:async-trait",
        "fbsource//third-party/rust:derivative",
        "fbsource//third-party/rust:indexmap",
        "fbsource//third-party/rust:indoc",
        "fbsource//third-party/rust:itertools",
        "fbsource//third-party/rust:maplit",
        "fbsource//third-party/rust:serde_json",
        "fbsource//third-party/rust:tokio",
        "//buck2/allocative/allocative:allocative",
        "//buck2/app/buck2_build_api:buck2_build_api",
        "//buck2/app/buck2_common:buck2_common",
        "//buck2/app/buck2_core:buck2_core",
        "//buck2/app/buck2_data:buck2_data",
        "//buck2/app/buck2_events:buck2_events",
        "//buck2/app/buck2_execute:buck2_execute",
        "//buck2/app/buck2_interpreter:buck2_interpreter",
        "//buck2/app/buck2_interpreter_for_build:buck2_interpreter_for_build",
        "//buck2/app/buck2_node:buck2_node",
        "//buck2/app/buck2_util:buck2_util",
        "//buck2/dice/dice:dice",
        "//buck2/gazebo/dupe:dupe",
        "//buck2/gazebo/gazebo:gazebo",
        "//buck2/starlark-rust/starlark:starlark",
        "//buck2/starlark-rust/starlark_map:starlark_map",
        "//common/rust/shed/sorted_vector_map:sorted_vector_map",
    ],
)
