load("@prelude//toolchains/android/tools:build_rules.bzl", "buck_kotlin_library")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

buck_kotlin_library(
    name = "scribe",
    srcs = glob([
        "*.kt",
    ]),
    labels = ["codegen_rule"],  # see: https://fburl.com/workplace/fhud6fe6
    resources = glob(["resources/**/*"]),
    resources_root = "resources",
    visibility = ["PUBLIC"],
    runtime_deps = [
        "fbsource//third-party/java/org/slf4j/slf4j-nop:slf4j-nop",
    ],
    deps = [
        "fbcode//dsi/logger/log_entry/KotlinCDLoggerConfig:kotlin_c_d_log_entry-java-swift-java17",
        "fbcode//scribe/api/producer/thrift/experimental:structured_producer-java-swift-java17",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/kotlin/cd/analytics/logger:logger",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/kotlin/cd/analytics/logger/model:model",
    ],
)
