load("@fbcode//buck2/tests:buck_e2e.bzl", "buck2_e2e_test")

oncall("build_infra")

buck2_e2e_test(
    name = "test_buck_config_logging.py",
    srcs = ["test_buck_config_logging.py"],
    data_dir = "test_buck_config_log_data",
)
