load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("build_infra")

source_listing()

prelude = native

prelude.python_bootstrap_binary(
    name = "gen_stdlib_importcfg",
    main = "gen_stdlib_importcfg.py",
    visibility = ["PUBLIC"],
)

prelude.python_bootstrap_binary(
    name = "go_wrapper_py",
    main = "go_wrapper.py",
    visibility = ["PUBLIC"],
)

prelude.go_stdlib(
    name = "stdlib",
    visibility = ["PUBLIC"],
)

prelude.go_bootstrap_binary(
    name = "tool_pack",
    build_args = [
        "cmd/pack",
    ],
    visibility = ["PUBLIC"],
)
