load("@fbcode//buck2/tests/prelude:py_assertion.bzl", "py_assertion")

oncall("golang")

prelude = native

prelude.write_file(
    name = "greeting",
    out = "greeting.txt",
    content = ["HELLO WORLD"],
)

prelude.go_binary(
    name = "bin",
    srcs = ["main.go"],
    embed_srcs = [":greeting"],
)

py_assertion(
    name = "check_output",
    script = """
import subprocess
import sys
assert subprocess.check_output([sys.argv[1]]).decode().strip() == "HELLO WORLD"
""",
    script_args = ["$(exe_target :bin)"],
)
