load("@prelude//toolchains/android/tools:build_rules.bzl", "buck_java_library")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

buck_java_library(
    name = "plugin-loader",
    srcs = ["PluginLoader.java"],
    resources = [
        "dep-tracker.jar",
    ],
    visibility = [
        "prelude//toolchains/android/src/com/facebook/buck/jvm/kotlin:",
    ],
)
