load("@prelude//toolchains/android/tools:build_rules.bzl", "buck_kotlin_library")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

buck_kotlin_library(
    name = "sample-no-deps",
    deps = [
        "fbsource//fbandroid/third-party/java/infer-annotations:infer-annotations",
    ],
)
