# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is dual-licensed under either the MIT license found in the
# LICENSE-MIT file in the root directory of this source tree or the Apache
# License, Version 2.0 found in the LICENSE-APACHE file in the root directory
# of this source tree. You may select, at your option, one of the
# above-listed licenses.

load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("build_infra")

source_listing()

constraint_setting(
    name = "default_opt_cxx_setting",
    visibility = ["PUBLIC"],
)

constraint_value(
    name = "enabled",
    constraint_setting = ":default_opt_cxx_setting",
    visibility = ["PUBLIC"],
)

constraint_value(
    name = "disabled",
    constraint_setting = ":default_opt_cxx_setting",
    visibility = ["PUBLIC"],
)
