load("@fbcode_macros//build_defs:rust_library.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "gazebo",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    features = [
        "str_pattern_extensions",
    ],
    deps = [
        "//buck2/gazebo/dupe:dupe",
        "//buck2/gazebo/gazebo_derive:gazebo_derive",
    ],
)
