load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "gazebo",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    autocargo = {
        "cargo_toml_config": {
            "features": {
                "str_pattern_extensions": [],
            },
            "package": {
                "authors": ["Facebook"],
                "categories": ["rust-patterns"],
                "description": "A collection of well-tested utilities",
                "documentation": "https://docs.rs/gazebo",
                "version": "0.8.1",
            },
        },
    },
    features = [
        "str_pattern_extensions",
    ],
    deps = [
        "//buck2/gazebo/dupe:dupe",
        "//buck2/gazebo/gazebo_derive:gazebo_derive",
    ],
)
