load("@prelude//toolchains/android/tools:build_rules.bzl", "buck_java_library")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

buck_java_library(
    name = "api",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        # Don't add deps that aren't already in the plugin; this is a super-light library
        "prelude//toolchains/android/src/com/facebook/buck/jvm/java/plugin/api:api",
        "prelude//toolchains/android/src/com/facebook/buck/util/liteinfersupport:liteinfersupport",
    ],
)
