load(
    "@prelude//toolchains/android/tools:build_rules.bzl",
    "buck_kotlin_library",
)
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

buck_kotlin_library(
    name = "step",
    srcs = glob(
        [
            "*.java",
            "*.kt",
        ],
    ),
    visibility = ["PUBLIC"],
    deps = [
        "prelude//toolchains/android/src/com/facebook/buck/util:process_executor",
    ],
    exported_deps = [
    ],
)
