load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "dice",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    # `dep:` is required so cargo doesn't auto-create a same-named implicit
    # feature that fails to enable the optional dep.
    autocargo = {
        "cargo_toml_config": {
            "features": {
                "default": ["pagable"],
                "pagable": ["dep:pagable"],
            },
        },
    },
    crate_root = "src/lib.rs",
    features = ["pagable"],
    test_deps = [
        "fbsource//third-party/rust:assert_matches",
        "fbsource//third-party/rust:bincode",
        "fbsource//third-party/rust:derivative",
        "fbsource//third-party/rust:indoc",
        "fbsource//third-party/rust:tempfile",
    ],
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:anymap3",
        "fbsource//third-party/rust:arc-swap",
        "fbsource//third-party/rust:async-trait",
        "fbsource//third-party/rust:dashmap",
        "fbsource//third-party/rust:derivative",
        "fbsource//third-party/rust:derive_more",
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:itertools",
        "fbsource//third-party/rust:parking_lot",
        "fbsource//third-party/rust:pin-project",
        "fbsource//third-party/rust:ref-cast",
        "fbsource//third-party/rust:scopeguard",
        "fbsource//third-party/rust:serde",
        "fbsource//third-party/rust:sorted_vector_map",
        "fbsource//third-party/rust:static_assertions",
        "fbsource//third-party/rust:thiserror",
        "fbsource//third-party/rust:tokio",
        "fbsource//third-party/rust:tracing",
        "fbsource//third-party/rust:triomphe",
        "fbsource//third-party/rust:typed-arena",
        "//buck2/allocative/allocative:allocative",
        "//buck2/app/buck2_hash:buck2_hash",
        "//buck2/dice/dice_error:dice_error",
        "//buck2/dice/dice_futures:dice_futures",
        "//buck2/gazebo/cmp_any:cmp_any",
        "//buck2/gazebo/dupe:dupe",
        "//buck2/gazebo/gazebo:gazebo",
        "//buck2/pagable:pagable",
        "//buck2/pagable_storage:pagable_storage",
        "//buck2/shed/lock_free_hashtable:lock_free_hashtable",
        "//buck2/shed/lock_free_vec:lock_free_vec",
        "//buck2/shed/mini_vec:mini_vec",
    ],
)
