load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("build_infra")

source_listing()

prelude = native

prelude.python_bootstrap_binary(
    name = "go_wrapper_py",
    main = "go_wrapper.py",
    visibility = ["PUBLIC"],
)
