load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("build_infra")

source_listing()

prelude = native

prelude.python_bootstrap_binary(
    name = "go_wrapper_py",
    main = "go_wrapper.py",
    visibility = ["PUBLIC"],
)

# Type checking target for Python tool scripts
prelude.python_library(
    name = "scripts-typing",
    srcs = [
        "go_wrapper.py",
    ],
    typing = True,
)
