load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("build_infra")

source_listing()

config_setting(
    name = "conda",
    constraint_values = [
        "//distro/constraints:conda",
    ],
    visibility = ["PUBLIC"],
)
