# @lint-ignore BUCKLINT missing-oncall-call-severe This file is unowned and will be deleted without notice (due to not having an owner to contact).  Do not depend on this file
load(":platforms.bzl", "execution_platform", "host_configuration")

execution_platform(
    name = "default",
    cpu_configuration = host_configuration.cpu,
    os_configuration = host_configuration.os,
    use_windows_path_separators = host_info().os.is_windows,
)

# Construct a bootstrap platforms that inherits everything from
# default but adds on an extra bootstrap constraint
platform(
    name = "bootstrap",
    constraint_values = ["bootstrap//:use_bootstrap"],
    visibility = ["PUBLIC"],
    deps = [":default"],
)
