load(":platforms.bzl", "execution_platform", "host_configuration")

execution_platform(
    name = "default_platforms",
    cpu_configuration = host_configuration.cpu,
    os_configuration = host_configuration.os,
    use_windows_path_separators = host_info().os.is_windows,
)

# Construct a bootstrap platforms that inherits everything from
# default_platforms but adds on an extra bootstrap constraint
platform(
    name = "bootstrap_platforms",
    constraint_values = ["bootstrap//bootstrap:use_bootstrap"],
    visibility = ["PUBLIC"],
    deps = [":default_platforms"],
)
