load(":platforms.bzl", "execution_platform", "host_configuration")

oncall("build_infra")

execution_platform(
    name = "default",
    cpu_configuration = host_configuration.cpu,
    os_configuration = host_configuration.os,
    use_windows_path_separators = host_info().os.is_windows,
)

# Construct a bootstrap platforms that inherits everything from
# default but adds on an extra bootstrap constraint
platform(
    name = "bootstrap",
    constraint_values = ["bootstrap//:use_bootstrap"],
    visibility = ["PUBLIC"],
    deps = [":default"],
)
