load("@prelude//toolchains/android/tools:build_rules.bzl", "buck_java_library")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

buck_java_library(
    name = "testresultsoutput",
    srcs = [
        "TestResultsOutputEvent.java",
        "TestResultsOutputSender.java",
    ],
    # @oss-disable[end= ]: source = "8",
    # @oss-disable[end= ]: target = "8",
    source = "11", # @oss-enable
    target = "11", # @oss-enable
    tests = [
        "prelude//toolchains/android/test/com/facebook/buck/testresultsoutput:testresultsoutput",
    ],
    visibility = [
        "prelude//toolchains/android/src/com/facebook/buck/testrunner:instrumentation",
        "prelude//toolchains/android/src/com/facebook/buck/testrunner:junit",
        "prelude//toolchains/android/test/com/facebook/buck/testresultsoutput:testresultsoutput",
        "prelude//toolchains/android/test/com/facebook/buck/testrunner:testrunner",
    ],
    deps = [
        "prelude//toolchains/android/third-party:jackson-core",
    ],
)
