load("@fbcode_macros//build_defs:rust_library.bzl", "rust_library")
load("@fbsource//tools/build_defs:glob_defs.bzl", "glob")

oncall("buck2")

rust_library(
    name = "buck2_build_info",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//buck2/app/buck2_util:buck2_util",
        # @oss-disable: "//common/rust/build_info:build_info", 
    ],
)
