load("@fbcode_macros//build_defs:rust_library.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "buck2_build_info",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//buck2/app/buck2_util:buck2_util",
        # @oss-disable[end= ]: "//common/rust/build_info:build_info",
    ],
)
