prelude = native

prelude.sh_binary(
    name = "win_python_wrapper",
    main = "win_python_wrapper.bat",
    visibility = ["PUBLIC"],
    target_compatible_with = select({
        "DEFAULT": [],
        "config//os:windows": ["config//os:windows"],
    }),
)
