load("//test_utils.bzl", "assert_output")

_SUPPORTED = host_info().os.is_linux

haskell_library(
    name = "library",
    srcs = ["Library.hs"],
    deps = [
        "//third-party/haskell:base",
    ],
) if _SUPPORTED else None

haskell_binary(
    name = "main",
    srcs = ["Main.hs"],
    deps = [
        ":library",
    ],
) if _SUPPORTED else None

assert_output(
    name = "hello-world-check",
    command = "$(exe_target :main)",
    output = "Hello World!",
) if _SUPPORTED else None
