# @lint-ignore BUCKLINT missing-oncall-call-severe This file is unowned and will be deleted without notice (due to not having an owner to contact).  Do not depend on this file
load("//:test_utils.bzl", "assert_output", "haskell_binary", "haskell_library")

_SUPPORTED = host_info().os.is_macos or host_info().os.is_linux

# buildifier: disable=no-effect
haskell_library(
    name = "library",
    srcs = ["Library.hs"],
) if _SUPPORTED else None

# buildifier: disable=no-effect
haskell_binary(
    name = "main",
    srcs = ["Main.hs"],
    deps = [
        ":library",
    ],
) if _SUPPORTED else None

# buildifier: disable=no-effect
assert_output(
    name = "hello-world-check",
    command = "$(exe_target :main)",
    output = "Hello World!",
) if _SUPPORTED else None
