load("@prelude//apple/tools:defs.bzl", "meta_python_test")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("apple_build_infra")

source_listing()

python_bootstrap_binary(
    name = "merge_index_store",
    main = "merge_index_store.py",
    visibility = ["PUBLIC"],
)

python_bootstrap_library(
    name = "merge_index_store_lib",
    srcs = ["merge_index_store.py"],
    tests = [":merge_index_store_tests"],
    visibility = ["PUBLIC"],
)

meta_python_test(
    name = "merge_index_store_tests",
    srcs = [
        "merge_index_store.py",
        "merge_index_store_tests.py",
    ],
)
