load("@fbcode_macros//build_defs:rust_library.bzl", "rust_library")
load("@fbsource//tools/build_defs:glob_defs.bzl", "glob")

oncall("buck2")

rust_library(
    name = "buck2_interpreter_tests",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    test_deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:indoc",
        "//buck2/app/buck2_interpreter:buck2_interpreter",
        "//buck2/app/buck2_interpreter_for_build:buck2_interpreter_for_build",
    ],
)
