load(
    "@prelude//toolchains/android/tools:build_rules.bzl",
    "buck_java_library",
)
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

buck_java_library(
    name = "cd",
    srcs = glob(["*.java"]),
    visibility = [
        "prelude//toolchains/android/meta_only/src/com/facebook/buck/jvm/remote_worker/...",
        "prelude//toolchains/android/src/com/facebook/buck/...",
        "prelude//toolchains/android/test/com/facebook/buck/...",
    ],
    deps = [
        "prelude//toolchains/android/src/com/facebook/buck/cd/resources/proto:cd-model",
        "prelude//toolchains/android/src/com/facebook/buck/cd/resources/proto:javacd-model",
        "prelude//toolchains/android/src/com/facebook/buck/cd/resources/proto:kotlincd-model",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/cd/command/kotlin:command",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/cd/serialization:serialization",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/cd/serialization/java:java",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/cd/workertool:workertool",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/java:support",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/java/abi/source/api:api",
        "prelude//toolchains/android/src/com/facebook/buck/step/isolatedsteps/java:java",
        "prelude//toolchains/android/src/com/facebook/buck/util/json:json",
        "prelude//toolchains/android/third-party:guava",
        "prelude//toolchains/android/third-party:infer-annotations",
        "prelude//toolchains/android/third-party:jsr305",
        "prelude//toolchains/android/third-party:kotlin-annotations",
    ],
)
