load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("build_infra")

source_listing()

config_setting(
    name = "libc++",
    constraint_values = [
        "//cpp/constraints:libc++",
    ],
    visibility = ["PUBLIC"],
)

config_setting(
    name = "libstdc++",
    constraint_values = [
        "//cpp/constraints:libstdc++",
    ],
    visibility = ["PUBLIC"],
)
