load("@fbcode//buck2/tests:buck_e2e.bzl", "buck2_e2e_test")

oncall("build_infra")

buck2_e2e_test(
    name = "test_v2_only",
    srcs = ["test_v2_only.py"],
)

buck2_e2e_test(
    name = "test_read_root_config",
    srcs = ["test_read_root_config.py"],
    data_dir = "test_read_root_config_data",
)

buck2_e2e_test(
    name = "test_package_file_alt_name",
    srcs = ["test_package_file_alt_name.py"],
    data_dir = "test_package_file_alt_name_data",
    serialize_test_cases = False,
)

buck2_e2e_test(
    name = "test_package_file_package_values",
    srcs = ["test_package_file_package_values.py"],
    data_dir = "test_package_file_package_values_data",
    serialize_test_cases = False,
    deps = [
        "//buck2/tests/e2e_util:golden",
    ],
)

buck2_e2e_test(
    name = "test_package_values_missing_buck_file",
    srcs = ["test_package_values_missing_buck_file.py"],
    data_dir = "test_package_values_missing_buck_file_data",
    serialize_test_cases = False,
    deps = [
        "//buck2/tests/e2e_util:golden",
    ],
)

buck2_e2e_test(
    name = "test_unstable_typecheck",
    srcs = ["test_unstable_typecheck.py"],
    data_dir = "test_unstable_typecheck_data",
)

buck2_e2e_test(
    name = "test_prelude_typecheck",
    srcs = ["test_prelude_typecheck.py"],
    data_dir = "test_prelude_typecheck_data",
)

buck2_e2e_test(
    name = "test_peak_allocated_bytes",
    srcs = ["test_peak_allocated_bytes.py"],
    data_dir = "test_peak_allocated_bytes_data",
    deps = [
        "//buck2/tests/e2e_util:utils",
    ],
)

buck2_e2e_test(
    name = "test_peak_allocated_bytes_exceeds_limit",
    srcs = ["test_peak_allocated_bytes_exceeds_limit.py"],
    data_dir = "test_peak_allocated_bytes_exceeds_limit_data",
    deps = [
        "//buck2/tests/e2e_util:utils",
    ],
)

buck2_e2e_test(
    name = "test_peak_allocated_bytes_exceeds_soft_limit",
    srcs = ["test_peak_allocated_bytes_exceeds_soft_limit.py"],
    data_dir = "test_peak_allocated_bytes_exceeds_soft_limit_data",
    deps = [
        "//buck2/tests/e2e_util:utils",
    ],
)

buck2_e2e_test(
    name = "test_cpu_instruction_count",
    srcs = ["test_cpu_instruction_count.py"],
    data_dir = "test_cpu_instruction_count_data",
    deps = [
        "//buck2/tests/e2e_util:utils",
    ],
)

buck2_e2e_test(
    name = "test_package_values_cross_cell",
    srcs = ["test_package_values_cross_cell.py"],
    data_dir = "test_package_values_cross_cell_data",
    serialize_test_cases = False,
    deps = [
        "//buck2/tests/e2e_util:golden",
    ],
)

buck2_e2e_test(
    name = "test_callstack_size",
    srcs = ["test_callstack_size.py"],
    data_dir = "test_callstack_size_data",
    serialize_test_cases = False,
)

buck2_e2e_test(
    name = "test_sub_packages",
    srcs = ["test_sub_packages.py"],
    data_dir = "test_sub_packages_data",
)

buck2_e2e_test(
    name = "test_missing_source_file",
    srcs = ["test_missing_source_file.py"],
    data_dir = "test_missing_source_file_data",
)
