load("@fbcode_macros//build_defs:rust_library.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "buck2_build_api_derive",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    proc_macro = True,
    deps = [
        "fbsource//third-party/rust:convert_case",
        "fbsource//third-party/rust:proc-macro2",
        "fbsource//third-party/rust:quote",
        "fbsource//third-party/rust:syn",
        "//buck2/gazebo/gazebo:gazebo",
    ],
)
