# @lint-ignore BUCKLINT missing-oncall-call-severe This file is unowned and will be deleted without notice (due to not having an owner to contact).  Do not depend on this file
load("@fbcode_macros//build_defs:native_rules.bzl", "alias")
load("@fbcode_macros//build_defs:rust_library.bzl", "rust_library")

rust_library(
    name = "l",
    srcs = ["lib.rs"],
    unittests = False,
)

alias(
    name = "l_alias",
    actual = ":l",
)
