load("@fbcode//buck2/tests:buck_e2e.bzl", "buck2_core_tests")

oncall("build_infra")

buck2_core_tests(
    target_extra_attrs = {
        "test_install": {
            "env": {
                "EXTRA_ARGS_VALIDATOR_BIN": "$(location fbcode//buck2/tests/targets/rules/install:server_validates_extra_args_order)",
                "FORWARDED_PARAMS_INSTALLER_BIN": "$(location fbcode//buck2/tests/targets/rules/install:server_requires_forwarded_params)",
                "INSTALLER_BIN": "$(location fbcode//buck2/tests/targets/rules/install:installer)",
            },
            "skip_for_os": [
                "darwin",
                "windows",
            ],
        },
    },
)
