load("@fbcode//buck2/tests:buck_e2e.bzl", "buck2_e2e_test")

oncall("build_infra")

buck2_e2e_test(
    name = "test_vpnless",
    srcs = ["test_vpnless.py"],
    data_dir = "test_vpnless_data",
    deps = [
        "fbsource//third-party/pypi/requests:requests",
    ],
)
