load("@fbcode_macros//build_defs:rust_library.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "buck2_re_configuration",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//buck2/allocative/allocative:allocative",
        "//buck2/app/buck2_common:buck2_common",
        "//buck2/app/buck2_core:buck2_core",
        "//buck2/app/buck2_error:buck2_error",
    ],
)
