# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is dual-licensed under either the MIT license found in the
# LICENSE-MIT file in the root directory of this source tree or the Apache
# License, Version 2.0 found in the LICENSE-APACHE file in the root directory
# of this source tree. You may select, at your option, one of the
# above-listed licenses.

# Configuration for Reindeer to generate Buck targets from Cargo.toml
#
# Overview of available options:
# https://github.com/facebookincubator/reindeer/blob/main/example/third-party/reindeer.toml

# Parse Rust code to work out the precise set of source files for each crate.
precise_srcs = true

# Include a public top-level target which depends on all other targets.
include_top_level = true
include_workspace_members = true

[cargo]
# Support Cargo's unstable "artifact dependencies" functionality, RFC 3028.
bindeps = true

[buck]
# Name of the generated file.
file_name = "BUCK.reindeer"

platform_compatibility_on_all_targets = true

# Rules used for various kinds of targets.
rust_library = "third_party_rust_rust_library"
rust_binary = "third_party_rust_rust_binary"
prebuilt_cxx_library = "third_party_rust_prebuilt_cxx_library"
cxx_library = "third_party_rust_cxx_library"
alias = "third_party_rust_alias"
alias_with_platforms = "third_party_rust_alias"

buckfile_imports = """
load("@prelude//rust:cargo_buildscript.bzl", "buildscript_run")
load("@prelude//rust:cargo_package.bzl", "cargo")
load(
    "@shim//third-party/macros:rust_third_party.bzl",
    "third_party_rust_alias",
    "third_party_rust_cxx_library",
    "third_party_rust_prebuilt_cxx_library",
    "third_party_rust_rust_binary",
    "third_party_rust_rust_library",
)
"""
