load(
    "@prelude//toolchains/android/tools:build_rules.bzl",
    "buck_kotlin_library",
)
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

buck_kotlin_library(
    name = "common",
    srcs = glob([
        "*.java",
        "*.kt",
    ]),
    visibility = [
        "prelude//toolchains/android/src/com/facebook/buck/...",
        "prelude//toolchains/android/test/com/facebook/buck/...",
    ],
    deps = [
        "prelude//toolchains/android/src/com/facebook/buck/io/file:file",
        "prelude//toolchains/android/src/com/facebook/buck/util/zip:zip",
        "prelude//toolchains/android/third-party:guava",
    ],
    exported_deps = [
        "prelude//toolchains/android/src/com/facebook/buck/io/filesystem/impl:utils",
        "prelude//toolchains/android/src/com/facebook/buck/step/isolatedsteps:isolatedsteps",
    ],
)
