load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("build_infra")

source_listing()

prelude = native

prelude.python_bootstrap_binary(
    name = "inject_test_env",
    main = "inject_test_env.py",
    visibility = ["PUBLIC"],
)
