load("@fbcode//buck2/tests:buck_e2e.bzl", "buck2_core_tests")

oncall("build_infra")

buck2_core_tests(
    target_extra_attrs = {
        "test_action_suspension": {
            "env": {
                "USE_SOME_MEMORY_BIN": "$(location //buck2/shed/cgroups/use_some_memory:use_some_memory)",
            },
            "skip_for_os": [
                "darwin",
                "windows",
            ],
        },
        "test_hybrid_execution_resource_control": {
            "env": {
                "USE_SOME_MEMORY_BIN": "$(location //buck2/shed/cgroups/use_some_memory:use_some_memory)",
            },
            "skip_for_os": [
                "darwin",
                "windows",
            ],
        },
        "test_instruction_count": {
            "env": {
                "THREE_BILLION_INSTRUCTIONS_BIN": "$(location //buck2/shed/three_billion_instructions:three_billion_instructions-bin)",
            },
        },
        "test_memory_reporting": {
            "env": {
                "USE_SOME_MEMORY_BIN": "$(location //buck2/shed/cgroups/use_some_memory:use_some_memory)",
            },
            "skip_for_os": [
                "darwin",
                "windows",
            ],
            "use_compiled_buck2_client_and_tpx": True,
        },
    },
)
