load("@fbcode//buck2/tests:buck_e2e.bzl", "buck2_e2e_test")

oncall("build_infra")

buck2_e2e_test(
    name = "test_what_ran",
    srcs = ["test_what_ran.py"],
    use_compiled_buck2_client_and_tpx = True,
)

buck2_e2e_test(
    name = "test_what_failed",
    srcs = ["test_what_failed.py"],
)

buck2_e2e_test(
    name = "test_log_format",
    srcs = ["test_log_format.py"],
    use_compiled_buck2_client_and_tpx = True,
)

buck2_e2e_test(
    name = "test_persist_event_logs",
    srcs = ["test_persist_event_logs.py"],
    deps = [
        "//manifold/clients/python:manifold_client_deprecated",
    ],
)

buck2_e2e_test(
    name = "test_upload_re_logs",
    srcs = ["test_upload_re_logs.py"],
    deps = [
        "fbcode//buck2/tests/e2e_util:utils",
        "//manifold/clients/python:manifold_client_deprecated",
    ],
)
