load("@fbcode//buck2/tests:buck_e2e.bzl", "buck2_e2e_test")

oncall("build_infra")

buck2_e2e_test(
    name = "test_cycle_detection",
    srcs = ["test_cycle_detection.py"],
    data_dir = "test_cycle_detection_data",
)
