# @lint-ignore BUCKLINT missing-oncall-call-severe This file is unowned and will be deleted without notice (due to not having an owner to contact).  Do not depend on this file
constraint_setting(
    name = "configuration",
    visibility = ["PUBLIC"],
)

constraint_value(
    name = "debug",
    constraint_setting = ":configuration",
    visibility = ["PUBLIC"],
)

constraint_value(
    name = "release",
    constraint_setting = ":configuration",
    visibility = ["PUBLIC"],
)
