# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under both the MIT license found in the
# LICENSE-MIT file in the root directory of this source tree and the Apache
# License, Version 2.0 found in the LICENSE-APACHE file in the root directory
# of this source tree.

config_setting(
    name = "linux",
    constraint_values = [
        "prelude//os/constraints:linux",
    ],
    visibility = ["PUBLIC"],
)

config_setting(
    name = "linux-fedora",
    constraint_values = [
        "prelude//os/constraints:os[linux]",
        "//os/linux/distro/constraints:distro[fedora]",
    ],
    visibility = ["PUBLIC"],
)

config_setting(
    name = "linux-ubuntu",
    constraint_values = [
        "prelude//os/constraints:os[linux]",
        "//os/linux/distro/constraints:distro[ubuntu]",
    ],
    visibility = ["PUBLIC"],
)

configuration_alias(
    name = "android",
    actual = "prelude//os:android",
    visibility = ["PUBLIC"],
)

config_setting(
    name = "android-arm64",
    constraint_values = [
        "prelude//cpu/constraints:arm64",
        "prelude//os/constraints:android",
    ],
    visibility = ["PUBLIC"],
)

config_setting(
    name = "android-x86_64",
    constraint_values = [
        "prelude//cpu/constraints:x86_64",
        "prelude//os/constraints:android",
    ],
    visibility = ["PUBLIC"],
)

configuration_alias(
    name = "appletvos",
    actual = "prelude//os:tvos",
    visibility = ["PUBLIC"],
)

configuration_alias(
    name = "iphoneos",
    actual = "prelude//os:iphoneos",
    visibility = ["PUBLIC"],
)

configuration_alias(
    name = "linux-arm64",
    actual = "prelude//os:linux-arm64",
    visibility = ["PUBLIC"],
)

configuration_alias(
    name = "linux-sgx",
    actual = "prelude//os:linux-sgx",
    visibility = ["PUBLIC"],
)

configuration_alias(
    name = "macos",
    actual = "prelude//os:macos",
    visibility = ["PUBLIC"],
)

config_setting(
    name = "macos-homebrew",
    constraint_values = [
        "prelude//os/constraints:os[macos]",
    ],
    visibility = ["PUBLIC"],
)

configuration_alias(
    name = "watchos",
    actual = "prelude//os:watchos",
    visibility = ["PUBLIC"],
)

configuration_alias(
    name = "windows",
    actual = "prelude//os:windows",
    visibility = ["PUBLIC"],
)
