# @lint-ignore BUCKLINT missing-oncall-call-severe This file is unowned and will be deleted without notice (due to not having an owner to contact).  Do not depend on this file
load("@prelude//utils:source_listing.bzl", "source_listing")

source_listing()

python_bootstrap_binary(
    name = "build_index_store",
    main = "main.py",
    deps = [
        "prelude//apple/tools/index:merge_index_store_lib",
    ],
)
