load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("apple_build_infra")

source_listing()

python_bootstrap_binary(
    name = "build_index_store",
    main = "main.py",
    visibility = [
        "fbcode//glean/glass/test/regression:swift-binary",
        "fbcode//glean/glass/test/regression:swift-objc-xlang-binary",
        "fbcode//glean/lang/swift/tests:tests",
        "fbcode//glean/lang/swift/tests:tests-rust-indexer",
    ],
    deps = [
        "prelude//apple/tools/index:merge_index_store_lib",
    ],
)
