# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under both the MIT license found in the
# LICENSE-MIT file in the root directory of this source tree and the Apache
# License, Version 2.0 found in the LICENSE-APACHE file in the root directory
# of this source tree.

# Used by buck2.py.
alias(
    name = "buck2",
    actual = "gh_facebook_buck2//:buck2",
)

alias(
    name = "buck2_bundle",
    actual = "gh_facebook_buck2//:buck2_bundle",
)
