load("@prelude//toolchains/android/tools:build_rules.bzl", "buck_kotlin_library")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

buck_kotlin_library(
    name = "common",
    srcs = glob(["*.kt"]),
    labels = ["codegen_rule"],
    provided_deps = [
        "prelude//toolchains/android/third-party:kotlin-compiler",
    ],
    tests = [
        "fbsource//fbandroid/javatests/com/facebook/kotlin/compilerplugins/common:common",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
    ],
)
