load("@prelude//erlang:erlang_otp_application.bzl", "gen_otp_applications")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("build_infra")

source_listing()

gen_otp_applications()
