load("//test_utils.bzl", "assert_output")

rust_binary(
    name = "main",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    crate_root = "src/main.rs",
)

assert_output(
    name = "check_main",
    command = "$(exe_target :main)",
    output = "hello world from rust toolchain",
)
