load("@prelude//toolchains/android/tools:build_rules.bzl", "buck_java_library")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

buck_java_library(
    name = "unit",
    srcs = glob(["*.java"]),
    tests = [
        "prelude//toolchains/android/test/com/facebook/buck/util/unit:unit",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "prelude//toolchains/android/src/com/facebook/buck/util/string:string",
        "prelude//toolchains/android/third-party:guava",
    ],
    exported_deps = [
        "prelude//toolchains/android/src/com/facebook/buck/util/types:types",
    ],
)
