load("@prelude//toolchains/android/tools:build_rules.bzl", "buck_kotlin_library")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

buck_kotlin_library(
    name = "postexecutors",
    srcs = glob(["**/*.kt"]),
    labels = ["codegen_rule"],
    tests = [
        "prelude//toolchains/android/test/com/facebook/buck/jvm/kotlin/cd/workertool/postexecutors:postexecutors",
    ],
    visibility = [
        "prelude//toolchains/android/src/com/facebook/buck/jvm/kotlin/cd/workertool/...",
        "prelude//toolchains/android/test/com/facebook/buck/jvm/kotlin/cd/workertool/...",
    ],
    deps = [
        "prelude//toolchains/android/src/com/facebook/buck/core/filesystems:filesystems",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/java/abi:abi",
    ],
)
