load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("build_infra")

source_listing()

# Used by open source projects to support `prelude//`

constraint_setting(
    name = "stdlib",
    visibility = ["PUBLIC"],
)

constraint_value(
    name = "libc++",
    constraint_setting = ":stdlib",
    visibility = ["PUBLIC"],
)

constraint_value(
    name = "libstdc++",
    constraint_setting = ":stdlib",
    visibility = ["PUBLIC"],
)
