# @lint-ignore BUCKLINT missing-oncall-call-severe This file is unowned and will be deleted without notice (due to not having an owner to contact).  Do not depend on this file
_SUPPORTED = not host_info().os.is_windows

# buildifier: disable=no-effect
go_library(
    name = "greeting",
    srcs = glob(["*.go"]),
    visibility = ["PUBLIC"],
) if _SUPPORTED else None

# buildifier: disable=no-effect
go_test(
    name = "greeting_test",
    srcs = glob(["*.go"]),
) if _SUPPORTED else None
