prelude = native

prelude.python_bootstrap_binary(
    name = "rustc_action",
    main = "rustc_action.py",
    visibility = ["PUBLIC"],
)

prelude.python_bootstrap_binary(
    name = "rustdoc_test_with_resources",
    main = "rustdoc_test_with_resources.py",
    visibility = ["PUBLIC"],
)

prelude.python_bootstrap_binary(
    name = "failure_filter_action",
    main = "failure_filter_action.py",
    visibility = ["PUBLIC"],
)

prelude.python_bootstrap_binary(
    name = "concat",
    main = "concat.py",
    visibility = ["PUBLIC"],
)

prelude.python_bootstrap_binary(
    name = "transitive_dependency_symlinks",
    main = "transitive_dependency_symlinks.py",
    visibility = ["PUBLIC"],
)
