load("@fbcode//buck2/tests:buck_e2e.bzl", "buck2_e2e_test")

oncall("tcc")

buck2_e2e_test(
    name = "tests",
    srcs = glob(
        [
            "**/*.py",
        ],
    ),
    compatible_with = ["ovr_config//os:linux"],
    skip_for_os = [
        "darwin",
        "windows",
    ],
    test_with_deployed_buck2 = True,
    use_compiled_buck2_client_and_tpx = True,
)
