load("@fbcode//buck2:proto_defs.bzl", "rust_protobuf_library")
load("@fbcode//grpc_fb/codegen:buck_macros.bzl", "grpc_library")
load("@fbsource//tools/build_defs:glob_defs.bzl", "glob")

oncall("buck2")

rust_protobuf_library(
    name = "buck2_worker_proto",
    srcs = glob(["src/**/*.rs"]),
    build_script = "build.rs",
    protos = ["worker.proto"],
)

grpc_library(
    name = "worker",
    srcs = [
        "worker.proto",
    ],
    languages = [
        "py",
    ],
)
