load("@prelude//toolchains/android/tools:build_rules.bzl", "buck_kotlin_library")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("kotlin_foundation_oncall")

source_listing()

buck_kotlin_library(
    name = "qe2",
    srcs = glob(["**/*.kt"]),
    labels = ["codegen_rule"],  # see: https://fburl.com/workplace/fhud6fe6
    visibility = [
        "prelude//toolchains/android/meta_only/src/com/facebook/buck/jvm/kotlin/abtesting:abtesting",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/kotlin/...",
        "prelude//toolchains/android/test/com/facebook/buck/jvm/kotlin/...",
    ],
    deps = [
        "fbsource//fbandroid/java/com/facebook/tools/qe2:qe2",
        "fbsource//fbandroid/third-party/java/json:json",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/kotlin/abtesting:abtesting",
    ],
)
