load("@fbcode_macros//build_defs:rust_unittest.bzl", "rust_unittest")

oncall("build_infra")

rust_unittest(
    name = "buck2_action_impl_tests",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:ctor",
        "fbsource//third-party/rust:indoc",
        "fbsource//third-party/rust:maplit",
        "//buck2/app/buck2_action_impl:buck2_action_impl",
        "//buck2/app/buck2_anon_target:buck2_anon_target",
        "//buck2/app/buck2_build_api:buck2_build_api",
        "//buck2/app/buck2_core:buck2_core",
        "//buck2/app/buck2_execute:buck2_execute",
        "//buck2/app/buck2_interpreter_for_build:buck2_interpreter_for_build",
        "//buck2/gazebo/dupe:dupe",
        "//buck2/starlark-rust/starlark:starlark",
    ],
)
