load("@fbcode//buck2/tests:buck_e2e.bzl", "buck2_e2e_test")
load("@fbcode//buck2/tests:bxl_test.bzl", "bxl_test")

oncall("build_infra")

buck2_e2e_test(
    name = "test_test_inplace",
    srcs = ["test_test_inplace.py"],
    data = "//buck2/tests/targets:isolated_targets",
    test_with_deployed_buck2 = True,
    use_compiled_buck2_client_and_tpx = True,
)

bxl_test(
    src = "test_label_inplace.bxl",
)

bxl_test(
    name = "test_label_inplace_with_asan_buckconfig",
    src = "test_label_inplace.bxl",
    buck_args = [
        "@fbsource//fbandroid/mode/asan",
    ],
)

buck2_e2e_test(
    name = "test_test_coverage",
    srcs = glob([
        "test_test_coverage/**/*.py",
    ]),
    skip_for_os = [
        "darwin",
        "windows",
    ],
    test_with_deployed_buck2 = True,
    use_compiled_buck2_client_and_tpx = True,
)

buck2_e2e_test(
    name = "test_test_artifacts",
    srcs = ["test_test_artifacts.py"],
    env = {
        "TESTX_BIN": "$(exe_target fbsource//xplat/tools:testx)",
    },
    skip_for_os = [
        "darwin",
        "windows",
    ],
    test_with_deployed_buck2 = True,
    use_compiled_buck2_client_and_tpx = True,
    deps = [
        "//buck2/tests/e2e_util:utils",
        "//remote_execution/client_lib/wrappers/python:py_re_client_lib",
        "//remote_execution/lib/if:common-py3-types",
        "//remote_execution/lib/if/client_lib:re-client-lib-if-py3-types",
        "//tae/testx:py",
    ],
)

buck2_e2e_test(
    name = "test_testname_formatting",
    srcs = ["test_testname_formatting.py"],
    test_with_deployed_buck2 = True,
    use_compiled_buck2_client_and_tpx = True,
    deps = [
        "//remote_execution/client_lib/wrappers/python:py_re_client_lib",  # @autodeps2-fixme-manual
    ],
)
