oncall("build_infra")

cxx_binary(
    name = "main",
    srcs = ["main.cpp"],
    link_style = "static",
    deps = [":print"],
)

cxx_library(
    name = "print",
    srcs = ["library.cpp"],
    exported_headers = glob(["**/*.hpp"]),
    visibility = ["PUBLIC"],
)

java_library(
    name = "java_lib",
    srcs = ["HelloWorld.java"],
    source = "11",
    target = "11",
)
