load("@prelude//toolchains/android/tools:build_rules.bzl", "buck_java_library")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

# Includes stripped-down versions of types that Infer recognizes, so that we can use Infer on
# code that must be very light on dependencies.
buck_java_library(
    name = "liteinfersupport",
    srcs = glob(["*.java"]),
    required_for_source_only_abi = True,
    visibility = [
        "prelude//toolchains/android/src/com/facebook/buck/jvm/java/abi/source:source",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/java/abi/source/api:api",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/java/fatjar:fat-jar-main",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/java/lang/model:model",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/java/plugin/adapter:adapter",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/java/plugin/api:api",
    ],
    deps = [
        # This module is intended for use in dependency-constrained environments. Don't take deps.
    ],
)
