load("@prelude//toolchains/android/tools/build_rules:java_rules.bzl", "buck_java_library")

buck_java_library(
    name = "installer-proto",
    srcs = glob(["**/install/model/**/*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "fbsource//xplat/toolchains/android/sdk/third-party/java/jakarta.annotation-api:jakarta.annotation-api",
    ],
    exported_deps = [
        "fbsource//xplat/toolchains/android/sdk/third-party/java/grpc:remote-apis",
    ],
)
