/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under both the MIT license found in the
 * LICENSE-MIT file in the root directory of this source tree and the Apache
 * License, Version 2.0 found in the LICENSE-APACHE file in the root directory
 * of this source tree.
 */

pub mod configured;
pub mod configured_node_visit_all_deps;
pub mod configured_ref;
pub mod eval_result;
pub mod unconfigured;

/// Attributes on target nodes that are generated by buck, not provided by users.
pub mod attributes {
    /// The nodes that this node depends on.
    #[allow(unused)]
    pub static DEPS: &str = "buck.deps";
    pub static DEPS_LEGACY: &str = "$deps";

    /// The oncall for this node.
    pub static ONCALL: &str = "buck.oncall";

    /// The package that this node belongs to.
    #[allow(unused)]
    pub static PACKAGE: &str = "buck.package";
    pub static PACKAGE_LEGACY: &str = "$package";

    /// A string representation of the target's rule type.
    pub static TYPE: &str = "buck.type";
    pub static TYPE_LEGACY: &str = "$type";

    /// The target hash of this target.
    #[allow(unused)]
    pub static TARGET_HASH: &str = "buck.target_hash";
    pub static TARGET_HASH_LEGACY: &str = "$target_hash";

    /// The callstack for this target.
    #[allow(unused)]
    pub static TARGET_CALL_STACK: &str = "buck.target_call_stack";
    pub static TARGET_CALL_STACK_LEGACY: &str = "$target_call_stack";

    /// The configuration deps, deps that appear as conditions in selects.
    pub static CONFIGURATION_DEPS: &str = "buck.configuration_deps";
}
