load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("build_infra")

source_listing()

prelude = native

prelude.python_bootstrap_binary(
    name = "compile_kotlin",
    main = "compile_kotlin.py",
    visibility = ["PUBLIC"],
    deps = [
        "prelude//java/tools:utils_lib",
    ],
)
