load("@prelude//toolchains/android/tools:build_rules.bzl", "buck_kotlin_library")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

buck_kotlin_library(
    name = "analytics",
    srcs = glob(["**/*.kt"]),
    extra_kotlinc_arguments = ["-Xopt-in=kotlin.ExperimentalStdlibApi"],
    labels = ["codegen_rule"],
    tests = ["prelude//toolchains/android/test/com/facebook/buck/jvm/kotlin/cd/analytics/logger:logger"],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "prelude//toolchains/android/src/com/facebook/buck/core/filesystems:filesystems",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/cd/command/kotlin:language-version",
    ],
)
