load("@prelude//toolchains/android/tools:build_rules.bzl", "buck_java_library")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

TRANSLATOR_SRCS = [
    "ProguardMapping.java",
    "ProguardTranslatorFactory.java",
]

buck_java_library(
    name = "translator",
    srcs = TRANSLATOR_SRCS,
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "prelude//toolchains/android/third-party:guava",
    ],
)
