load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("plf_experience")

source_listing()

filegroup(
    name = "bootstrap_files",
    srcs = glob(["__par__/**/*.py"]),
    visibility = ["PUBLIC"],
)
