# @lint-ignore BUCKLINT missing-oncall-call-severe This file is unowned and will be deleted without notice (due to not having an owner to contact).  Do not depend on this file
load("//cpp:rules.bzl", "cpp_binary")

cpp_binary(
    name = "main",
    srcs = glob(["*.cpp"]),
    headers = glob(["*.hpp"]),
    toolchain = "toolchains//:cpp",
    deps = [],
)
