load("@fbcode_macros//build_defs:rust_library.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "buck2_test_runner",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:async-trait",
        "fbsource//third-party/rust:clap",
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:parking_lot",
        "fbsource//third-party/rust:tokio",
        "//buck2/app/buck2_error:buck2_error",
        "//buck2/app/buck2_grpc:buck2_grpc",
        "//buck2/app/buck2_test_api:buck2_test_api",
        "//buck2/host_sharing:host_sharing",
    ],
)
