load("@prelude//toolchains/android/tools:build_rules.bzl", "buck_kotlin_library")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("kotlin_foundation_oncall")

source_listing()

buck_kotlin_library(
    name = "abtesting",
    srcs = glob(["**/*.kt"]),
    resources = glob(["resources/**/*"]),
    resources_root = "resources",
    visibility = [
        "prelude//toolchains/android/src/com/facebook/buck/jvm/kotlin/...",
        "prelude//toolchains/android/test/com/facebook/buck/jvm/kotlin/...",
    ],
    deps = [
        "prelude//toolchains/android/meta_only/src/com/facebook/buck/jvm/kotlin/abtesting/qe2:qe2",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/kotlin/abtesting:abtesting",
    ],
)
