load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("build_infra")

source_listing()

prelude = native

prelude.python_bootstrap_library(
    name = "library",
    srcs = [
        "inputs.py",
        "legacy_outputs.py",
        "outputs.py",
    ],
    visibility = ["PUBLIC"],
)

prelude.python_bootstrap_binary(
    name = "merge",
    main = "merge.py",
    visibility = ["PUBLIC"],
    deps = [
        ":library",
    ],
)

prelude.python_bootstrap_binary(
    name = "legacy_merge",
    main = "legacy_merge.py",
    visibility = ["PUBLIC"],
    deps = [
        ":library",
    ],
)

# Run the test suite with this command:
# buck2 run prelude//python/tools/sourcedb_merger:tests --target-platforms prelude//platforms:default
prelude.sh_binary(
    name = "tests",
    main = "tests/main.sh",
    resources = glob(["**/*.py"]),
)
