load("@prelude//toolchains/android/tools:build_rules.bzl", "buck_kotlin_library")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

buck_kotlin_library(
    name = "stub",
    srcs = glob(
        ["**/*.kt"],
    ),
    labels = ["codegen_rule"],
    provided_deps = [
        "prelude//toolchains/android/third-party:kotlin-compiler-embeddable",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "prelude//toolchains/android/src/com/facebook/buck/jvm/kotlin/compilerplugins/kosabi/common:common",
        "prelude//toolchains/android/third-party:kotlin-poet",
    ],
)
