load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("build_infra")

source_listing()

# Used by open source projects to support `prelude//`

constraint_setting(
    name = "distro",
    visibility = ["PUBLIC"],
)

constraint_value(
    name = "conda",
    constraint_setting = ":distro",
    visibility = ["PUBLIC"],
)
