load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("apple_workflows")

source_listing()

python_binary(
    name = "codesign_bundle_using_manifest",
    main = "main.py",
    visibility = ["PUBLIC"],
)
