load("@fbcode_macros//build_defs:rust_library.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "buck2_miniperf_proto",
    srcs = glob(["src/**/*.rs"]),
    test_deps = [
        "fbsource//third-party/rust:bincode",
    ],
    deps = [
        "fbsource//third-party/rust:serde",
        "//buck2/app/buck2_data:buck2_data",
        "//buck2/gazebo/dupe:dupe",
    ],
)
