load("@fbcode_macros//build_defs:rust_library.bzl", "rust_library")
load("@fbsource//tools/build_defs:glob_defs.bzl", "glob")

oncall("buck2")

rust_library(
    name = "buck2_miniperf_proto",
    srcs = glob(["src/**/*.rs"]),
    test_deps = [
        "fbsource//third-party/rust:bincode",
    ],
    deps = [
        "fbsource//third-party/rust:serde",
        "//buck2/gazebo/dupe:dupe",
    ],
)
