load("@fbcode//buck2/tests/prelude:py_assertion.bzl", "py_assertion")

oncall("golang")

prelude = native

# Objective-C is only compilable where there's a runtime for it, which is what
# `system_cxx_toolchain`'s `objc_supported` defaults to off elsewhere.
prelude.go_binary(
    name = "bin",
    srcs = [
        "lib.m",
        "main.go",
    ],
    headers = ["lib.h"],
    header_namespace = "",
    target_compatible_with = ["config//os:macos"],
)

py_assertion(
    name = "check_output",
    script = """
import subprocess
import sys
assert subprocess.check_output([sys.argv[1]]).decode().strip() == "i = 1"
""",
    script_args = ["$(exe_target :bin)"],
    target_compatible_with = ["config//os:macos"],
)
