// (c) Meta Platforms, Inc. and affiliates. Confidential and proprietary.
package com.facebook.kotlin.compilerplugins.kosabi.stubsgen.util

import com.facebook.kotlin.compilerplugins.kosabi.common.FullTypeQualifier

// @generated by parsing types contained in kotlin/core/builtins
// https://github.com/JetBrains/kotlin/tree/master/core/builtins
class KTBuiltInTypes private constructor() {
  companion object {
    val KTBuiltIn_Comparable: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "Comparable",
            ))
    val KTBuiltIn_CharSequence: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "CharSequence",
            ))
    val KTBuiltIn_Iterator: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "collections",
                "Iterator",
            ))
    val KTBuiltIn_MutableIterator: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "collections",
                "MutableIterator",
            ))
    val KTBuiltIn_ListIterator: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "collections",
                "ListIterator",
            ))
    val KTBuiltIn_MutableListIterator: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "collections",
                "MutableListIterator",
            ))
    val KTBuiltIn_Iterable: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "collections",
                "Iterable",
            ))
    val KTBuiltIn_MutableIterable: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "collections",
                "MutableIterable",
            ))
    val KTBuiltIn_Collection: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "collections",
                "Collection",
            ))
    val KTBuiltIn_MutableCollection: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "collections",
                "MutableCollection",
            ))
    val KTBuiltIn_List: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "collections",
                "List",
            ))
    val KTBuiltIn_MutableList: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "collections",
                "MutableList",
            ))
    val KTBuiltIn_Set: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "collections",
                "Set",
            ))
    val KTBuiltIn_MutableSet: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "collections",
                "MutableSet",
            ))
    val KTBuiltIn_Map: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "collections",
                "Map",
            ))
    val KTBuiltIn_MutableMap: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "collections",
                "MutableMap",
            ))
    val KTBuiltIn_String: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "String",
            ))
    val KTBuiltIn_Enum: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "Enum",
            ))
    val KTBuiltIn_Nothing: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "Nothing",
            ))
    val KTBuiltIn_Array: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "Array",
            ))
    val KTBuiltIn_Any: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "Any",
            ))
    val KTBuiltIn_Throwable: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "Throwable",
            ))
    val KTBuiltIn_ByteArray: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "ByteArray",
            ))
    val KTBuiltIn_CharArray: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "CharArray",
            ))
    val KTBuiltIn_ShortArray: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "ShortArray",
            ))
    val KTBuiltIn_IntArray: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "IntArray",
            ))
    val KTBuiltIn_LongArray: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "LongArray",
            ))
    val KTBuiltIn_FloatArray: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "FloatArray",
            ))
    val KTBuiltIn_DoubleArray: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "DoubleArray",
            ))
    val KTBuiltIn_BooleanArray: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "BooleanArray",
            ))
    val KTBuiltIn_Annotation: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "Annotation",
            ))
    val KTBuiltIn_Boolean: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "Boolean",
            ))
    val KTBuiltIn_Byte: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "Byte",
            ))
    val KTBuiltIn_Short: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "Short",
            ))
    val KTBuiltIn_Int: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "Int",
            ))
    val KTBuiltIn_Long: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "Long",
            ))
    val KTBuiltIn_Float: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "Float",
            ))
    val KTBuiltIn_Double: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "Double",
            ))
    val KTBuiltIn_Number: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "Number",
            ))
    val KTBuiltIn_Char: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "Char",
            ))
    val KTBuiltIn_Unit: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "Unit",
            ))
    val KTBuiltIn_Function: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "Function",
            ))
    val KTBuiltIn_AnnotationTarget: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "annotation",
                "AnnotationTarget",
            ))
    val KTBuiltIn_AnnotationRetention: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "annotation",
                "AnnotationRetention",
            ))
    val KTBuiltIn_Target: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "annotation",
                "Target",
            ))
    val KTBuiltIn_Retention: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "annotation",
                "Retention",
            ))
    val KTBuiltIn_Repeatable: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "annotation",
                "Repeatable",
            ))
    val KTBuiltIn_MustBeDocumented: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "annotation",
                "MustBeDocumented",
            ))
    val KTBuiltIn_Deprecated: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "Deprecated",
            ))
    val KTBuiltIn_DeprecatedSinceKotlin: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "DeprecatedSinceKotlin",
            ))
    val KTBuiltIn_ReplaceWith: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "ReplaceWith",
            ))
    val KTBuiltIn_DeprecationLevel: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "DeprecationLevel",
            ))
    val KTBuiltIn_ExtensionFunctionType: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "ExtensionFunctionType",
            ))
    val KTBuiltIn_ContextFunctionTypeParams: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "ContextFunctionTypeParams",
            ))
    val KTBuiltIn_ParameterName: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "ParameterName",
            ))
    val KTBuiltIn_Suppress: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "Suppress",
            ))
    val KTBuiltIn_UnsafeVariance: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "UnsafeVariance",
            ))
    val KTBuiltIn_SinceKotlin: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "SinceKotlin",
            ))
    val KTBuiltIn_DslMarker: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "DslMarker",
            ))
    val KTBuiltIn_PublishedApi: FullTypeQualifier =
        FullTypeQualifier(
            listOf(
                "kotlin",
                "PublishedApi",
            ))
  }
}
