load("//os_lookup:defs.bzl", "os_lookup")

os_lookup(
    name = "os_lookup",
    # FIXME: prelude// should be standalone (not refer to ovr_config//)
    cpu = select({
        "DEFAULT": None,
        "ovr_config//cpu:arm64": "arm64",
        "ovr_config//cpu:x86_64": "x86_64",
    }),
    platform = select({
        "DEFAULT": "linux",
        "ovr_config//os:macos": "macos",
        "ovr_config//os:windows": "windows",
    }),
    visibility = ["PUBLIC"],
)
