load("@fbcode//buck2/tests:buck_e2e.bzl", "buck2_e2e_test")

oncall("build_infra")

buck2_e2e_test(
    name = "test_argfiles",
    srcs = ["test_argfiles.py"],
    data_dir = "test_argfiles_data",
)

buck2_e2e_test(
    name = "test_common_opts",
    srcs = ["test_common_opts.py"],
    data_dir = "test_common_opts_data",
)
