# @lint-ignore BUCKLINT missing-oncall-call-severe This file is unowned and will be deleted without notice (due to not having an owner to contact).  Do not depend on this file
cxx_library(
    name = "lib",
    srcs = ["lib.cc"],
    headers = ["lib.h"],
)

cxx_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = [":lib"],
)
