load("@fbcode//buck2/tests:buck_e2e.bzl", "buck2_e2e_test")

oncall("build_infra")

buck2_e2e_test(
    name = "test_emit_console_preferences",
    srcs = ["test_emit_console_preferences.py"],
    data_dir = "test_emit_console_preferences_data",
    deps = [
        "fbcode//buck2/tests/e2e_util:utils",
    ],
)
