load("@fbcode//buck2/tests:buck_e2e.bzl", "buck2_core_tests")

oncall("build_infra")

buck2_core_tests(
    target_extra_attrs = {
        "test_console": {
            "env": {
                "FIXTURES": "$(location //buck2/tests/core/console/fixtures:fixtures)",
            },
        },
    },
)
