# @lint-ignore BUCKLINT missing-oncall-call-severe This file is unowned and will be deleted without notice (due to not having an owner to contact).  Do not depend on this file
load("@fbcode//buck2/tests:bxl_test.bzl", "bxl_test")

bxl_test(
    src = "test_configuration_alias.bxl",
)
