load("@fbcode//buck2/tests/prelude:py_assertion.bzl", "py_assertion")

oncall("golang")

prelude = native

prelude.go_binary(
    name = "bin",
    srcs = ["main.go"],
    embed_srcs = ["greeting.txt"],
)

prelude.go_test(
    name = "test",
    srcs = [
        "main.go",
        "main_test.go",
    ],
    embed_srcs = ["greeting.txt"],
    # @oss-disable[end= ]: env = {"GO_TEST2JSON_TOOL": "$(exe_target fbsource//third-party/go:test2json)"},
)

py_assertion(
    name = "check_output",
    script = """
import subprocess
import sys
assert subprocess.check_output([sys.argv[1]]).decode().strip() == "Hello"
""",
    script_args = ["$(exe_target :bin)"],
)
