/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under both the MIT license found in the
 * LICENSE-MIT file in the root directory of this source tree and the Apache
 * License, Version 2.0 found in the LICENSE-APACHE file in the root directory
 * of this source tree.
 */

use crate::interface::HealthCheckType;

/// Severity of the issue reported by a health check.
pub enum Severity {
    Info,
    Warning,
}

/// Remediation for an issue reported by a health check.
pub enum Remediation {
    /// A message to display to the user.
    Message(String),
    /// A hyperlink to a page containing more details and remediation.
    Link(String),
}

/// Report to be displayed to the user on the console.
pub struct DisplayReport {
    /// The health check that generated this report.
    pub health_check_type: HealthCheckType,

    /// The severity of the issue reported by the health check.
    pub severity: Severity,

    /// The message to display to the user.
    pub message: String,

    /// The remediation for the issue reported by the health check.
    /// This is optional because some health checks may not have a remediation.
    pub remediation: Option<Remediation>,
}

/// Report generated by a health check.
pub struct Report {
    /// Display report to be shown to the user. Some health checks may only log tags.
    pub display_report: Option<DisplayReport>,

    /// Tags to be logged to scuba.
    pub tag: Option<String>,
}
