load("@fbcode_macros//build_defs:rust_library.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "dupe",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    deps = [
        "//buck2/gazebo/dupe_derive:dupe_derive",
    ],
)
