load("@fbcode_macros//build_defs:rust_library.bzl", "rust_library")
load("@fbsource//tools/build_defs:glob_defs.bzl", "glob")

oncall("buck2")

rust_library(
    name = "dupe",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    deps = [
        "//buck2/gazebo/dupe_derive:dupe_derive",
    ],
)
