// @generated
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.facebook.buck.cd.model.common;

@javax.annotation.Generated(value="protoc", comments="annotations:PostBuildParamsOrBuilder.java.pb.meta")
public interface PostBuildParamsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PostBuildParams)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string libraryJar = 1;</code>
   */
  java.lang.String getLibraryJar();
  /**
   * <code>string libraryJar = 1;</code>
   */
  com.google.protobuf.ByteString
      getLibraryJarBytes();

  /**
   * <code>string abiJar = 2;</code>
   */
  java.lang.String getAbiJar();
  /**
   * <code>string abiJar = 2;</code>
   */
  com.google.protobuf.ByteString
      getAbiJarBytes();

  /**
   * <code>string jvmAbiGen = 4;</code>
   */
  java.lang.String getJvmAbiGen();
  /**
   * <code>string jvmAbiGen = 4;</code>
   */
  com.google.protobuf.ByteString
      getJvmAbiGenBytes();

  /**
   * <code>string abiOutputDir = 5;</code>
   */
  java.lang.String getAbiOutputDir();
  /**
   * <code>string abiOutputDir = 5;</code>
   */
  com.google.protobuf.ByteString
      getAbiOutputDirBytes();

  /**
   * <code>repeated string usedClasses = 6;</code>
   */
  java.util.List<java.lang.String>
      getUsedClassesList();
  /**
   * <code>repeated string usedClasses = 6;</code>
   */
  int getUsedClassesCount();
  /**
   * <code>repeated string usedClasses = 6;</code>
   */
  java.lang.String getUsedClasses(int index);
  /**
   * <code>repeated string usedClasses = 6;</code>
   */
  com.google.protobuf.ByteString
      getUsedClassesBytes(int index);

  /**
   * <code>string depFile = 7;</code>
   */
  java.lang.String getDepFile();
  /**
   * <code>string depFile = 7;</code>
   */
  com.google.protobuf.ByteString
      getDepFileBytes();

  /**
   * <code>string jarToJarDirMap = 8;</code>
   */
  java.lang.String getJarToJarDirMap();
  /**
   * <code>string jarToJarDirMap = 8;</code>
   */
  com.google.protobuf.ByteString
      getJarToJarDirMapBytes();

  /**
   * <code>repeated string optionalDirs = 9;</code>
   */
  java.util.List<java.lang.String>
      getOptionalDirsList();
  /**
   * <code>repeated string optionalDirs = 9;</code>
   */
  int getOptionalDirsCount();
  /**
   * <code>repeated string optionalDirs = 9;</code>
   */
  java.lang.String getOptionalDirs(int index);
  /**
   * <code>repeated string optionalDirs = 9;</code>
   */
  com.google.protobuf.ByteString
      getOptionalDirsBytes(int index);

  /**
   * <code>string incrementalStateDir = 10;</code>
   */
  java.lang.String getIncrementalStateDir();
  /**
   * <code>string incrementalStateDir = 10;</code>
   */
  com.google.protobuf.ByteString
      getIncrementalStateDirBytes();

  /**
   * <code>bool shouldCreateClassAbi = 11;</code>
   */
  boolean getShouldCreateClassAbi();

  /**
   * <code>string usedJarsFile = 12;</code>
   */
  java.lang.String getUsedJarsFile();
  /**
   * <code>string usedJarsFile = 12;</code>
   */
  com.google.protobuf.ByteString
      getUsedJarsFileBytes();
}
