load("@fbcode//buck2/tests:buck_e2e.bzl", "buck2_e2e_test")

oncall("build_infra")

buck2_e2e_test(
    name = "test_subscribe",
    srcs = ["test_subscribe.py"],
    data_dir = "test_subscribe_data",
    env = {
        "BUCK2_EXPECT": "$(exe_target fbcode//buck2/tests/e2e/subscribe/buck2_expect:buck2_expect)",
    },
    serialize_test_cases = False,
    deps = [
    ],
)
