load("@prelude//toolchains/android/tools:build_rules.bzl", "buck_kotlin_library")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

buck_kotlin_library(
    name = "usedclasses",
    srcs = glob(["**/*.kt"]),
    labels = ["codegen_rule"],
    tests = [
        "prelude//toolchains/android/test/com/facebook/buck/jvm/kotlin/compilerplugins/usedclasses:usedclasses",
    ],
    visibility = ["PUBLIC"],
)
