// @generated
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kotlincd.proto

// Protobuf Java Version: 3.25.6
package com.facebook.buck.cd.model.kotlin;

@javax.annotation.Generated(value="protoc", comments="annotations:ActionMetadataOrBuilder.java.pb.meta")
public interface ActionMetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kotlincd.api.v1.ActionMetadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.kotlincd.api.v1.Metadata previousMetadata = 1;</code>
   * @return Whether the previousMetadata field is set.
   */
  boolean hasPreviousMetadata();
  /**
   * <code>.kotlincd.api.v1.Metadata previousMetadata = 1;</code>
   * @return The previousMetadata.
   */
  com.facebook.buck.cd.model.kotlin.Metadata getPreviousMetadata();
  /**
   * <code>.kotlincd.api.v1.Metadata previousMetadata = 1;</code>
   */
  com.facebook.buck.cd.model.kotlin.MetadataOrBuilder getPreviousMetadataOrBuilder();

  /**
   * <code>.kotlincd.api.v1.Metadata currentMetadata = 2;</code>
   * @return Whether the currentMetadata field is set.
   */
  boolean hasCurrentMetadata();
  /**
   * <code>.kotlincd.api.v1.Metadata currentMetadata = 2;</code>
   * @return The currentMetadata.
   */
  com.facebook.buck.cd.model.kotlin.Metadata getCurrentMetadata();
  /**
   * <code>.kotlincd.api.v1.Metadata currentMetadata = 2;</code>
   */
  com.facebook.buck.cd.model.kotlin.MetadataOrBuilder getCurrentMetadataOrBuilder();
}
