load("@prelude//toolchains/android/tools:build_rules.bzl", "standard_java_test")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

standard_java_test(
    name = "types",
    deps = [
        "prelude//toolchains/android/src/com/facebook/buck/util/types:types",
        "prelude//toolchains/android/third-party:junit",
    ],
)
