load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("build_infra")

source_listing()

# No-op in OSS.

config_setting(
    name = "arvr_mode",
    visibility = ["PUBLIC"],
)

constraint_value(
    name = "dev",
    constraint_setting = "//build_mode/constraints:core_build_mode",
    visibility = ["PUBLIC"],
)

constraint_value(
    name = "opt",
    constraint_setting = "//build_mode/constraints:core_build_mode",
    visibility = ["PUBLIC"],
)
