load("@prelude//toolchains/android/tools:build_rules.bzl", "buck_prebuilt_artifact")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

# See README.txt
buck_prebuilt_artifact(
    name = "agent.apk",
    # @oss-disable[end= ]: cas_digest = "1b188878f29e0875c5f5fa67ab69d3c53a0db264bb7b750a6b1e9bbc3a5060ef:3865223",
    visibility = ["PUBLIC"],
)
