load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("build_infra")

source_listing()

export_file(
    name = "__run_lpar_main__.py",
    src = "__run_lpar_main__.py",
    visibility = ["PUBLIC"],
)

export_file(
    name = "sitecustomize.py",
    src = "sitecustomize.py",
    visibility = ["PUBLIC"],
)

export_file(
    name = "_lpar_bootstrap.sh.template",
    src = "_lpar_bootstrap.sh.template",
    visibility = ["PUBLIC"],
)
