load("@fbcode_macros//build_defs:rust_library.bzl", "rust_library")

rust_library(
    name = "dice_tests",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    crate_root = "src/lib.rs",
    doctests = False,
    test_deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:async-trait",
        "fbsource//third-party/rust:derive_more",
        "fbsource//third-party/rust:parking_lot",
        "fbsource//third-party/rust:tempfile",
        "fbsource//third-party/rust:tokio",
        "//buck2/allocative/allocative:allocative",
        "//buck2/dice/dice:dice",
        "//buck2/gazebo/dupe:dupe",
        "//buck2/shed/more_futures:more_futures",
    ],
)
