# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is dual-licensed under either the MIT license found in the
# LICENSE-MIT file in the root directory of this source tree or the Apache
# License, Version 2.0 found in the LICENSE-APACHE file in the root directory
# of this source tree. You may select, at your option, one of the
# above-listed licenses.

load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("build_infra")

source_listing()

config_setting(
    name = "clang",
    constraint_values = [
        "prelude//compiler/constraints:clang",
    ],
    visibility = ["PUBLIC"],
)

config_setting(
    name = "gcc",
    constraint_values = [
        "prelude//compiler/constraints:gcc",
    ],
    visibility = ["PUBLIC"],
)

config_setting(
    name = "msvc",
    constraint_values = [
        "prelude//compiler/constraints:msvc",
    ],
    visibility = ["PUBLIC"],
)
