oncall("build_infra")

constraint_setting(
    name = "bootstrap",
    visibility = ["PUBLIC"],
)

constraint_value(
    name = "use_bootstrap",
    constraint_setting = ":bootstrap",
    visibility = ["PUBLIC"],
)
