load("@prelude//configurations:constraint_alias.bzl", "constraint_with_aliases")

oncall("build_infra")

constraint_with_aliases(
    name = "bootstrap",
    aliases = {},
    default = "unspecified",
    values = [
        "use",
        "unspecified",
    ],
    visibility = ["PUBLIC"],
)
