# @lint-ignore BUCKLINT missing-oncall-call-severe This file is unowned and will be deleted without notice (due to not having an owner to contact).  Do not depend on this file
constraint_setting(
    name = "bootstrap",
    visibility = ["PUBLIC"],
)

constraint_value(
    name = "use_bootstrap",
    constraint_setting = ":bootstrap",
    visibility = ["PUBLIC"],
)
