load("@prelude//toolchains/android/tools:build_rules.bzl", "buck_kotlin_library")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

buck_kotlin_library(
    name = "abtesting",
    srcs = glob(["**/*.kt"]),
    visibility = [
        "fbsource//xplat/toolchains/android/sdk/src/com/facebook/buck/jvm/kotlin/abtesting/...",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/kotlin/...",
        "prelude//toolchains/android/test/com/facebook/buck/jvm/kotlin/...",
    ],
)
