load("@prelude//toolchains/android/tools:build_rules.bzl", "buck_java_binary", "buck_kotlin_library")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

# compilercompat shims are bucketed by Kotlin minor version: every 2.3.x compiler
# uses the compilercompat/2.3.0 folder. Key off kotlin_version_for_upgrade_only_do_not_use
# (the same config the kotlincd toolchain selects the compiler jar from) so the shims
# always match the compiler actually run -- not kotlin_version, which can differ.
_KOTLIN_VERSION_PARTS = read_config("kotlin", "kotlin_version_for_upgrade_only_do_not_use", "2.2.0").split(".")

KOTLIN_VERSION = _KOTLIN_VERSION_PARTS[0] + "." + _KOTLIN_VERSION_PARTS[1] + ".0"

buck_kotlin_library(
    name = "k2-jvm-abi-gen-lib",
    srcs = glob(
        ["**/*.kt"],
        exclude = ["src/main/kotlin/compilercompat/2.*/*.kt"],
    )
    + glob(["src/main/kotlin/compilercompat/" + KOTLIN_VERSION + "/*.kt"]),
    labels = ["codegen_rule"],
    provided_deps = [
        "prelude//toolchains/android/third-party:kotlin-compiler-embeddable",
    ],
    resources = glob(["resources/**"]),
    resources_root = "resources",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "fbsource//fbandroid/java/com/facebook/kotlin/compilercompat:compilercompat",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/kotlin/compilerplugins/common:common",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/kotlin/compilerplugins/kosabi/common/stub:stub",
        "prelude//toolchains/android/third-party:kotlin-metadata-jvm",
        "prelude//toolchains/android/third-party:kotlin-stdlib",
        "prelude//toolchains/android/third-party:kotlinx-coroutines-core-jvm",
    ],
)

buck_java_binary(
    name = "k2-jvm-abi-gen",
    visibility = ["PUBLIC"],
    deps = [":k2-jvm-abi-gen-lib"],
)
