load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "buck2_sketches",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//buck2/shed/setsketch:setsketch",
    ],
)
