load(
    "@prelude//toolchains/android/tools:build_rules.bzl",
    "buck_java_test",
)
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

buck_java_test(
    name = "build_config",
    srcs = glob(["*.java"]),
    deps = [
        "prelude//toolchains/android/src/com/facebook/buck/android/build_config:build_config",
        "prelude//toolchains/android/test/com/facebook/buck/testutil:testutil",
        "prelude//toolchains/android/third-party:guava",
        "prelude//toolchains/android/third-party:junit",
    ],
)
