load("@prelude//toolchains/android/tools:build_rules.bzl", "buck_java_library", "standard_java_test")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

buck_java_library(
    name = "testutil",
    srcs = glob(
        ["*.java"],
        exclude = [
            "*Benchmark.java",
            "*Test.java",
        ],
    ),
    visibility = ["prelude//toolchains/android/test/..."],
    deps = [
        "prelude//toolchains/android/src/com/facebook/buck/test/selectors:selectors",
        "prelude//toolchains/android/third-party:hamcrest",
    ],
)

standard_java_test(
    name = "selectors",
    deps = [
        "prelude//toolchains/android/src/com/facebook/buck/test/selectors:selectors",
        "prelude//toolchains/android/test/com/facebook/buck/test/selectors:testutil",
        "prelude//toolchains/android/third-party:guava",
        "prelude//toolchains/android/third-party:junit",
    ],
)
