load("@fbcode//buck2/tests:buck_e2e.bzl", "buck2_e2e_test")

oncall("build_infra")

buck2_e2e_test(
    name = "test_lint_and_typecheck",
    srcs = ["test_lint_and_typecheck.py"],
    data_dir = "test_lint_and_typecheck_data",
)
