// @generated
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: javacd.proto

package com.facebook.buck.cd.model.java;

@javax.annotation.Generated(value="protoc", comments="annotations:BuildJavaCommandOrBuilder.java.pb.meta")
public interface BuildJavaCommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:javacd.api.v1.BuildJavaCommand)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.javacd.api.v1.BuildCommand buildCommand = 1;</code>
   */
  boolean hasBuildCommand();
  /**
   * <code>.javacd.api.v1.BuildCommand buildCommand = 1;</code>
   */
  com.facebook.buck.cd.model.java.BuildCommand getBuildCommand();
  /**
   * <code>.javacd.api.v1.BuildCommand buildCommand = 1;</code>
   */
  com.facebook.buck.cd.model.java.BuildCommandOrBuilder getBuildCommandOrBuilder();

  /**
   * <code>.PostBuildParams postBuildParams = 3;</code>
   */
  boolean hasPostBuildParams();
  /**
   * <code>.PostBuildParams postBuildParams = 3;</code>
   */
  com.facebook.buck.cd.model.common.PostBuildParams getPostBuildParams();
  /**
   * <code>.PostBuildParams postBuildParams = 3;</code>
   */
  com.facebook.buck.cd.model.common.PostBuildParamsOrBuilder getPostBuildParamsOrBuilder();
}
