// @generated
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: javacd.proto

// Protobuf Java Version: 3.25.6
package com.facebook.buck.cd.model.java;

@javax.annotation.Generated(value="protoc", comments="annotations:BuildTargetValueOrBuilder.java.pb.meta")
public interface BuildTargetValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:javacd.api.v1.BuildTargetValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string fullyQualifiedName = 1;</code>
   * @return The fullyQualifiedName.
   */
  java.lang.String getFullyQualifiedName();
  /**
   * <code>string fullyQualifiedName = 1;</code>
   * @return The bytes for fullyQualifiedName.
   */
  com.google.protobuf.ByteString
      getFullyQualifiedNameBytes();

  /**
   * <code>.javacd.api.v1.BuildTargetValue.Type type = 2;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.javacd.api.v1.BuildTargetValue.Type type = 2;</code>
   * @return The type.
   */
  com.facebook.buck.cd.model.java.BuildTargetValue.Type getType();
}
