// @generated
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: javacd.proto

// Protobuf Java Version: 3.25.6
package com.facebook.buck.cd.model.java;

@javax.annotation.Generated(value="protoc", comments="annotations:OutputPathsValueOrBuilder.java.pb.meta")
public interface OutputPathsValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:javacd.api.v1.OutputPathsValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.javacd.api.v1.OutputPathsValue.OutputPaths libraryPaths = 1;</code>
   * @return Whether the libraryPaths field is set.
   */
  boolean hasLibraryPaths();
  /**
   * <code>.javacd.api.v1.OutputPathsValue.OutputPaths libraryPaths = 1;</code>
   * @return The libraryPaths.
   */
  com.facebook.buck.cd.model.java.OutputPathsValue.OutputPaths getLibraryPaths();
  /**
   * <code>.javacd.api.v1.OutputPathsValue.OutputPaths libraryPaths = 1;</code>
   */
  com.facebook.buck.cd.model.java.OutputPathsValue.OutputPathsOrBuilder getLibraryPathsOrBuilder();

  /**
   * <code>.javacd.api.v1.OutputPathsValue.OutputPaths sourceAbiPaths = 2;</code>
   * @return Whether the sourceAbiPaths field is set.
   */
  boolean hasSourceAbiPaths();
  /**
   * <code>.javacd.api.v1.OutputPathsValue.OutputPaths sourceAbiPaths = 2;</code>
   * @return The sourceAbiPaths.
   */
  com.facebook.buck.cd.model.java.OutputPathsValue.OutputPaths getSourceAbiPaths();
  /**
   * <code>.javacd.api.v1.OutputPathsValue.OutputPaths sourceAbiPaths = 2;</code>
   */
  com.facebook.buck.cd.model.java.OutputPathsValue.OutputPathsOrBuilder getSourceAbiPathsOrBuilder();

  /**
   * <code>.javacd.api.v1.OutputPathsValue.OutputPaths sourceOnlyAbiPaths = 3;</code>
   * @return Whether the sourceOnlyAbiPaths field is set.
   */
  boolean hasSourceOnlyAbiPaths();
  /**
   * <code>.javacd.api.v1.OutputPathsValue.OutputPaths sourceOnlyAbiPaths = 3;</code>
   * @return The sourceOnlyAbiPaths.
   */
  com.facebook.buck.cd.model.java.OutputPathsValue.OutputPaths getSourceOnlyAbiPaths();
  /**
   * <code>.javacd.api.v1.OutputPathsValue.OutputPaths sourceOnlyAbiPaths = 3;</code>
   */
  com.facebook.buck.cd.model.java.OutputPathsValue.OutputPathsOrBuilder getSourceOnlyAbiPathsOrBuilder();

  /**
   * <code>string libraryTargetFullyQualifiedName = 4;</code>
   * @return The libraryTargetFullyQualifiedName.
   */
  java.lang.String getLibraryTargetFullyQualifiedName();
  /**
   * <code>string libraryTargetFullyQualifiedName = 4;</code>
   * @return The bytes for libraryTargetFullyQualifiedName.
   */
  com.google.protobuf.ByteString
      getLibraryTargetFullyQualifiedNameBytes();
}
