// @generated
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: javacd.proto

// Protobuf Java Version: 3.25.6
package com.facebook.buck.cd.model.java;

/**
 * Protobuf type {@code javacd.api.v1.ResolvedJavac}
 */
@javax.annotation.Generated(value="protoc", comments="annotations:ResolvedJavac.java.pb.meta")
public final class ResolvedJavac extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:javacd.api.v1.ResolvedJavac)
    ResolvedJavacOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ResolvedJavac.newBuilder() to construct.
  private ResolvedJavac(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ResolvedJavac() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ResolvedJavac();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.facebook.buck.cd.model.java.JavaCDProto.internal_static_javacd_api_v1_ResolvedJavac_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.facebook.buck.cd.model.java.JavaCDProto.internal_static_javacd_api_v1_ResolvedJavac_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.facebook.buck.cd.model.java.ResolvedJavac.class, com.facebook.buck.cd.model.java.ResolvedJavac.Builder.class);
  }

  public interface ExternalJavacOrBuilder extends
      // @@protoc_insertion_point(interface_extends:javacd.api.v1.ResolvedJavac.ExternalJavac)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string shortName = 1;</code>
     * @return The shortName.
     */
    java.lang.String getShortName();
    /**
     * <code>string shortName = 1;</code>
     * @return The bytes for shortName.
     */
    com.google.protobuf.ByteString
        getShortNameBytes();

    /**
     * <code>repeated string commandPrefix = 2;</code>
     * @return A list containing the commandPrefix.
     */
    java.util.List<java.lang.String>
        getCommandPrefixList();
    /**
     * <code>repeated string commandPrefix = 2;</code>
     * @return The count of commandPrefix.
     */
    int getCommandPrefixCount();
    /**
     * <code>repeated string commandPrefix = 2;</code>
     * @param index The index of the element to return.
     * @return The commandPrefix at the given index.
     */
    java.lang.String getCommandPrefix(int index);
    /**
     * <code>repeated string commandPrefix = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the commandPrefix at the given index.
     */
    com.google.protobuf.ByteString
        getCommandPrefixBytes(int index);
  }
  /**
   * Protobuf type {@code javacd.api.v1.ResolvedJavac.ExternalJavac}
   */
  public static final class ExternalJavac extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:javacd.api.v1.ResolvedJavac.ExternalJavac)
      ExternalJavacOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ExternalJavac.newBuilder() to construct.
    private ExternalJavac(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ExternalJavac() {
      shortName_ = "";
      commandPrefix_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ExternalJavac();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.facebook.buck.cd.model.java.JavaCDProto.internal_static_javacd_api_v1_ResolvedJavac_ExternalJavac_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.facebook.buck.cd.model.java.JavaCDProto.internal_static_javacd_api_v1_ResolvedJavac_ExternalJavac_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac.class, com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac.Builder.class);
    }

    public static final int SHORTNAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object shortName_ = "";
    /**
     * <code>string shortName = 1;</code>
     * @return The shortName.
     */
    @java.lang.Override
    public java.lang.String getShortName() {
      java.lang.Object ref = shortName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        shortName_ = s;
        return s;
      }
    }
    /**
     * <code>string shortName = 1;</code>
     * @return The bytes for shortName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getShortNameBytes() {
      java.lang.Object ref = shortName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        shortName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMMANDPREFIX_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList commandPrefix_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string commandPrefix = 2;</code>
     * @return A list containing the commandPrefix.
     */
    public com.google.protobuf.ProtocolStringList
        getCommandPrefixList() {
      return commandPrefix_;
    }
    /**
     * <code>repeated string commandPrefix = 2;</code>
     * @return The count of commandPrefix.
     */
    public int getCommandPrefixCount() {
      return commandPrefix_.size();
    }
    /**
     * <code>repeated string commandPrefix = 2;</code>
     * @param index The index of the element to return.
     * @return The commandPrefix at the given index.
     */
    public java.lang.String getCommandPrefix(int index) {
      return commandPrefix_.get(index);
    }
    /**
     * <code>repeated string commandPrefix = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the commandPrefix at the given index.
     */
    public com.google.protobuf.ByteString
        getCommandPrefixBytes(int index) {
      return commandPrefix_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(shortName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, shortName_);
      }
      for (int i = 0; i < commandPrefix_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, commandPrefix_.getRaw(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(shortName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, shortName_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < commandPrefix_.size(); i++) {
          dataSize += computeStringSizeNoTag(commandPrefix_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getCommandPrefixList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac)) {
        return super.equals(obj);
      }
      com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac other = (com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac) obj;

      if (!getShortName()
          .equals(other.getShortName())) return false;
      if (!getCommandPrefixList()
          .equals(other.getCommandPrefixList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SHORTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getShortName().hashCode();
      if (getCommandPrefixCount() > 0) {
        hash = (37 * hash) + COMMANDPREFIX_FIELD_NUMBER;
        hash = (53 * hash) + getCommandPrefixList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code javacd.api.v1.ResolvedJavac.ExternalJavac}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:javacd.api.v1.ResolvedJavac.ExternalJavac)
        com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavacOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.facebook.buck.cd.model.java.JavaCDProto.internal_static_javacd_api_v1_ResolvedJavac_ExternalJavac_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.facebook.buck.cd.model.java.JavaCDProto.internal_static_javacd_api_v1_ResolvedJavac_ExternalJavac_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac.class, com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac.Builder.class);
      }

      // Construct using com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        shortName_ = "";
        commandPrefix_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.facebook.buck.cd.model.java.JavaCDProto.internal_static_javacd_api_v1_ResolvedJavac_ExternalJavac_descriptor;
      }

      @java.lang.Override
      public com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac getDefaultInstanceForType() {
        return com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac.getDefaultInstance();
      }

      @java.lang.Override
      public com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac build() {
        com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac buildPartial() {
        com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac result = new com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.shortName_ = shortName_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          commandPrefix_.makeImmutable();
          result.commandPrefix_ = commandPrefix_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac) {
          return mergeFrom((com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac other) {
        if (other == com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac.getDefaultInstance()) return this;
        if (!other.getShortName().isEmpty()) {
          shortName_ = other.shortName_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.commandPrefix_.isEmpty()) {
          if (commandPrefix_.isEmpty()) {
            commandPrefix_ = other.commandPrefix_;
            bitField0_ |= 0x00000002;
          } else {
            ensureCommandPrefixIsMutable();
            commandPrefix_.addAll(other.commandPrefix_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                shortName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureCommandPrefixIsMutable();
                commandPrefix_.add(s);
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object shortName_ = "";
      /**
       * <code>string shortName = 1;</code>
       * @return The shortName.
       */
      public java.lang.String getShortName() {
        java.lang.Object ref = shortName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          shortName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string shortName = 1;</code>
       * @return The bytes for shortName.
       */
      public com.google.protobuf.ByteString
          getShortNameBytes() {
        java.lang.Object ref = shortName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          shortName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string shortName = 1;</code>
       * @param value The shortName to set.
       * @return This builder for chaining.
       */
      public Builder setShortName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        shortName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string shortName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearShortName() {
        shortName_ = getDefaultInstance().getShortName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string shortName = 1;</code>
       * @param value The bytes for shortName to set.
       * @return This builder for chaining.
       */
      public Builder setShortNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        shortName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList commandPrefix_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureCommandPrefixIsMutable() {
        if (!commandPrefix_.isModifiable()) {
          commandPrefix_ = new com.google.protobuf.LazyStringArrayList(commandPrefix_);
        }
        bitField0_ |= 0x00000002;
      }
      /**
       * <code>repeated string commandPrefix = 2;</code>
       * @return A list containing the commandPrefix.
       */
      public com.google.protobuf.ProtocolStringList
          getCommandPrefixList() {
        commandPrefix_.makeImmutable();
        return commandPrefix_;
      }
      /**
       * <code>repeated string commandPrefix = 2;</code>
       * @return The count of commandPrefix.
       */
      public int getCommandPrefixCount() {
        return commandPrefix_.size();
      }
      /**
       * <code>repeated string commandPrefix = 2;</code>
       * @param index The index of the element to return.
       * @return The commandPrefix at the given index.
       */
      public java.lang.String getCommandPrefix(int index) {
        return commandPrefix_.get(index);
      }
      /**
       * <code>repeated string commandPrefix = 2;</code>
       * @param index The index of the value to return.
       * @return The bytes of the commandPrefix at the given index.
       */
      public com.google.protobuf.ByteString
          getCommandPrefixBytes(int index) {
        return commandPrefix_.getByteString(index);
      }
      /**
       * <code>repeated string commandPrefix = 2;</code>
       * @param index The index to set the value at.
       * @param value The commandPrefix to set.
       * @return This builder for chaining.
       */
      public Builder setCommandPrefix(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureCommandPrefixIsMutable();
        commandPrefix_.set(index, value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string commandPrefix = 2;</code>
       * @param value The commandPrefix to add.
       * @return This builder for chaining.
       */
      public Builder addCommandPrefix(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureCommandPrefixIsMutable();
        commandPrefix_.add(value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string commandPrefix = 2;</code>
       * @param values The commandPrefix to add.
       * @return This builder for chaining.
       */
      public Builder addAllCommandPrefix(
          java.lang.Iterable<java.lang.String> values) {
        ensureCommandPrefixIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, commandPrefix_);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string commandPrefix = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCommandPrefix() {
        commandPrefix_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string commandPrefix = 2;</code>
       * @param value The bytes of the commandPrefix to add.
       * @return This builder for chaining.
       */
      public Builder addCommandPrefixBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureCommandPrefixIsMutable();
        commandPrefix_.add(value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:javacd.api.v1.ResolvedJavac.ExternalJavac)
    }

    // @@protoc_insertion_point(class_scope:javacd.api.v1.ResolvedJavac.ExternalJavac)
    private static final com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac();
    }

    public static com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ExternalJavac>
        PARSER = new com.google.protobuf.AbstractParser<ExternalJavac>() {
      @java.lang.Override
      public ExternalJavac parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ExternalJavac> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ExternalJavac> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface JSR199JavacOrBuilder extends
      // @@protoc_insertion_point(interface_extends:javacd.api.v1.ResolvedJavac.JSR199Javac)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code javacd.api.v1.ResolvedJavac.JSR199Javac}
   */
  public static final class JSR199Javac extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:javacd.api.v1.ResolvedJavac.JSR199Javac)
      JSR199JavacOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use JSR199Javac.newBuilder() to construct.
    private JSR199Javac(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private JSR199Javac() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new JSR199Javac();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.facebook.buck.cd.model.java.JavaCDProto.internal_static_javacd_api_v1_ResolvedJavac_JSR199Javac_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.facebook.buck.cd.model.java.JavaCDProto.internal_static_javacd_api_v1_ResolvedJavac_JSR199Javac_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac.class, com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac)) {
        return super.equals(obj);
      }
      com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac other = (com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code javacd.api.v1.ResolvedJavac.JSR199Javac}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:javacd.api.v1.ResolvedJavac.JSR199Javac)
        com.facebook.buck.cd.model.java.ResolvedJavac.JSR199JavacOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.facebook.buck.cd.model.java.JavaCDProto.internal_static_javacd_api_v1_ResolvedJavac_JSR199Javac_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.facebook.buck.cd.model.java.JavaCDProto.internal_static_javacd_api_v1_ResolvedJavac_JSR199Javac_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac.class, com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac.Builder.class);
      }

      // Construct using com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.facebook.buck.cd.model.java.JavaCDProto.internal_static_javacd_api_v1_ResolvedJavac_JSR199Javac_descriptor;
      }

      @java.lang.Override
      public com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac getDefaultInstanceForType() {
        return com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac.getDefaultInstance();
      }

      @java.lang.Override
      public com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac build() {
        com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac buildPartial() {
        com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac result = new com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac) {
          return mergeFrom((com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac other) {
        if (other == com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:javacd.api.v1.ResolvedJavac.JSR199Javac)
    }

    // @@protoc_insertion_point(class_scope:javacd.api.v1.ResolvedJavac.JSR199Javac)
    private static final com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac();
    }

    public static com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<JSR199Javac>
        PARSER = new com.google.protobuf.AbstractParser<JSR199Javac>() {
      @java.lang.Override
      public JSR199Javac parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<JSR199Javac> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<JSR199Javac> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int javacCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object javac_;
  public enum JavacCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    EXTERNALJAVAC(1),
    JSR199JAVAC(2),
    JAVAC_NOT_SET(0);
    private final int value;
    private JavacCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static JavacCase valueOf(int value) {
      return forNumber(value);
    }

    public static JavacCase forNumber(int value) {
      switch (value) {
        case 1: return EXTERNALJAVAC;
        case 2: return JSR199JAVAC;
        case 0: return JAVAC_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public JavacCase
  getJavacCase() {
    return JavacCase.forNumber(
        javacCase_);
  }

  public static final int EXTERNALJAVAC_FIELD_NUMBER = 1;
  /**
   * <code>.javacd.api.v1.ResolvedJavac.ExternalJavac externalJavac = 1;</code>
   * @return Whether the externalJavac field is set.
   */
  @java.lang.Override
  public boolean hasExternalJavac() {
    return javacCase_ == 1;
  }
  /**
   * <code>.javacd.api.v1.ResolvedJavac.ExternalJavac externalJavac = 1;</code>
   * @return The externalJavac.
   */
  @java.lang.Override
  public com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac getExternalJavac() {
    if (javacCase_ == 1) {
       return (com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac) javac_;
    }
    return com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac.getDefaultInstance();
  }
  /**
   * <code>.javacd.api.v1.ResolvedJavac.ExternalJavac externalJavac = 1;</code>
   */
  @java.lang.Override
  public com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavacOrBuilder getExternalJavacOrBuilder() {
    if (javacCase_ == 1) {
       return (com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac) javac_;
    }
    return com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac.getDefaultInstance();
  }

  public static final int JSR199JAVAC_FIELD_NUMBER = 2;
  /**
   * <code>.javacd.api.v1.ResolvedJavac.JSR199Javac jsr199Javac = 2;</code>
   * @return Whether the jsr199Javac field is set.
   */
  @java.lang.Override
  public boolean hasJsr199Javac() {
    return javacCase_ == 2;
  }
  /**
   * <code>.javacd.api.v1.ResolvedJavac.JSR199Javac jsr199Javac = 2;</code>
   * @return The jsr199Javac.
   */
  @java.lang.Override
  public com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac getJsr199Javac() {
    if (javacCase_ == 2) {
       return (com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac) javac_;
    }
    return com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac.getDefaultInstance();
  }
  /**
   * <code>.javacd.api.v1.ResolvedJavac.JSR199Javac jsr199Javac = 2;</code>
   */
  @java.lang.Override
  public com.facebook.buck.cd.model.java.ResolvedJavac.JSR199JavacOrBuilder getJsr199JavacOrBuilder() {
    if (javacCase_ == 2) {
       return (com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac) javac_;
    }
    return com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (javacCase_ == 1) {
      output.writeMessage(1, (com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac) javac_);
    }
    if (javacCase_ == 2) {
      output.writeMessage(2, (com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac) javac_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (javacCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac) javac_);
    }
    if (javacCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac) javac_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.facebook.buck.cd.model.java.ResolvedJavac)) {
      return super.equals(obj);
    }
    com.facebook.buck.cd.model.java.ResolvedJavac other = (com.facebook.buck.cd.model.java.ResolvedJavac) obj;

    if (!getJavacCase().equals(other.getJavacCase())) return false;
    switch (javacCase_) {
      case 1:
        if (!getExternalJavac()
            .equals(other.getExternalJavac())) return false;
        break;
      case 2:
        if (!getJsr199Javac()
            .equals(other.getJsr199Javac())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (javacCase_) {
      case 1:
        hash = (37 * hash) + EXTERNALJAVAC_FIELD_NUMBER;
        hash = (53 * hash) + getExternalJavac().hashCode();
        break;
      case 2:
        hash = (37 * hash) + JSR199JAVAC_FIELD_NUMBER;
        hash = (53 * hash) + getJsr199Javac().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.facebook.buck.cd.model.java.ResolvedJavac parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.facebook.buck.cd.model.java.ResolvedJavac parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.facebook.buck.cd.model.java.ResolvedJavac parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.facebook.buck.cd.model.java.ResolvedJavac parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.facebook.buck.cd.model.java.ResolvedJavac parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.facebook.buck.cd.model.java.ResolvedJavac parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.facebook.buck.cd.model.java.ResolvedJavac parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.facebook.buck.cd.model.java.ResolvedJavac parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.facebook.buck.cd.model.java.ResolvedJavac parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.facebook.buck.cd.model.java.ResolvedJavac parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.facebook.buck.cd.model.java.ResolvedJavac parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.facebook.buck.cd.model.java.ResolvedJavac parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.facebook.buck.cd.model.java.ResolvedJavac prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code javacd.api.v1.ResolvedJavac}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:javacd.api.v1.ResolvedJavac)
      com.facebook.buck.cd.model.java.ResolvedJavacOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.facebook.buck.cd.model.java.JavaCDProto.internal_static_javacd_api_v1_ResolvedJavac_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.facebook.buck.cd.model.java.JavaCDProto.internal_static_javacd_api_v1_ResolvedJavac_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.facebook.buck.cd.model.java.ResolvedJavac.class, com.facebook.buck.cd.model.java.ResolvedJavac.Builder.class);
    }

    // Construct using com.facebook.buck.cd.model.java.ResolvedJavac.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (externalJavacBuilder_ != null) {
        externalJavacBuilder_.clear();
      }
      if (jsr199JavacBuilder_ != null) {
        jsr199JavacBuilder_.clear();
      }
      javacCase_ = 0;
      javac_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.facebook.buck.cd.model.java.JavaCDProto.internal_static_javacd_api_v1_ResolvedJavac_descriptor;
    }

    @java.lang.Override
    public com.facebook.buck.cd.model.java.ResolvedJavac getDefaultInstanceForType() {
      return com.facebook.buck.cd.model.java.ResolvedJavac.getDefaultInstance();
    }

    @java.lang.Override
    public com.facebook.buck.cd.model.java.ResolvedJavac build() {
      com.facebook.buck.cd.model.java.ResolvedJavac result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.facebook.buck.cd.model.java.ResolvedJavac buildPartial() {
      com.facebook.buck.cd.model.java.ResolvedJavac result = new com.facebook.buck.cd.model.java.ResolvedJavac(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.facebook.buck.cd.model.java.ResolvedJavac result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(com.facebook.buck.cd.model.java.ResolvedJavac result) {
      result.javacCase_ = javacCase_;
      result.javac_ = this.javac_;
      if (javacCase_ == 1 &&
          externalJavacBuilder_ != null) {
        result.javac_ = externalJavacBuilder_.build();
      }
      if (javacCase_ == 2 &&
          jsr199JavacBuilder_ != null) {
        result.javac_ = jsr199JavacBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.facebook.buck.cd.model.java.ResolvedJavac) {
        return mergeFrom((com.facebook.buck.cd.model.java.ResolvedJavac)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.facebook.buck.cd.model.java.ResolvedJavac other) {
      if (other == com.facebook.buck.cd.model.java.ResolvedJavac.getDefaultInstance()) return this;
      switch (other.getJavacCase()) {
        case EXTERNALJAVAC: {
          mergeExternalJavac(other.getExternalJavac());
          break;
        }
        case JSR199JAVAC: {
          mergeJsr199Javac(other.getJsr199Javac());
          break;
        }
        case JAVAC_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getExternalJavacFieldBuilder().getBuilder(),
                  extensionRegistry);
              javacCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getJsr199JavacFieldBuilder().getBuilder(),
                  extensionRegistry);
              javacCase_ = 2;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int javacCase_ = 0;
    private java.lang.Object javac_;
    public JavacCase
        getJavacCase() {
      return JavacCase.forNumber(
          javacCase_);
    }

    public Builder clearJavac() {
      javacCase_ = 0;
      javac_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilderV3<
        com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac, com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac.Builder, com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavacOrBuilder> externalJavacBuilder_;
    /**
     * <code>.javacd.api.v1.ResolvedJavac.ExternalJavac externalJavac = 1;</code>
     * @return Whether the externalJavac field is set.
     */
    @java.lang.Override
    public boolean hasExternalJavac() {
      return javacCase_ == 1;
    }
    /**
     * <code>.javacd.api.v1.ResolvedJavac.ExternalJavac externalJavac = 1;</code>
     * @return The externalJavac.
     */
    @java.lang.Override
    public com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac getExternalJavac() {
      if (externalJavacBuilder_ == null) {
        if (javacCase_ == 1) {
          return (com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac) javac_;
        }
        return com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac.getDefaultInstance();
      } else {
        if (javacCase_ == 1) {
          return externalJavacBuilder_.getMessage();
        }
        return com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac.getDefaultInstance();
      }
    }
    /**
     * <code>.javacd.api.v1.ResolvedJavac.ExternalJavac externalJavac = 1;</code>
     */
    public Builder setExternalJavac(com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac value) {
      if (externalJavacBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        javac_ = value;
        onChanged();
      } else {
        externalJavacBuilder_.setMessage(value);
      }
      javacCase_ = 1;
      return this;
    }
    /**
     * <code>.javacd.api.v1.ResolvedJavac.ExternalJavac externalJavac = 1;</code>
     */
    public Builder setExternalJavac(
        com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac.Builder builderForValue) {
      if (externalJavacBuilder_ == null) {
        javac_ = builderForValue.build();
        onChanged();
      } else {
        externalJavacBuilder_.setMessage(builderForValue.build());
      }
      javacCase_ = 1;
      return this;
    }
    /**
     * <code>.javacd.api.v1.ResolvedJavac.ExternalJavac externalJavac = 1;</code>
     */
    public Builder mergeExternalJavac(com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac value) {
      if (externalJavacBuilder_ == null) {
        if (javacCase_ == 1 &&
            javac_ != com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac.getDefaultInstance()) {
          javac_ = com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac.newBuilder((com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac) javac_)
              .mergeFrom(value).buildPartial();
        } else {
          javac_ = value;
        }
        onChanged();
      } else {
        if (javacCase_ == 1) {
          externalJavacBuilder_.mergeFrom(value);
        } else {
          externalJavacBuilder_.setMessage(value);
        }
      }
      javacCase_ = 1;
      return this;
    }
    /**
     * <code>.javacd.api.v1.ResolvedJavac.ExternalJavac externalJavac = 1;</code>
     */
    public Builder clearExternalJavac() {
      if (externalJavacBuilder_ == null) {
        if (javacCase_ == 1) {
          javacCase_ = 0;
          javac_ = null;
          onChanged();
        }
      } else {
        if (javacCase_ == 1) {
          javacCase_ = 0;
          javac_ = null;
        }
        externalJavacBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.javacd.api.v1.ResolvedJavac.ExternalJavac externalJavac = 1;</code>
     */
    public com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac.Builder getExternalJavacBuilder() {
      return getExternalJavacFieldBuilder().getBuilder();
    }
    /**
     * <code>.javacd.api.v1.ResolvedJavac.ExternalJavac externalJavac = 1;</code>
     */
    @java.lang.Override
    public com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavacOrBuilder getExternalJavacOrBuilder() {
      if ((javacCase_ == 1) && (externalJavacBuilder_ != null)) {
        return externalJavacBuilder_.getMessageOrBuilder();
      } else {
        if (javacCase_ == 1) {
          return (com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac) javac_;
        }
        return com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac.getDefaultInstance();
      }
    }
    /**
     * <code>.javacd.api.v1.ResolvedJavac.ExternalJavac externalJavac = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac, com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac.Builder, com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavacOrBuilder> 
        getExternalJavacFieldBuilder() {
      if (externalJavacBuilder_ == null) {
        if (!(javacCase_ == 1)) {
          javac_ = com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac.getDefaultInstance();
        }
        externalJavacBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac, com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac.Builder, com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavacOrBuilder>(
                (com.facebook.buck.cd.model.java.ResolvedJavac.ExternalJavac) javac_,
                getParentForChildren(),
                isClean());
        javac_ = null;
      }
      javacCase_ = 1;
      onChanged();
      return externalJavacBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac, com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac.Builder, com.facebook.buck.cd.model.java.ResolvedJavac.JSR199JavacOrBuilder> jsr199JavacBuilder_;
    /**
     * <code>.javacd.api.v1.ResolvedJavac.JSR199Javac jsr199Javac = 2;</code>
     * @return Whether the jsr199Javac field is set.
     */
    @java.lang.Override
    public boolean hasJsr199Javac() {
      return javacCase_ == 2;
    }
    /**
     * <code>.javacd.api.v1.ResolvedJavac.JSR199Javac jsr199Javac = 2;</code>
     * @return The jsr199Javac.
     */
    @java.lang.Override
    public com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac getJsr199Javac() {
      if (jsr199JavacBuilder_ == null) {
        if (javacCase_ == 2) {
          return (com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac) javac_;
        }
        return com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac.getDefaultInstance();
      } else {
        if (javacCase_ == 2) {
          return jsr199JavacBuilder_.getMessage();
        }
        return com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac.getDefaultInstance();
      }
    }
    /**
     * <code>.javacd.api.v1.ResolvedJavac.JSR199Javac jsr199Javac = 2;</code>
     */
    public Builder setJsr199Javac(com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac value) {
      if (jsr199JavacBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        javac_ = value;
        onChanged();
      } else {
        jsr199JavacBuilder_.setMessage(value);
      }
      javacCase_ = 2;
      return this;
    }
    /**
     * <code>.javacd.api.v1.ResolvedJavac.JSR199Javac jsr199Javac = 2;</code>
     */
    public Builder setJsr199Javac(
        com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac.Builder builderForValue) {
      if (jsr199JavacBuilder_ == null) {
        javac_ = builderForValue.build();
        onChanged();
      } else {
        jsr199JavacBuilder_.setMessage(builderForValue.build());
      }
      javacCase_ = 2;
      return this;
    }
    /**
     * <code>.javacd.api.v1.ResolvedJavac.JSR199Javac jsr199Javac = 2;</code>
     */
    public Builder mergeJsr199Javac(com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac value) {
      if (jsr199JavacBuilder_ == null) {
        if (javacCase_ == 2 &&
            javac_ != com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac.getDefaultInstance()) {
          javac_ = com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac.newBuilder((com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac) javac_)
              .mergeFrom(value).buildPartial();
        } else {
          javac_ = value;
        }
        onChanged();
      } else {
        if (javacCase_ == 2) {
          jsr199JavacBuilder_.mergeFrom(value);
        } else {
          jsr199JavacBuilder_.setMessage(value);
        }
      }
      javacCase_ = 2;
      return this;
    }
    /**
     * <code>.javacd.api.v1.ResolvedJavac.JSR199Javac jsr199Javac = 2;</code>
     */
    public Builder clearJsr199Javac() {
      if (jsr199JavacBuilder_ == null) {
        if (javacCase_ == 2) {
          javacCase_ = 0;
          javac_ = null;
          onChanged();
        }
      } else {
        if (javacCase_ == 2) {
          javacCase_ = 0;
          javac_ = null;
        }
        jsr199JavacBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.javacd.api.v1.ResolvedJavac.JSR199Javac jsr199Javac = 2;</code>
     */
    public com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac.Builder getJsr199JavacBuilder() {
      return getJsr199JavacFieldBuilder().getBuilder();
    }
    /**
     * <code>.javacd.api.v1.ResolvedJavac.JSR199Javac jsr199Javac = 2;</code>
     */
    @java.lang.Override
    public com.facebook.buck.cd.model.java.ResolvedJavac.JSR199JavacOrBuilder getJsr199JavacOrBuilder() {
      if ((javacCase_ == 2) && (jsr199JavacBuilder_ != null)) {
        return jsr199JavacBuilder_.getMessageOrBuilder();
      } else {
        if (javacCase_ == 2) {
          return (com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac) javac_;
        }
        return com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac.getDefaultInstance();
      }
    }
    /**
     * <code>.javacd.api.v1.ResolvedJavac.JSR199Javac jsr199Javac = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac, com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac.Builder, com.facebook.buck.cd.model.java.ResolvedJavac.JSR199JavacOrBuilder> 
        getJsr199JavacFieldBuilder() {
      if (jsr199JavacBuilder_ == null) {
        if (!(javacCase_ == 2)) {
          javac_ = com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac.getDefaultInstance();
        }
        jsr199JavacBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac, com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac.Builder, com.facebook.buck.cd.model.java.ResolvedJavac.JSR199JavacOrBuilder>(
                (com.facebook.buck.cd.model.java.ResolvedJavac.JSR199Javac) javac_,
                getParentForChildren(),
                isClean());
        javac_ = null;
      }
      javacCase_ = 2;
      onChanged();
      return jsr199JavacBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:javacd.api.v1.ResolvedJavac)
  }

  // @@protoc_insertion_point(class_scope:javacd.api.v1.ResolvedJavac)
  private static final com.facebook.buck.cd.model.java.ResolvedJavac DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.facebook.buck.cd.model.java.ResolvedJavac();
  }

  public static com.facebook.buck.cd.model.java.ResolvedJavac getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResolvedJavac>
      PARSER = new com.google.protobuf.AbstractParser<ResolvedJavac>() {
    @java.lang.Override
    public ResolvedJavac parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ResolvedJavac> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResolvedJavac> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.facebook.buck.cd.model.java.ResolvedJavac getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

