load("@prelude//toolchains:genrule.bzl", "system_genrule_toolchain")
load("@prelude//toolchains:no_toolchain.bzl", "no_toolchain")
load("@prelude//toolchains:python.bzl", "remote_python_toolchain", "system_python_bootstrap_toolchain")
load(":cpython_urls.json", cpython_urls = "value")

oncall("plf")

system_python_bootstrap_toolchain(
    name = "python_bootstrap",
    visibility = ["PUBLIC"],
)

remote_python_toolchain(
    name = "python",
    cpython_urls = cpython_urls,
    visibility = ["PUBLIC"],
)

no_toolchain(
    name = "cxx",
    visibility = ["PUBLIC"],
)

system_genrule_toolchain(
    name = "genrule",
    visibility = ["PUBLIC"],
)
