load("@fbcode//buck2:proto_defs.bzl", "rust_protobuf_library")

oncall("build_infra")

rust_protobuf_library(
    name = "buck2_action_metadata_proto",
    srcs = glob(["src/**/*.rs"]),
    build_script = "build.rs",
    protos = ["action_metadata.proto"],
    deps = [
        "fbsource//third-party/rust:tonic",
    ],
)
