load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("build_infra")

source_listing()

prelude = native

prelude.python_bootstrap_binary(
    name = "git_fetch",
    main = "git_fetch.py",
    visibility = ["PUBLIC"],
)
