load("@fbcode//buck2/tests:buck_e2e.bzl", "buck2_e2e_test")

oncall("build_infra")

buck2_e2e_test(
    name = "test_compatible_with_before_select",
    srcs = ["test_compatible_with_before_select.py"],
    data_dir = "test_compatible_with_before_select_data",
    env = {
        "OVR_CONFIG": "1",
        "PRELUDE": "$(location prelude//:prelude)",
    },
)

buck2_e2e_test(
    name = "test_configuration_rule_unbound",
    srcs = ["test_configuration_rule_unbound.py"],
)

buck2_e2e_test(
    name = "test_select_buckconfig",
    srcs = ["test_select_buckconfig.py"],
)

buck2_e2e_test(
    name = "test_select_refine",
    srcs = ["test_select_refine.py"],
)

buck2_e2e_test(
    name = "test_target_incompatible",
    srcs = ["test_target_incompatible.py"],
    data_dir = "test_target_incompatible_data",
)

buck2_e2e_test(
    name = "test_target_platforms_arg",
    srcs = ["test_target_platforms_arg.py"],
)

buck2_e2e_test(
    name = "test_platform_via_alias",
    srcs = ["test_platform_via_alias.py"],
)

buck2_e2e_test(
    name = "test_platform_wrong_label",
    srcs = ["test_platform_wrong_label.py"],
    data_dir = "test_platform_wrong_label_data",
)

buck2_e2e_test(
    name = "test_toolchain_overconfiguration",
    srcs = ["test_toolchain_overconfiguration.py"],
    data_dir = "test_toolchain_overconfiguration_data",
)
