load("@fbcode//buck2/tests:buck_e2e.bzl", "buck2_e2e_test")

oncall("build_infra")

buck2_e2e_test(
    name = "test_target_call_stacks",
    srcs = ["test_target_call_stacks.py"],
)

buck2_e2e_test(
    name = "test_cquery",
    srcs = ["test_cquery.py"],
    data_dir = "test_cquery_data",
    deps = [
        "//buck2/tests/e2e_util:golden",
    ],
)

buck2_e2e_test(
    name = "test_filter",
    srcs = ["test_filter.py"],
    data_dir = "test_filter_data",
)

buck2_e2e_test(
    name = "test_owner",
    srcs = ["test_owner.py"],
    data_dir = "test_owner_data",
)

buck2_e2e_test(
    name = "test_owner_isolated",
    srcs = ["test_owner_isolated.py"],
    data_dir = "test_owner_isolated_data",
)

buck2_e2e_test(
    name = "test_cquery_with_transition",
    srcs = ["test_cquery_with_transition.py"],
    data_dir = "test_cquery_with_transition_data",
)
