load("@fbcode//buck2/tests:buck_e2e.bzl", "buck2_e2e_test")

oncall("build_infra")

buck2_e2e_test(
    name = "test_output",
    srcs = ["test_output.py"],
    data_dir = "test_output_data",
    deps = [
        "//buck2/tests/e2e_util:utils",
    ],
)

buck2_e2e_test(
    name = "test_dynamic",
    srcs = ["test_dynamic.py"],
    data_dir = "test_dynamic_data",
    deps = [
        "//buck2/tests/e2e_util:golden",
        "//buck2/tests/e2e_util:utils",
    ],
)

buck2_e2e_test(
    name = "test_dynamic_new",
    srcs = ["test_dynamic_new.py"],
    data_dir = "test_dynamic_new_data",
    deps = [
        "//buck2/tests/e2e_util:utils",
    ],
)

buck2_e2e_test(
    name = "test_typecheck",
    srcs = ["test_typecheck.py"],
    data_dir = "test_typecheck_data",
)

buck2_e2e_test(
    name = "test_not_bxl",
    srcs = ["test_not_bxl.py"],
    data_dir = "test_not_bxl_data",
    deps = [
        "//buck2/tests/e2e_util:utils",
    ],
)

buck2_e2e_test(
    name = "test_target_universe",
    srcs = ["test_target_universe.py"],
    data_dir = "test_target_universe_data",
    deps = [
        "//buck2/tests/e2e_util:utils",
    ],
)

buck2_e2e_test(
    name = "test_configured_target",
    srcs = ["test_configured_target.py"],
    data_dir = "test_configured_target_data",
    deps = [
        "//buck2/tests/e2e_util:utils",
    ],
)

buck2_e2e_test(
    name = "test_type_names_and_symbols",
    srcs = ["test_type_names_and_symbols.py"],
    data_dir = "test_type_names_and_symbols_data",
    deps = [
        "//buck2/tests/e2e_util:utils",
    ],
)
