# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is dual-licensed under either the MIT license found in the
# LICENSE-MIT file in the root directory of this source tree or the Apache
# License, Version 2.0 found in the LICENSE-APACHE file in the root directory
# of this source tree. You may select, at your option, one of the
# above-listed licenses.

"""Simulated Triton kernel for testing stub generation.

This file represents code that would normally be generated by the Triton AOT
compiler. In real usage, this would be expensive to generate during IDE analysis.
"""


def kernel_func(x):
    """A simulated kernel function."""
    return x * 2


class KernelClass:
    """A simulated kernel class."""

    def method(self):
        return 42
