oncall("build_infra")

prelude = native

prelude.export_file(
    name = "some_file",
)

prelude.command_alias(
    name = "script",
    args = select({
        "DEFAULT": [
            "sh",
            "-c",
            "cat $1",
            "--",
            "$(location :some_file)",
        ],
        "ovr_config//os:windows": [
            "cmd.exe",
            "/c",
            "type",
            "$(location :some_file)",
        ],
    }),
    visibility = ["PUBLIC"],
)
