load("@fbcode//buck2/tests:buck_e2e.bzl", "buck2_e2e_test")

oncall("build_infra")

buck2_e2e_test(
    name = "test_docs",
    srcs = ["test_docs.py"],
    data_dir = "test_docs_data",
    deps = ["fbcode//buck2/tests/e2e_util:golden"],
)

buck2_e2e_test(
    name = "test_builtin_docs",
    srcs = ["test_builtin_docs.py"],
    data_dir = "test_builtin_docs_data",
    deps = ["fbcode//buck2/tests/e2e_util:golden"],
)
