load("@prelude//utils:source_listing.bzl", "source_listing")
load(":tools.bzl", "path_clang_tools")

oncall("build_infra")

source_listing()

path_clang_tools(
    name = "path_clang_tools",
    visibility = ["PUBLIC"],
)
