load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "dice_core",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    crate_root = "src/lib.rs",
    deps = [
        "fbsource//third-party/rust:arc-swap",
        "fbsource//third-party/rust:smallvec",
        "fbsource//third-party/rust:triomphe",
        "//buck2/allocative/allocative:allocative",
        "//buck2/gazebo/dupe:dupe",
        "//buck2/shed/lock_free_hashtable:lock_free_hashtable",
        "//buck2/shed/mini_vec:mini_vec",
    ],
)
