load("@fbcode_macros//build_defs:rust_library.bzl", "rust_library")
load("@fbsource//tools/build_defs:glob_defs.bzl", "glob")

oncall("build_infra")

rust_library(
    name = "buck2_external_cells",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "fbsource//third-party/rust:async-trait",
        "//buck2/app/buck2_common:buck2_common",
        "//buck2/app/buck2_external_cells_bundled:buck2_external_cells_bundled",
    ],
)
