# @oss-disable[end= ]: load("@fbcode_macros//build_defs:go_binary.bzl", "go_binary")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("golang")

source_listing()

prelude = native # @oss-enable
go_binary = prelude.go_binary # @oss-enable

go_binary(
    name = "gobuckify",
    srcs = ["main.go"],
    visibility = ["PUBLIC"],
    deps = [
        "prelude//go/tools/gobuckify/lib:gobuckifylib",
    ],
)
