load("@prelude//toolchains/android/tools:build_rules.bzl", "buck_kotlin_library")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

buck_kotlin_library(
    name = "common",
    srcs = glob(["**/*.kt"]),
    provided_deps = [
        "prelude//toolchains/android/third-party:kotlin-compiler",
    ],
    resources = glob(["resources/**"]),
    resources_root = "resources",
    tests = [
        "fbsource//fbandroid/javatests/com/facebook/kotlin/compilerplugins/kosabi/applicability:applicability-test",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "fbsource//fbandroid/java/com/facebook/kotlin/compilercompat:compilercompat",
        "fbsource//fbandroid/java/com/facebook/kotlin/compilerplugins/dataclassgenerate/annotation:dataclassgenerate-annotation",
    ],
)
