load("@fbcode//buck2/tests/prelude:py_assertion.bzl", "py_assertion")

oncall("golang")

prelude = native

prelude.go_binary(
    name = "bin",
    srcs = [
        "lib.c",
        "main.go",
    ],
    headers = ["lib.h"],
    header_namespace = "",
)

py_assertion(
    name = "check_output",
    script = """
import subprocess
import sys
assert subprocess.check_output([sys.argv[1]]).decode().strip() == "i = 1"
""",
    script_args = ["$(exe_target :bin)"],
)
