// @generated
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: install.proto

// Protobuf Java Version: 3.25.6
package com.facebook.buck.install.model;

/**
 * Protobuf type {@code install.InstallInfoRequest}
 */
@javax.annotation.Generated(value="protoc", comments="annotations:InstallInfoRequest.java.pb.meta")
public final class InstallInfoRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:install.InstallInfoRequest)
    InstallInfoRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InstallInfoRequest.newBuilder() to construct.
  private InstallInfoRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InstallInfoRequest() {
    installId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new InstallInfoRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.facebook.buck.install.model.InstallerProto.internal_static_install_InstallInfoRequest_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 2:
        return internalGetFiles();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.facebook.buck.install.model.InstallerProto.internal_static_install_InstallInfoRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.facebook.buck.install.model.InstallInfoRequest.class, com.facebook.buck.install.model.InstallInfoRequest.Builder.class);
  }

  public static final int INSTALL_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object installId_ = "";
  /**
   * <code>string install_id = 1;</code>
   * @return The installId.
   */
  @java.lang.Override
  public java.lang.String getInstallId() {
    java.lang.Object ref = installId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      installId_ = s;
      return s;
    }
  }
  /**
   * <code>string install_id = 1;</code>
   * @return The bytes for installId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInstallIdBytes() {
    java.lang.Object ref = installId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      installId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILES_FIELD_NUMBER = 2;
  private static final class FilesDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.facebook.buck.install.model.InstallerProto.internal_static_install_InstallInfoRequest_FilesEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> files_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetFiles() {
    if (files_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          FilesDefaultEntryHolder.defaultEntry);
    }
    return files_;
  }
  public int getFilesCount() {
    return internalGetFiles().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; files = 2;</code>
   */
  @java.lang.Override
  public boolean containsFiles(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetFiles().getMap().containsKey(key);
  }
  /**
   * Use {@link #getFilesMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getFiles() {
    return getFilesMap();
  }
  /**
   * <code>map&lt;string, string&gt; files = 2;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getFilesMap() {
    return internalGetFiles().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; files = 2;</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getFilesOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetFiles().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; files = 2;</code>
   */
  @java.lang.Override
  public java.lang.String getFilesOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetFiles().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(installId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, installId_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetFiles(),
        FilesDefaultEntryHolder.defaultEntry,
        2);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(installId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, installId_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetFiles().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      files__ = FilesDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, files__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.facebook.buck.install.model.InstallInfoRequest)) {
      return super.equals(obj);
    }
    com.facebook.buck.install.model.InstallInfoRequest other = (com.facebook.buck.install.model.InstallInfoRequest) obj;

    if (!getInstallId()
        .equals(other.getInstallId())) return false;
    if (!internalGetFiles().equals(
        other.internalGetFiles())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + INSTALL_ID_FIELD_NUMBER;
    hash = (53 * hash) + getInstallId().hashCode();
    if (!internalGetFiles().getMap().isEmpty()) {
      hash = (37 * hash) + FILES_FIELD_NUMBER;
      hash = (53 * hash) + internalGetFiles().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.facebook.buck.install.model.InstallInfoRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.facebook.buck.install.model.InstallInfoRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.facebook.buck.install.model.InstallInfoRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.facebook.buck.install.model.InstallInfoRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.facebook.buck.install.model.InstallInfoRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.facebook.buck.install.model.InstallInfoRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.facebook.buck.install.model.InstallInfoRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.facebook.buck.install.model.InstallInfoRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.facebook.buck.install.model.InstallInfoRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.facebook.buck.install.model.InstallInfoRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.facebook.buck.install.model.InstallInfoRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.facebook.buck.install.model.InstallInfoRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.facebook.buck.install.model.InstallInfoRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code install.InstallInfoRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:install.InstallInfoRequest)
      com.facebook.buck.install.model.InstallInfoRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.facebook.buck.install.model.InstallerProto.internal_static_install_InstallInfoRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 2:
          return internalGetFiles();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 2:
          return internalGetMutableFiles();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.facebook.buck.install.model.InstallerProto.internal_static_install_InstallInfoRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.facebook.buck.install.model.InstallInfoRequest.class, com.facebook.buck.install.model.InstallInfoRequest.Builder.class);
    }

    // Construct using com.facebook.buck.install.model.InstallInfoRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      installId_ = "";
      internalGetMutableFiles().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.facebook.buck.install.model.InstallerProto.internal_static_install_InstallInfoRequest_descriptor;
    }

    @java.lang.Override
    public com.facebook.buck.install.model.InstallInfoRequest getDefaultInstanceForType() {
      return com.facebook.buck.install.model.InstallInfoRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.facebook.buck.install.model.InstallInfoRequest build() {
      com.facebook.buck.install.model.InstallInfoRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.facebook.buck.install.model.InstallInfoRequest buildPartial() {
      com.facebook.buck.install.model.InstallInfoRequest result = new com.facebook.buck.install.model.InstallInfoRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.facebook.buck.install.model.InstallInfoRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.installId_ = installId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.files_ = internalGetFiles();
        result.files_.makeImmutable();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.facebook.buck.install.model.InstallInfoRequest) {
        return mergeFrom((com.facebook.buck.install.model.InstallInfoRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.facebook.buck.install.model.InstallInfoRequest other) {
      if (other == com.facebook.buck.install.model.InstallInfoRequest.getDefaultInstance()) return this;
      if (!other.getInstallId().isEmpty()) {
        installId_ = other.installId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      internalGetMutableFiles().mergeFrom(
          other.internalGetFiles());
      bitField0_ |= 0x00000002;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              installId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              files__ = input.readMessage(
                  FilesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableFiles().getMutableMap().put(
                  files__.getKey(), files__.getValue());
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object installId_ = "";
    /**
     * <code>string install_id = 1;</code>
     * @return The installId.
     */
    public java.lang.String getInstallId() {
      java.lang.Object ref = installId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        installId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string install_id = 1;</code>
     * @return The bytes for installId.
     */
    public com.google.protobuf.ByteString
        getInstallIdBytes() {
      java.lang.Object ref = installId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        installId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string install_id = 1;</code>
     * @param value The installId to set.
     * @return This builder for chaining.
     */
    public Builder setInstallId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      installId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string install_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearInstallId() {
      installId_ = getDefaultInstance().getInstallId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string install_id = 1;</code>
     * @param value The bytes for installId to set.
     * @return This builder for chaining.
     */
    public Builder setInstallIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      installId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> files_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetFiles() {
      if (files_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            FilesDefaultEntryHolder.defaultEntry);
      }
      return files_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableFiles() {
      if (files_ == null) {
        files_ = com.google.protobuf.MapField.newMapField(
            FilesDefaultEntryHolder.defaultEntry);
      }
      if (!files_.isMutable()) {
        files_ = files_.copy();
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return files_;
    }
    public int getFilesCount() {
      return internalGetFiles().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; files = 2;</code>
     */
    @java.lang.Override
    public boolean containsFiles(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetFiles().getMap().containsKey(key);
    }
    /**
     * Use {@link #getFilesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getFiles() {
      return getFilesMap();
    }
    /**
     * <code>map&lt;string, string&gt; files = 2;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getFilesMap() {
      return internalGetFiles().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; files = 2;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getFilesOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetFiles().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; files = 2;</code>
     */
    @java.lang.Override
    public java.lang.String getFilesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetFiles().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearFiles() {
      bitField0_ = (bitField0_ & ~0x00000002);
      internalGetMutableFiles().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; files = 2;</code>
     */
    public Builder removeFiles(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableFiles().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
        getMutableFiles() {
      bitField0_ |= 0x00000002;
      return internalGetMutableFiles().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; files = 2;</code>
     */
    public Builder putFiles(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableFiles().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; files = 2;</code>
     */
    public Builder putAllFiles(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableFiles().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000002;
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:install.InstallInfoRequest)
  }

  // @@protoc_insertion_point(class_scope:install.InstallInfoRequest)
  private static final com.facebook.buck.install.model.InstallInfoRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.facebook.buck.install.model.InstallInfoRequest();
  }

  public static com.facebook.buck.install.model.InstallInfoRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InstallInfoRequest>
      PARSER = new com.google.protobuf.AbstractParser<InstallInfoRequest>() {
    @java.lang.Override
    public InstallInfoRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<InstallInfoRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InstallInfoRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.facebook.buck.install.model.InstallInfoRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

