load("@fbcode//buck2/tests:buck_e2e.bzl", "buck2_e2e_test")

oncall("build_infra")

buck2_e2e_test(
    name = "test_trace_io",
    srcs = ["test_trace_io.py"],
    data_dir = "test_trace_io_data",
    env = {
        "PRELUDE": "$(location prelude//:prelude)",
    },
)
