load("@fbcode//buck2/tests:buck_e2e.bzl", "buck2_e2e_test")

oncall("build_infra")

buck2_e2e_test(
    name = "test_debug",
    srcs = ["test_debug.py"],
    data_dir = "test_debug_data",
)

buck2_e2e_test(
    name = "test_debug_chrome_trace",
    srcs = ["test_debug_chrome_trace.py"],
    data_dir = "test_debug_chrome_trace_data",
)

buck2_e2e_test(
    name = "test_debug_eval",
    srcs = ["test_debug_eval.py"],
    data_dir = "test_debug_eval_data",
)
