load("@prelude//toolchains/android/tools:build_rules.bzl", "buck_java_library")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

buck_java_library(
    name = "graph",
    srcs = glob(["*.java"]),
    tests = [
        "prelude//toolchains/android/test/com/facebook/buck/core/util/graph:graph",
    ],
    visibility = [
        "prelude//toolchains/android/src/com/facebook/buck/android/apkmodule:apkmodule",
        "prelude//toolchains/android/test/com/facebook/buck/android/apkmodule:apkmodule",
        "prelude//toolchains/android/test/com/facebook/buck/core/util/graph:graph",
    ],
    deps = [
        "prelude//toolchains/android/src/com/facebook/buck/core/exceptions:exceptions",
        "prelude//toolchains/android/src/com/facebook/buck/util:util",
        "prelude//toolchains/android/src/com/facebook/buck/util/concurrent:concurrent",
        "prelude//toolchains/android/src/com/facebook/buck/util/string:string",
        "prelude//toolchains/android/third-party:guava",
    ],
)
