load("@prelude//toolchains/android/tools:build_rules.bzl", "buck_java_binary", "buck_java_library")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

buck_java_library(
    name = "installer_apple_lib",
    srcs = glob(["*.java"]),
    deps = [
        "fbsource//xplat/buck2/platform/apple/installer/src/com/facebook/buck/apple/device:device",
        "fbsource//xplat/buck2/platform/apple/installer/src/com/facebook/buck/apple/plist:plist",
        "fbsource//xplat/buck2/platform/apple/installer/src/com/facebook/buck/apple/simulator:simulator",
        "prelude//toolchains/android/src/com/facebook/buck/android/device:device",
        "prelude//toolchains/android/src/com/facebook/buck/installer:installer_server",
        "prelude//toolchains/android/src/com/facebook/buck/installer/common:options_handler",
        "prelude//toolchains/android/src/com/facebook/buck/util:process_executor",
        "prelude//toolchains/android/src/com/facebook/buck/util:util",
        "prelude//toolchains/android/src/com/facebook/buck/util/json:json",
        "prelude//toolchains/android/third-party:infer-annotations",
        "prelude//toolchains/android/third-party:jsr305",
    ],
)

buck_java_binary(
    name = "apple_installer",
    main_class = "com.facebook.buck.installer.apple.AppleInstallerMain",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        ":installer_apple_lib",
    ],
)
