/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is dual-licensed under either the MIT license found in the
 * LICENSE-MIT file in the root directory of this source tree or the Apache
 * License, Version 2.0 found in the LICENSE-APACHE file in the root directory
 * of this source tree. You may select, at your option, one of the
 * above-listed licenses.
 */

package com.facebook.kotlin.compilerplugins.kosabi.stubsgen.generators

interface StubsGenerator {
  /**
   * Called multiple times in order to create new code. Note that instances should not rely on being
   * able to resolve [projectFiles] to descriptors. They should rather use the Psi APIs to parse
   * files.
   *
   * In the first round code generators are called with the files from the project. In following
   * rounds [projectFiles] represents files that were generated by code generators until no code
   * generator produces any files anymore.
   */
  fun generateStubs(context: GenerationContext)
}
