load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("build_infra")

source_listing()

prelude = native

prelude.python_library(
    name = "re_compatibility_utils",
    srcs = [
        "writable.py",
    ],
    visibility = ["PUBLIC"],
)

prelude.python_bootstrap_library(
    name = "bootstrap_re_compatibility_utils",
    srcs = [
        "writable.py",
    ],
    has_content_based_path = True,
    visibility = ["PUBLIC"],
)
