load("@prelude//toolchains/android/tools:build_rules.bzl", "buck_java_library")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

buck_java_library(
    name = "testutil",
    srcs = glob(
        ["*.java"],
        exclude = [
            "*Benchmark.java",
            "*Test.java",
        ],
    ),
    visibility = ["prelude//toolchains/android/test/..."],
    deps = [
        "prelude//toolchains/android/src/com/facebook/buck/core/build/execution/context:context",
        "prelude//toolchains/android/src/com/facebook/buck/util:util",
        "prelude//toolchains/android/src/com/facebook/buck/util/environment:environment",
        "prelude//toolchains/android/test/com/facebook/buck/testutil:testutil",
        "prelude//toolchains/android/test/com/facebook/buck/util:testutil",
        "prelude//toolchains/android/third-party:guava",
    ],
    exported_deps = [
        "prelude//toolchains/android/src/com/facebook/buck/step:step",
    ],
)
