# @lint-ignore BUCKLINT missing-oncall-call-severe This file is unowned and will be deleted without notice (due to not having an owner to contact).  Do not depend on this file
android_library(
    name = "model",
    srcs = glob(["*.kt"]),
    # We should make default language Kotlin
    language = "KOTLIN",
    visibility = ["PUBLIC"],
    deps = [
        "//app/libs/androidx/annotation/annotation:annotation",
    ],
)
