load("@prelude//toolchains/android/tools:build_rules.bzl", "buck_kotlin_test")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

STANDARD_TEST_SRCS = [
    "*Test.java",
    "*Test.kt",
]

buck_kotlin_test(
    name = "unit",
    srcs = glob(
        STANDARD_TEST_SRCS,
    ),
    deps = [
        "prelude//toolchains/android/src/com/facebook/buck/android:utils_api",
        "prelude//toolchains/android/src/com/facebook/buck/core/filesystems:filesystems",
        "prelude//toolchains/android/src/com/facebook/buck/installer:installer_server",
        "prelude//toolchains/android/src/com/facebook/buck/installer/android:installer_android_lib",
        "prelude//toolchains/android/third-party:junit",
    ],
)
