load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("apple_workflows")

source_listing()

python_binary(
    name = "signing_context_tree_postprocessor",
    main = "main.py",
    visibility = ["PUBLIC"],
)
