# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under both the MIT license found in the
# LICENSE-MIT file in the root directory of this source tree and the Apache
# License, Version 2.0 found in the LICENSE-APACHE file in the root directory
# of this source tree.

configuration_alias(
    name = "arm64",
    actual = "prelude//cpu:arm64",
    visibility = ["PUBLIC"],
)

configuration_alias(
    name = "riscv64",
    actual = "prelude//cpu:riscv64",
    visibility = ["PUBLIC"],
)

configuration_alias(
    name = "x86_64",
    actual = "prelude//cpu:x86_64",
    visibility = ["PUBLIC"],
)
