load("@fbcode_macros//build_defs:rust_library.bzl", "rust_library")

oncall("buck2")

rust_library(
    name = "buck2_offline_archive",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "fbsource//third-party/rust:serde",
    ],
)
