load("@prelude//toolchains/android/tools:build_rules.bzl", "buck_java_library")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

buck_java_library(
    name = "unarchive",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "prelude//toolchains/android/src/com/facebook/buck/io/file:file",
        "prelude//toolchains/android/src/com/facebook/buck/io/filesystem:filesystem",
        "prelude//toolchains/android/src/com/facebook/buck/io/filesystem/impl:utils",
        "prelude//toolchains/android/src/com/facebook/buck/util/environment:platform",
        "prelude//toolchains/android/third-party:commons-compress",
        "prelude//toolchains/android/third-party:guava",
        "prelude//toolchains/android/third-party:zstd-jni",
    ],
    exported_deps = [
        "prelude//toolchains/android/src/com/facebook/buck/util:util",
    ],
)
