load("@fbcode//buck2/tests:buck_e2e.bzl", "buck2_e2e_test")

oncall("build_infra")

buck2_e2e_test(
    name = "test_explain",
    srcs = ["test_explain.py"],
    data_dir = "test_explain_data",
    deps = [
        "//manifold/clients/python:manifold_client_deprecated",
    ],
)
