# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under both the MIT license found in the
# LICENSE-MIT file in the root directory of this source tree and the Apache
# License, Version 2.0 found in the LICENSE-APACHE file in the root directory
# of this source tree.

load("@prelude//configurations:constraint_alias.bzl", "constraint_with_aliases")

constraint_with_aliases(
    name = "runtime",
    aliases = {
        "android-host-test": "android-host-test",
        "android-instrumentation-test": "android-instrumentation-test",
        "android-unit-test": "android-unit-test",
        "anywhere-linux": "anywhere-linux",
        "fbcode": "fbcode",
    },
    default = "unspecified",
    values = [
        "android-host-test",
        "android-instrumentation-test",
        "android-unit-test",
        "anywhere-linux",
        "fbcode",
        "unspecified",
    ],
    visibility = ["PUBLIC"],
)
