load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "host_sharing",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:dashmap",
        "fbsource//third-party/rust:futures-intrusive",
        "//buck2/allocative/allocative:allocative",
        "//buck2/starlark-rust/starlark_map:starlark_map",
    ],
)
