native.rust_library(
    name = "member",
    srcs = ["lib.rs"],
    crate_root = "lib.rs",
)

native.rust_library(
    name = "root",
    srcs = ["lib.rs"],
    crate_root = "lib.rs",
    deps = [":member"],
)
