# @lint-ignore BUCKLINT missing-oncall-call-severe This file is unowned and will be deleted without notice (due to not having an owner to contact).  Do not depend on this file
load("//:test_utils.bzl", "assert_output")

python_binary(
    name = "main",
    main = "main/main.py",
    deps = ["//python/library:printlib"],
)

assert_output(
    name = "check_main",
    command = "$(exe_target :main)",
    output = "hello world from python toolchain",
)
