load("@fbcode//buck2:proto_defs.bzl", "rust_protobuf_library")

oncall("build_infra")

rust_protobuf_library(
    name = "buck2_downward_api_proto",
    srcs = glob(["src/**/*.rs"]),
    build_script = "build.rs",
    protos = ["downward_api.proto"],
    deps = [
        "fbsource//third-party/rust:tonic",
        "fbsource//third-party/rust:tracing",
        "//buck2/app/buck2_error:buck2_error",
    ],
)
