load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "starlark_derive",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    autocargo = {
        "cargo_toml_config": {
            "package": {
                "authors": ["Facebook"],
                "description": "Derive helpers for the starlark package.",
                "documentation": "https://docs.rs/starlark_derive",
                "license": "Apache-2.0",
                "repository": "https://github.com/facebook/starlark-rust",
                "version": "0.14.2",
            },
        },
    },
    proc_macro = True,
    visibility = [
        "//buck2/starlark-rust/...",
    ],
    deps = [
        "fbsource//third-party/rust:proc-macro2",
        "fbsource//third-party/rust:quote",
        "fbsource//third-party/rust:syn",
        "//buck2/gazebo/dupe:dupe",
    ],
)
