load("@fbcode_macros//build_defs:rust_library.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "buck2_query_derive",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    proc_macro = True,
    deps = [
        "fbsource//third-party/rust:itertools",
        "fbsource//third-party/rust:proc-macro2",
        "fbsource//third-party/rust:quote",
        "fbsource//third-party/rust:syn",
        "fbsource//third-party/rust:textwrap",
    ],
)
