# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is dual-licensed under either the MIT license found in the
# LICENSE-MIT file in the root directory of this source tree or the Apache
# License, Version 2.0 found in the LICENSE-APACHE file in the root directory
# of this source tree. You may select, at your option, one of the
# above-listed licenses.

buildscript.run = false

[['cfg(target_os = "linux")'.cxx_library]]
name = "linux"
srcs = ["c/linux.c"]
headers = ["c/*.h"]

[['cfg(target_os = "macos")'.cxx_library]]
name = "macos"
srcs = ["c/darwin.c"]
headers = ["c/*.h"]

['cfg(target_os = "freebsd")']
rustc_flags = ["-l", "pthread"]

[['cfg(target_os = "freebsd")'.cxx_library]]
name = "freebsd"
srcs = ["c/freebsd.c"]
headers = ["c/*.h"]

[['cfg(target_os = "windows")'.cxx_library]]
name = "windows"
srcs = ["c/windows.c"]
headers = ["c/*.h"]
