load("@prelude//toolchains/android/tools:build_rules.bzl", "buck_java_binary", "buck_kotlin_library")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

buck_kotlin_library(
    name = "stubsgen-standalone-lib",
    srcs = glob(
        [
            "**/*.kt",
        ],
    ),
    labels = ["codegen_rule"],
    provided_deps = [
        "prelude//toolchains/android/third-party:kotlin-compiler",
    ],
    resources = glob(["resources/**"]),
    resources_root = "resources",
    tests = [
        "fbsource//fbandroid/javatests/com/facebook/kotlin/compilerplugins/kosabi/integrationtest:integration-test",
        "fbsource//fbandroid/javatests/com/facebook/kotlin/compilerplugins/kosabi/stubsgen/standalone:standalone",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "prelude//toolchains/android/src/com/facebook/buck/jvm/kotlin/compilerplugins/kosabi/common:common",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/kotlin/compilerplugins/kosabi/common/stub:stub",
        "prelude//toolchains/android/third-party:kotlin-stdlib",
    ],
)

buck_java_binary(
    name = "standalone",
    visibility = ["PUBLIC"],
    deps = [":stubsgen-standalone-lib"],
)
