load("@prelude//utils:source_listing.bzl", "source_listing")
load(":tools.bzl", "find_msvc_tools")

oncall("build_infra")

source_listing()

python_bootstrap_binary(
    name = "vswhere",
    main = "vswhere.py",
    visibility = ["PUBLIC"],
)

python_bootstrap_binary(
    name = "run_msvc_tool",
    main = "run_msvc_tool.py",
    visibility = ["PUBLIC"],
)

find_msvc_tools(
    name = "msvc_tools",
    target_compatible_with = ["config//os:windows"],
    visibility = ["PUBLIC"],
)
