load("@prelude//configurations:constraint_alias.bzl", "constraint_with_aliases")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("build_infra")

source_listing()

# Used by open source projects to support `prelude//`

constraint_with_aliases(
    name = "abi",
    aliases = {
        "gnu": "gnu",
        "msvc": "msvc",
        "musl": "musl",
    },
    default = "unspecified",
    values = ["gnu", "msvc", "musl", "unspecified"],
    visibility = ["PUBLIC"],
)
