load("@fbcode//buck2/tests:bxl_test.bzl", "bxl_test")

oncall("build_infra")

[bxl_test(
    src = src,
) for src in glob(
    ["test_*.bxl"],
    exclude = ["test_sanitizer_buckconfig_backed_modifiers.bxl"],
)]

[bxl_test(
    name = "{}_test".format(sanitizer),
    src = "test_sanitizer_buckconfig_backed_modifiers.bxl",
    buck_args = [
        "--config",
        "fbcode.sanitizer={}".format(sanitizer),
    ],
) for sanitizer in ("address", "address-undefined", "thread", "hwaddress")]
