oncall("golang")

prelude = native

prelude.go_test(
    name = "test",
    srcs = [
        "coverage.go",
        "coverage_test.go",
    ],
    coverage_mode = "set",
    # @oss-disable[end= ]: env = {"GO_TEST2JSON_TOOL": "$(exe_target fbsource//third-party/go:test2json)"},
)
