load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("build_infra")

source_listing()

# Used by open source projects to support `prelude//`

config_setting(
    name = "fbcode",
    visibility = ["PUBLIC"],
)
