load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "buck2_hash",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "fbsource//third-party/rust:fxhash",
        "//buck2/gazebo/dupe:dupe",
    ],
)
