load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "buck2_proto_serde",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "fbsource//third-party/rust:prost-types",
        "fbsource//third-party/rust:serde",
    ],
)
