load("@prelude//configurations:constraint_alias.bzl", "constraint_with_aliases")

constraint_with_aliases(
    name = "singleton",
    aliases = {
        "singleton-schedule-at-exit-disabled": "schedule-at-exit-disabled",
    },
    default = "unspecified",
    values = [
        "schedule-at-exit-disabled",
        "unspecified",
    ],
    visibility = ["PUBLIC"],
)

constraint_with_aliases(
    name = "f14-fallback",
    aliases = {
        "f14-fallback-disabled": "disabled",
    },
    default = "unspecified",
    values = [
        "disabled",
        "unspecified",
    ],
    visibility = ["PUBLIC"],
)

constraint_with_aliases(
    name = "gflags",
    aliases = {
        "gflags-enabled": "enabled",
    },
    default = "unspecified",
    values = [
        "enabled",
        "unspecified",
    ],
    visibility = ["PUBLIC"],
)
