load("@prelude//configurations:constraint_alias.bzl", "constraint_with_aliases")

constraint_with_aliases(
    name = "singleton",
    aliases = {},
    default = "unspecified",
    values = [
        "schedule-at-exit-disabled",
        "unspecified",
    ],
    visibility = ["PUBLIC"],
)

constraint_with_aliases(
    name = "f14-fallback",
    aliases = {},
    default = "unspecified",
    values = [
        "disabled",
        "unspecified",
    ],
    visibility = ["PUBLIC"],
)

constraint_with_aliases(
    name = "gflags",
    aliases = {},
    default = "unspecified",
    values = [
        "enabled",
        "unspecified",
    ],
    visibility = ["PUBLIC"],
)
