load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("build_infra")

source_listing()

prelude = native

prelude.python_bootstrap_binary(
    name = "parse_julia_cmd",
    main = "parse_julia_cmd.py",
    visibility = ["PUBLIC"],
)

# Type checking target for Python tool scripts
prelude.python_library(
    name = "scripts-typing",
    srcs = [
        "parse_julia_cmd.py",
    ],
    typing = True,
)

prelude.python_test(
    name = "test_parse_julia_cmd",
    srcs = [
        "parse_julia_cmd.py",
        "tests/test_parse_julia_cmd.py",
    ],
    base_module = "",
)
