load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("build_infra")

source_listing()

prelude = native

prelude.python_bootstrap_binary(
    name = "parse_julia_cmd",
    main = "parse_julia_cmd.py",
    visibility = ["PUBLIC"],
)
