# @lint-ignore BUCKLINT missing-oncall-call-severe This file is unowned and will be deleted without notice (due to not having an owner to contact).  Do not depend on this file
_SUPPORTED = not host_info().os.is_windows

# buildifier: disable=no-effect
ocaml_binary(
    name = "calc",
    srcs = [
        "calc.ml",
        "lexer.mll",
        "parser.mly",
    ],
) if _SUPPORTED else None
