# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is dual-licensed under either the MIT license found in the
# LICENSE-MIT file in the root directory of this source tree or the Apache
# License, Version 2.0 found in the LICENSE-APACHE file in the root directory
# of this source tree. You may select, at your option, one of the
# above-listed licenses.

# TODO(cjhopman): This was generated by scripts/hacks/rules_shim_with_docs.py,
# but should be manually edited going forward. There may be some errors in
# the generated docs, and so those should be verified to be accurate and
# well-formatted (and then delete this TODO)

FrameworkVersion = ["net35", "net40", "net45", "net46"]

def _srcs_arg():
    return {
        "srcs": attrs.list(attrs.one_of(attrs.source(), attrs.tuple(attrs.source(), attrs.list(attrs.arg()))), default = [], doc = """
    The set of C, C++, Objective-C, Objective-C++, or assembly source files
     to be preprocessed, compiled, and assembled by this
     rule. We determine which stages to run on each input source based on its file extension. See the
     [GCC documentation](https://gcc.gnu.org/onlinedocs/gcc/Overall-Options.html) for more detail on how file extensions are interpreted. Each element can be either a string
     specifying a source file (e.g. `''`) or a tuple of
     a string specifying a source file and a list of compilation flags
     (e.g. `('', ['-Wall', '-Werror'])` ). In the latter case the specified flags will be used in addition to the rule's other
     flags when preprocessing and compiling that file (if applicable).
"""),
    }

def _resources_arg():
    return {
        "resources": attrs.dict(key = attrs.string(), value = attrs.source(), sorted = False, default = {}, doc = """
    Resources that should be embedded within the built DLL. The format
     is the name of the resource once mapped into the DLL as the key, and
     the value being the resource that should be merged. This allows
     non-unique keys to be identified quickly.
"""),
    }

def _framework_ver_arg():
    return {
        "framework_ver": attrs.enum(FrameworkVersion, doc = """
    The version of the .Net framework that this library targets. This is
     one of 'net35', 'net40', 'net45' and 'net46'.
"""),
    }

def _deps_arg():
    return {
        "deps": attrs.list(attrs.one_of(attrs.dep(), attrs.string()), default = [], doc = """
    The set of targets or system-provided assemblies to rely on. Any
     values that are targets must be either csharp\\_library or `prebuilt_dotnet_library`
     instances.
"""),
    }

def _compiler_flags_arg():
    return {
        "compiler_flags": attrs.list(attrs.string(), default = [], doc = """
     The set of additional compiler flags to pass to the compiler.
"""),
    }

def _default_host_platform_arg():
    return {"default_host_platform": attrs.option(attrs.configuration_label(), default = None)}

def _add_hermetic_arguments_arg():
    return {"add_hermetic_arguments": attrs.bool(default = True)}

dotnet_common = struct(
    srcs_arg = _srcs_arg,
    resources_arg = _resources_arg,
    framework_ver_arg = _framework_ver_arg,
    deps_arg = _deps_arg,
    compiler_flags_arg = _compiler_flags_arg,
    default_host_platform_arg = _default_host_platform_arg,
    add_hermetic_arguments_arg = _add_hermetic_arguments_arg,
)
