load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("build_infra")

source_listing()

python_bootstrap_binary(
    name = "unzip",
    main = "unzip.py",
    visibility = ["PUBLIC"],
)

# Type checking target for Python tool scripts
python_library(
    name = "scripts-typing",
    srcs = [
        "unzip.py",
    ],
    typing = True,
)
