load("@prelude//utils:source_listing.bzl", "source_listing")
load(":buildscript_platform.bzl", "transitions_for_constraint")

oncall("build_infra")

source_listing()

constraint(
    name = "buildscript_for_platform",
    default = "none",
    values = map(
        str,
        range(1000),
    )
    + ["none"],
    visibility = ["PUBLIC"],
)

transitions_for_constraint(
    name = "buildscript_platform_transition",
    constraint = ":buildscript_for_platform",
    visibility = ["PUBLIC"],
)
