oncall("golang")

prelude = native

prelude.go_test(
    name = "test",
    srcs = [
        "bar_test.go",
        "foo_test.go",
    ],
    # @oss-disable[end= ]: env = {"GO_TEST2JSON_TOOL": "$(exe_target fbsource//third-party/go:test2json)"},
)
