load("@prelude//toolchains/android/tools:build_rules.bzl", "buck_java_library")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

buck_java_library(
    name = "windowsfs",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = ["prelude//toolchains/android/third-party:jna"],
)
