load("@fbcode_macros//build_defs:rust_unittest.bzl", "rust_unittest")

oncall("build_infra")

rust_unittest(
    name = "buck2_node_tests",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    deps = [
        "//buck2/app/buck2_core:buck2_core",
        "//buck2/app/buck2_error:buck2_error",
        "//buck2/app/buck2_node:buck2_node",
        "//buck2/app/buck2_util:buck2_util",
        "//buck2/gazebo/dupe:dupe",
    ],
)
