load("@prelude//toolchains/android/tools:build_rules.bzl", "standard_java_test")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

standard_java_test(
    name = "testresultsoutput",
    vm_args = [
        # Needed for "fbsource//third-party/java/system-rules:system-rules"
        "--add-opens=java.base/java.util=ALL-UNNAMED",
    ],
    deps = [
        "prelude//toolchains/android/src/com/facebook/buck/testresultsoutput:testresultsoutput",
        "prelude//toolchains/android/third-party:junit",
        "prelude//toolchains/android/third-party:system-rules",
    ],
)
