load("@fbcode//buck2/tests:buck_e2e.bzl", "buck2_e2e_test")

oncall("build_infra")

buck2_e2e_test(
    name = "test_target_validation",
    srcs = ["test_target_validation.py"],
    data_dir = "test_target_validation_data",
)
