oncall("build_infra")

prelude = native

# Test to verify that we handle env
prelude.command_alias(
    name = "env_sh",
    args = [
        "sh",
        "-c",
        "echo $TEST_VAR",
    ],
    env = {"TEST_VAR": "foo"},
)

prelude.command_alias(
    name = "env_win",
    args = [
        "cmd.exe",
        "/c",
        "echo %TEST_VAR%",
    ],
    env = {"TEST_VAR": "foo bar"},
)

prelude.command_alias(
    name = "env",
    platform_exe = {
        "linux": ":env_sh",
        "macos": ":env_sh",
        "windows": ":env_win",
    },
)

prelude.genrule(
    name = "check_env",
    out = "out.txt",
    bash = '$(exe_target :env) | grep "foo" && touch "$OUT"',
    cmd_exe = '$(exe_target :env) | findstr "foo bar" && type nul> %OUT%',
)
