load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "pagable_derive",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    autocargo = {
        "cargo_toml_config": {
            "package": {
                "authors": ["Meta"],
                "description": "Implementation of derive(Pagable) for pagable crate",
                "version": "0.4.2",
            },
        },
    },
    crate_root = "src/lib.rs",
    proc_macro = True,
    deps = [
        "fbsource//third-party/rust:proc-macro2",
        "fbsource//third-party/rust:quote",
        "fbsource//third-party/rust:syn",
    ],
)
