load("@fbcode//buck2/tests:buck_e2e.bzl", "buck2_e2e_test")

oncall("build_infra")

buck2_e2e_test(
    name = "test_completion",
    srcs = ["test_completion.py"],
    data_dir = "test_completion_data",
)
