load("@prelude//rules.bzl", "python_binary")

# FIXME(marwhal): Get python_cextension example working again
# python_binary(
#     name = "cext",
#     deps = ["//cpp/python_cextension:cpprint"],
#     main = "cext/cext.py"
# )
