load("@prelude//toolchains:demo.bzl", "system_demo_toolchains")
load("@prelude//toolchains/conan:defs.bzl", "conan_init", "conan_profile", "system_conan_toolchain")

system_conan_toolchain(
    name = "conan",
    conan_path = "conan",
    visibility = ["PUBLIC"],
)

conan_profile(
    name = "conan-profile-linux",
    arch = "x86_64",
    os = "Linux" ,
    build_type = "Release",
    compiler = "gcc",
    compiler_version = "11.3",
    compiler_libcxx = "libstdc++",
)

conan_profile(
    name = "conan-profile-macos",
    arch = "x86_64",
    os = "Macos" ,
    build_type = "Release",
    compiler = "clang",
    compiler_version = "15",
    compiler_libcxx = "libc++",
)

conan_profile(
    name = "conan-profile-windows",
    arch = "x86_64",
    os = "Windows" ,
    build_type = "Release",
    compiler = "gcc",
    compiler_version = "11.3",
    compiler_libcxx = "libstdc++",
)

alias(
    name = "conan-profile",
    actual = select({
        "prelude//os:linux": ":conan-profile-linux",
        "prelude//os:macos": ":conan-profile-macos",
        "prelude//os:windows": ":conan-profile-windows",
    }),
)

conan_init(
    name = "conan-init",
    profile = ":conan-profile",
    visibility = ["PUBLIC"],
)

# All the default toolchains, suitable for a quick demo or early prototyping.
# Most real projects should copy/paste the implementation to configure them.
system_demo_toolchains()
