load("@prelude//:is_full_meta_repo.bzl", "is_full_meta_repo")
load("@prelude//toolchains/android/tools:build_rules.bzl", "buck_kotlin_library")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

buck_kotlin_library(
    name = "steps",
    srcs = glob(["*.java"]),
    tests = [
        "prelude//toolchains/android/test/com/facebook/buck/jvm/kotlin:kotlin",
    ],
    visibility = ["PUBLIC"],
    runtime_deps = [
        "fbsource//xplat/toolchains/android/sdk/src/com/facebook/buck/jvm/kotlin/abtesting:abtesting",
    ] if is_full_meta_repo() else [
        "prelude//toolchains/android/src/com/facebook/buck/jvm/kotlin/abtesting/noop:noop",
    ],
    deps = [
        "prelude//toolchains/android/src/com/facebook/buck/cd/resources/proto:javacd-model",
        "prelude//toolchains/android/src/com/facebook/buck/cd/resources/proto:kotlincd-model",
        "prelude//toolchains/android/src/com/facebook/buck/core/exceptions:exceptions",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/core:core",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/cd/serialization:serialization",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/cd/serialization/java:java",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/cd/serialization/kotlin:kotlin",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/java:steps",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/java:support",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/java/javax:javax",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/java/version:version",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/cd/command/kotlin:command",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/kotlin/buildtools:buildtools",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/kotlin/cd/analytics:analytics",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/kotlin/buildtools/snapshot:cp_snapshot_generator_lib",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/kotlin/kotlinc:kotlinc",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/kotlin/kotlinc/incremental:incremental",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/kotlin/compilerplugins/usedclasses:usedclasses",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/kotlin/ksp:ksp",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/kotlin/plugin:plugin-loader",
        "prelude//toolchains/android/src/com/facebook/buck/step/isolatedsteps/java:java",
        "prelude//toolchains/android/third-party:guava",
        "prelude//toolchains/android/third-party:jsr305",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/java/abi/source/api:api",
        # TODO(sergei): util/json is a source of [ObjectMapper] that is very heavy for class loading
        "prelude//toolchains/android/src/com/facebook/buck/util/json:json",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/cd/command/kotlin:language-version",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/kotlin/abtesting:abtesting",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/kotlin/abtesting/ksic:ksic",
        "prelude//toolchains/android/src/com/facebook/buck/core/filesystems:filesystems",
    ],
)
