load("@prelude//toolchains/android/tools:build_rules.bzl", "java_test")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

java_test(
    name = "strings",
    srcs = glob(["*.java"]),
    deps = [
        "prelude//toolchains/android/src/com/facebook/buck/android/resources/strings:strings",
        "prelude//toolchains/android/third-party:guava",
        "prelude//toolchains/android/third-party:junit",
    ],
)
