load("@fbcode_macros//build_defs:rust_library.bzl", "rust_library")
load("@fbsource//tools/build_defs:glob_defs.bzl", "glob")

oncall("buck2")

rust_library(
    name = "lock_free_vec",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
)
