load("@fbcode_macros//build_defs:rust_library.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "buck2_validation",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    deps = [
        "fbsource//third-party/rust:async-trait",
        "fbsource//third-party/rust:derivative",
        "fbsource//third-party/rust:derive_more",
        "fbsource//third-party/rust:either",
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:serde",
        "fbsource//third-party/rust:serde_json",
        "//buck2/allocative/allocative:allocative",
        "//buck2/app/buck2_artifact:buck2_artifact",
        "//buck2/app/buck2_build_api:buck2_build_api",
        "//buck2/app/buck2_core:buck2_core",
        "//buck2/app/buck2_error:buck2_error",
        "//buck2/app/buck2_execute:buck2_execute",
        "//buck2/dice/dice:dice",
        "//buck2/dice/dice_error:dice_error",
        "//buck2/gazebo/dupe:dupe",
    ],
)
