load("@fbcode_macros//build_defs:rust_library.bzl", "rust_library")
load("@fbsource//tools/build_defs:glob_defs.bzl", "glob")

oncall("build_infra")

rust_library(
    name = "buck2_validation",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:async-trait",
        "fbsource//third-party/rust:serde",
        "fbsource//third-party/rust:serde_json",
        "//buck2/allocative/allocative:allocative",
        "//buck2/app/buck2_build_api:buck2_build_api",
        "//buck2/app/buck2_core:buck2_core",
        "//buck2/app/buck2_error:buck2_error",
        "//buck2/app/buck2_node:buck2_node",
        "//buck2/dice/dice:dice",
        "//buck2/gazebo/dupe:dupe",
    ],
)
