load("@prelude//toolchains/android/tools:build_rules.bzl", "buck_java_binary", "buck_java_library")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

buck_java_library(
    name = "utils",
    srcs = glob(["*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "prelude//toolchains/android/src/com/facebook/buck/core/exceptions:exceptions",
        "prelude//toolchains/android/src/com/facebook/buck/core/filesystems:filesystems",
        "prelude//toolchains/android/src/com/facebook/buck/util/relativepathmap:relativepathmap",
        "prelude//toolchains/android/src/com/facebook/buck/util/zip/collect:collect",
        "prelude//toolchains/android/third-party:args4j",
        "prelude//toolchains/android/third-party:guava",
    ],
)

buck_java_binary(
    name = "zip_binary",
    main_class = "com.facebook.buck.features.zip.rules.utils.ZipMain",
    visibility = ["PUBLIC"],
    deps = [
        ":utils",
    ],
)
