load("@prelude//toolchains/android/tools:protobuf.bzl", "protobuf_src_gen")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

protobuf_src_gen(
    name = "worker-model",
    srcs = [
        "worker.proto",
    ],
    proto_path = [],
    deps = [
        "prelude//toolchains/android/third-party:jakarta.annotation-api",
    ],
    exported_deps = [
        "prelude//toolchains/android/third-party:protobuf",
        "prelude//toolchains/android/third-party:remote-apis",
    ],
)
