# @lint-ignore BUCKLINT missing-oncall-call-severe This file is unowned and will be deleted without notice (due to not having an owner to contact).  Do not depend on this file
load("@fbsource//tools/build_defs:cram_test.bzl", "cram_test")

cram_test(
    name = "integration",
    srcs = glob([
        "*.t",
        "fixtures/**/*",
    ]),
    env = {
        "DEP_FILE_PROCESSOR": "$(exe prelude//cxx/tools:dep_file_processor)",
    },
)
