load("@fbcode//buck2/tests:buck_e2e.bzl", "buck2_e2e_test")

oncall("build_infra")

buck2_e2e_test(
    name = "test_nested_invocations",
    srcs = ["test_nested_invocations.py"],
    data_dir = "test_nested_invocations_data",
)
