load("@prelude//toolchains/android/tools:build_rules.bzl", "buck_java_library")
load("@prelude//toolchains/android/tools/build_rules:file_alias.bzl", "file_alias")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

# Code shared between the agent and the host.
buck_java_library(
    name = "util",
    srcs = glob(["*.java"]),
    tests = [
        "prelude//toolchains/android/test/com/facebook/buck/android/agent/util:util",
    ],
    visibility = [
        "prelude//toolchains/android/src/com/facebook/buck/android:helpers",
        "prelude//toolchains/android/src/com/facebook/buck/android/agent:agent",
        "prelude//toolchains/android/test/com/facebook/buck/android/...",
        "prelude//toolchains/android/test/com/facebook/buck/android/agent/util:util",
    ],
    deps = [
        # Do not add other deps here.  The agent should remain very small.
    ],
)

file_alias(
    name = "util_src",
    source = "AgentUtil.java",
    visibility = [
        "prelude//toolchains/android/android/com/facebook/buck/android/agent/...",
    ],
)
