# @lint-ignore BUCKLINT missing-oncall-call-severe This file is unowned and will be deleted without notice (due to not having an owner to contact).  Do not depend on this file
load("//rust:rules.bzl", "rust_binary")

rust_binary(
    name = "main",
    file = "main.rs",
    toolchain = "toolchains//:rust",
)
