load("@fbcode//buck2/tests:buck_e2e.bzl", "buck2_e2e_test")
load("@prelude//cfg/modifier:name.bzl", "NAMED_CONSTRAINT_SETTINGS")
load(":constraint_setting_group.bzl", "constraint_setting_group")

oncall("buck2")

buck2_e2e_test(
    name = "test_cli_modifiers.py",
    srcs = ["test_cli_modifiers.py"],
)

buck2_e2e_test(
    name = "test_invoke_cfg_constructors.py",
    srcs = ["test_invoke_cfg_constructors.py"],
    data_dir = "test_invoke_cfg_constructors_data",
)

buck2_e2e_test(
    name = "test_set_cfg_modifiers.py",
    srcs = ["test_set_cfg_modifiers.py"],
    test_with_deployed_buck2 = True,
)

buck2_e2e_test(
    name = "test_invoke_cfg_constructors_bad_constraints.py",
    srcs = ["test_invoke_cfg_constructors_bad_constraints.py"],
    data_dir = "test_invoke_cfg_constructors_bad_constraints_data",
)

buck2_e2e_test(
    name = "test_cfg_modifiers.py",
    srcs = ["test_cfg_modifiers.py"],
    test_with_deployed_buck2 = True,
)

buck2_e2e_test(
    name = "test_cfg_constructors_inplace.py",
    srcs = ["test_cfg_constructors_inplace.py"],
    test_with_deployed_buck2 = True,
    test_with_reverted_buck2 = True,
)

constraint_setting_group(
    name = "test_named_constraint_settings",
    deps = NAMED_CONSTRAINT_SETTINGS.keys(),
)
