load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("build_infra")

source_listing()

prelude = native

prelude.python_bootstrap_binary(
    name = "script_template_processor",
    main = "script_template_processor.py",
    visibility = ["PUBLIC"],
)
