load("@fbcode_macros//build_defs:native_rules.bzl", "buck_filegroup")
# @oss-disable[end= ]: load("//buck2/tests/e2e_util/api:visibility.fb.bzl", "visibility")

oncall("build_infra")

visibility = ["PUBLIC"] # @oss-enable

buck_filegroup(
    name = "nano_prelude",
    srcs = glob(["*.bzl"]),
    visibility = visibility,
)
