load("@fbsource//tools/build_defs:rust_binary.bzl", "rust_binary")
load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")
load("@fbsource//tools/build_defs:rust_unittest.bzl", "rust_unittest")
load("@prelude//:rules.bzl", "rules")
load(":wrapper.bzl", "custom_rust_test")

oncall("rust_foundation")

rust_library(
    name = "a",
    srcs = ["lib_a.rs"],
    crate_root = "lib_a.rs",
    deps = ["//buck2/integrations/rust-project/tests/targets/bar:c"],
)

rust_library(
    name = "b",
    srcs = ["lib_b.rs"],
    crate_root = "lib_b.rs",
    deps = ["//buck2/integrations/rust-project/tests/targets/bar:d"],
)

rust_library(
    name = "e",
    srcs = ["lib_e.rs"],
    crate_root = "lib_e.rs",
    deps = [":f"],
)

rust_library(
    name = "f",
    srcs = ["lib_f.rs"],
    crate_root = "lib_f.rs",
)

rules["rust_library"](
    name = "unit_test_parent",
    srcs = ["lib_f.rs"],
    crate_root = "lib_f.rs",
    tests = [":arbitrary_unit_test"],
)

rules["rust_library"](
    name = "proc_macro_unit_test_parent",
    srcs = ["lib_f.rs"],
    crate_root = "lib_f.rs",
    proc_macro = True,
    tests = [":proc_macro_unit_test"],
    _workspaces = [":proc_macro_unit_test_parent"],
)

rust_library(
    name = "g_with_compatibility",
    srcs = ["lib_g.rs"],
    crate_root = "lib_g.rs",
    target_compatible_with = ["ovr_config//cpu/constraints:riscv64"],
)

rust_binary(
    name = "binary",
    srcs = ["main.rs"],
)

rust_unittest(
    name = "native_test",
    srcs = ["test.rs"],
    crate_root = "test.rs",
)

custom_rust_test(
    name = "wrapped_test",
    srcs = ["test.rs"],
    crate_root = "test.rs",
)

rules["rust_test"](
    name = "arbitrary_unit_test",
    srcs = ["lib_f.rs"],
    crate_root = "lib_f.rs",
    unit_test_of = ":unit_test_parent",
)

rules["rust_test"](
    name = "proc_macro_unit_test",
    srcs = ["lib_f.rs"],
    crate_root = "lib_f.rs",
    unit_test_of = ":proc_macro_unit_test_parent",
)
