load("@fbcode//buck2/tests:buck_e2e.bzl", "buck2_core_tests")

oncall("build_infra")

buck2_core_tests(
    target_extra_attrs = {
        "test_cancellation": {
            "skip_for_os": [
                "windows",
            ],
        },
        "test_hash_all_commands": {
            # These tests heavily depend on watchman, which is flakey on
            # non-Linux systems
            "skip_for_os": [
                "darwin",
                "windows",
            ],
        },
        "test_instruction_count": {
            "env": {
                "THREE_BILLION_INSTRUCTIONS_BIN": "$(location //buck2/shed/three_billion_instructions:three_billion_instructions-bin)",
            },
        },
        "test_outputs_ordering": {
            "env": {
                "RECLI": "$(location fbsource//xplat/remote_execution/dotslash:recli)",
            },
        },
    },
)
