load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "buck2_forkserver",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    compatible_with = [
        "ovr_config//os:linux",
        "ovr_config//os:macos",
    ],
    deps = [
        "fbsource//third-party/rust:arc-swap",
        "fbsource//third-party/rust:async-trait",
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:libc",
        "fbsource//third-party/rust:rand",
        "fbsource//third-party/rust:tokio",
        "fbsource//third-party/rust:tokio-stream",
        "fbsource//third-party/rust:tonic",
        "//buck2/allocative/allocative:allocative",
        "//buck2/app/buck2_common:buck2_common",
        "//buck2/app/buck2_core:buck2_core",
        "//buck2/app/buck2_data:buck2_data",
        "//buck2/app/buck2_error:buck2_error",
        "//buck2/app/buck2_execute_local:buck2_execute_local",
        "//buck2/app/buck2_forkserver_proto:buck2_forkserver_proto",
        "//buck2/app/buck2_fs:buck2_fs",
        "//buck2/app/buck2_grpc:buck2_grpc",
        "//buck2/app/buck2_resource_control:buck2_resource_control",
        "//buck2/app/buck2_util:buck2_util",
        "//buck2/gazebo/dupe:dupe",
    ] + select({
        "DEFAULT": [],
        "ovr_config//os:linux": [
            "fbsource//third-party/rust:nix",
            "//buck2/app/buck2_embedded_section:buck2_embedded_section",
        ],
    }),
)
