load("@prelude//toolchains/android/tools:build_rules.bzl", "buck_java_library")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

buck_java_library(
    name = "selectors",
    srcs = glob(["*.java"]),
    required_for_source_only_abi = True,
    # This target is pulled in by testrunner, which needs to compile against Java 8.
    # @oss-disable[end= ]: source = "8",
    # @oss-disable[end= ]: target = "8",
    source = "11", # @oss-enable
    target = "11", # @oss-enable
    tests = [
        "prelude//toolchains/android/test/com/facebook/buck/test/selectors:selectors",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [],  # This list is to remain empty. See src/com/facebook/buck/testrunner/BUCK.
)
