load("@fbcode//buck2:buck_rust_binary.bzl", "buck_rust_binary")

oncall("build_infra")

buck_rust_binary(
    name = "starlark_bin",
    srcs = glob(
        ["bin/**/*.rs"],
    ),
    crate_root = "bin/main.rs",
    env = {"CARGO_PKG_VERSION": "0.0"},  # So our OSS builds can support --version
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:argfile",
        "fbsource//third-party/rust:clap",
        "fbsource//third-party/rust:debugserver-types",
        "fbsource//third-party/rust:either",
        "fbsource//third-party/rust:globset",
        "fbsource//third-party/rust:itertools",
        "fbsource//third-party/rust:lsp-types",
        "fbsource//third-party/rust:serde",
        "fbsource//third-party/rust:serde_json",
        "fbsource//third-party/rust:thiserror",
        "fbsource//third-party/rust:walkdir",
        "//buck2/gazebo/dupe:dupe",
        "//buck2/starlark-rust/starlark:starlark",
        "//buck2/starlark-rust/starlark_lsp:starlark_lsp",
    ],
)
