prelude = native

prelude.python_binary(
    name = "dry_codesign_tool",
    main = "dry_codesign_tool.py",
    visibility = ["PUBLIC"],
)

prelude.python_bootstrap_binary(
    name = "make_modulemap",
    main = "make_modulemap.py",
    visibility = ["PUBLIC"],
)

prelude.export_file(
    name = "swift_exec.sh",
    src = "swift_exec.sh",
)

prelude.command_alias(
    name = "swift_exec",
    exe = ":swift_exec.sh",
    visibility = ["PUBLIC"],
)

prelude.python_bootstrap_binary(
    name = "make_vfsoverlay",
    main = "make_vfsoverlay.py",
    visibility = ["PUBLIC"],
)

prelude.python_binary(
    name = "split_arch_combine_dsym_bundles_tool",
    main = "split_arch_combine_dsym_bundles_tool.py",
    visibility = ["PUBLIC"],
)

prelude.python_bootstrap_binary(
    name = "swift_objc_header_postprocess",
    main = "swift_objc_header_postprocess.py",
    visibility = ["PUBLIC"],
)

prelude.python_bootstrap_binary(
    name = "make_swift_comp_db",
    main = "make_swift_comp_db.py",
    visibility = ["PUBLIC"],
)
