load("//:test_utils.bzl", "assert_output")

oncall("build_infra")

cxx_binary(
    name = "main",
    srcs = ["main.cpp"],
    link_style = "static",
    deps = ["//cpp/library:print"],
)

assert_output(
    name = "check_main",
    command = "$(exe_target :main)",
    output = "hello world from cpp toolchain",
)
