# @lint-ignore BUCKLINT missing-oncall-call-severe This file is unowned and will be deleted without notice (due to not having an owner to contact).  Do not depend on this file
load("//:test_utils.bzl", "assert_output")

cxx_binary(
    name = "main",
    srcs = ["main.cpp"],
    link_style = "static",
    deps = ["//cpp/library:print"],
)

assert_output(
    name = "check_main",
    command = "$(exe_target :main)",
    output = "hello world from cpp toolchain",
)
