# @lint-ignore BUCKLINT missing-oncall-call-severe This file is unowned and will be deleted without notice (due to not having an owner to contact).  Do not depend on this file
load("@fbcode_macros//build_defs:rust_library.bzl", "rust_library")

rust_library(
    name = "c",
    srcs = ["lib.rs"],
    visibility = ["PUBLIC"],
    deps = ["//buck2/integrations/rust-project/tests/targets/foo:e"],
)

rust_library(
    name = "d",
    srcs = ["lib.rs"],
    visibility = ["PUBLIC"],
    deps = ["//buck2/integrations/rust-project/tests/targets/foo:e"],
)
