load("@fbcode//buck2/tests:buck_e2e.bzl", "buck2_e2e_test")

oncall("build_infra")

buck2_e2e_test(
    name = "test_access_attr.py",
    srcs = ["test_access_attr.py"],
)

buck2_e2e_test(
    name = "test_attr",
    srcs = ["test_attr.py"],
)

buck2_e2e_test(
    name = "test_attr_split",
    srcs = ["test_attr_split.py"],
)

buck2_e2e_test(
    name = "test_rule",
    srcs = ["test_rule.py"],
    data_dir = "test_rule_data",
)

buck2_e2e_test(
    name = "test_rule_infinite_bug",
    srcs = ["test_rule_infinite_bug.py"],
)

buck2_e2e_test(
    name = "test_select_in_transition_attr",
    srcs = ["test_select_in_transition_attr.py"],
    data_dir = "test_select_in_transition_attr_data",
)
