load("@fbcode_macros//build_defs:rust_library.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "display_container",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    deps = [
        "fbsource//third-party/rust:either",
        "fbsource//third-party/rust:indenter",
    ],
)
