load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "display_container",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    autocargo = {
        "cargo_toml_config": {
            "package": {
                "authors": ["Facebook"],
                "categories": ["rust-patterns"],
                "description": "Utilities to implement Display",
                "documentation": "https://docs.rs/display_container",
                "version": "0.9.0",
            },
        },
    },
    deps = [
        "fbsource//third-party/rust:either",
        "fbsource//third-party/rust:indenter",
    ],
)
