load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

prelude = native

prelude.python_test(
    name = "test_sort_pre_dexed_files",
    srcs = ["test_sort_pre_dexed_files.py"],
    deps = [
        "prelude//android/tools:sort_pre_dexed_files_lib",
    ],
)
