load("@fbcode//buck2/tests:buck_e2e.bzl", "buck2_core_tests")

oncall("build_infra")

buck2_core_tests(
    target_extra_attrs = {
        "test_agent_host_guard": {
            "compatible_with": [
                "ovr_config//os:linux",
                "ovr_config//os:macos",
            ],
        },
    },
)
