load("@fbcode//buck2/tests:buck_e2e.bzl", "buck2_e2e_test")

oncall("build_infra")

buck2_e2e_test(
    name = "test_targets",
    srcs = ["test_targets.py"],
)

buck2_e2e_test(
    name = "test_targets_inplace",
    srcs = ["test_targets_inplace.py"],
)
