load("@fbcode//buck2/tests:buck_e2e.bzl", "buck2_e2e_test")

oncall("build_infra")

buck2_e2e_test(
    name = "test_invocation_record",
    srcs = ["test_invocation_record.py"],
    data_dir = "test_invocation_record_data",
    serialize_test_cases = False,
    deps = [
        "//buck2/tests/e2e_util:utils",
    ],
)
