load("@prelude//toolchains/android/tools:build_rules.bzl", "standard_java_test")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

standard_java_test(
    name = "unarchive",
    deps = [
        "prelude//toolchains/android/src/com/facebook/buck/io/file:file",
        "prelude//toolchains/android/src/com/facebook/buck/util/environment:platform",
        "prelude//toolchains/android/src/com/facebook/buck/util/unarchive:unarchive",
        "prelude//toolchains/android/src/com/facebook/buck/util/zip:zip",
        "prelude//toolchains/android/test/com/facebook/buck/testutil:testutil",
        "prelude//toolchains/android/test/com/facebook/buck/testutil/integration:util",
        "prelude//toolchains/android/third-party:commons-compress",
        "prelude//toolchains/android/third-party:guava",
        "prelude//toolchains/android/third-party:junit",
    ],
)
