load("@fbcode_macros//build_defs:rust_library.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "buck2_health_check",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    test_deps = ["fbsource//third-party/rust:tokio"],
    deps = [
        "fbsource//third-party/rust:async-trait",
        "//buck2/app/buck2_data:buck2_data",
        "//buck2/app/buck2_error:buck2_error",
        "//buck2/app/buck2_util:buck2_util",
    ],
)
