load("@prelude//android:min_sdk_version.bzl", "get_min_sdk_version_constraint_value_name", "get_min_sdk_version_range")
load("@prelude//configurations:constraint_alias.bzl", "constraint_with_aliases")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("build_infra")

source_listing()

prelude = native  # Avoid warnings and auto-formatters

constraint_with_aliases(
    name = "maybe_build_only_native_code",
    aliases = {
        "build_only_native_code": "build_only_native_code",
    },
    default = "unspecified",
    values = [
        "build_only_native_code",
        "unspecified",
    ],
    visibility = ["PUBLIC"],
)

constraint_with_aliases(
    name = "maybe_merge_native_libraries",
    aliases = {
        "merge_native_libraries": "merge_native_libraries",
    },
    default = "unspecified",
    values = [
        "merge_native_libraries",
        "unspecified",
    ],
    visibility = ["PUBLIC"],
)

prelude.filegroup(
    name = "files",
    srcs = glob(
        ["**"],
    ),
    visibility = ["PUBLIC"],
)

prelude.constraint_setting(
    name = "min_sdk_version",
    visibility = ["PUBLIC"],
)

[
    prelude.constraint_value(
        name = get_min_sdk_version_constraint_value_name(min_sdk),
        constraint_setting = ":min_sdk_version",
    )
    for min_sdk in get_min_sdk_version_range()
]
