load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "gazebo_derive",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    autocargo = {
        "cargo_toml_config": {
            "package": {
                "authors": ["Facebook"],
                "categories": ["rust-patterns"],
                "description": "Derive macros for the Gazebo library",
                "documentation": "https://docs.rs/gazebo_derive",
                "version": "0.8.0",
            },
        },
    },
    proc_macro = True,
    deps = [
        "fbsource//third-party/rust:proc-macro2",
        "fbsource//third-party/rust:quote",
        "fbsource//third-party/rust:syn",
    ],
)
