load("@fbcode_macros//build_defs:rust_binary.bzl", "rust_binary")
load("@fbsource//tools/build_defs:glob_defs.bzl", "glob")

oncall("buck2")

rust_binary(
    name = "three_billion_instructions",
    srcs = glob(
        ["src/**/*.rs"],
    ),
)
