load("@fbcode//buck2/tests:buck_e2e.bzl", "buck2_e2e_test")
load("@fbcode_macros//build_defs:native_rules.bzl", "buck_filegroup")

oncall("build_infra")

buck2_e2e_test(
    name = "test_console",
    srcs = ["test_console.py"],
    env = {
        "FIXTURES": "$(location :fixtures)",
    },
)

buck_filegroup(
    name = "fixtures",
    srcs = glob(
        ["fixtures/**"],
    ),
)
