load("@fbcode_macros//build_defs:export_files.bzl", "export_file")
load("@fbcode_macros//build_defs:python_library.bzl", "python_library")
load("@fbcode_macros//build_defs:python_unittest.bzl", "python_unittest")
load("@fbsource//tools/build_defs/testinfra:network_access_utils.bzl", "network_access_utils")

oncall("build_infra")

python_library(
    name = "assert_occurrences",
    srcs = ["helper/assert_occurrences.py"],
)

python_library(
    name = "utils",
    srcs = ["helper/utils.py"],
    deps = [
        "fbsource//third-party/pypi/psutil:psutil",
        "//buck2/tests/e2e_util/api:api",
    ],
)

python_library(
    name = "golden",
    srcs = ["helper/golden.py"],
)

python_library(
    name = "http_server",
    srcs = ["helper/http_server.py"],
    deps = [
        "fbsource//third-party/pypi/aiohttp:aiohttp",
    ],
)

python_library(
    name = "utilities",
    srcs = [
        "asserts.py",
        "buck_workspace.py",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "fbsource//third-party/pypi/decorator:decorator",
        "fbsource//third-party/pypi/pytest:pytest",
        "//buck2/tests/e2e_util/api:api",
    ],
)

export_file(
    name = "conftest.py",
    src = "conftest.py",
    visibility = ["PUBLIC"],
)

export_file(name = "test_bxl_template.py")

export_file(name = "test_bxl_check_dependencies_template.py")

# Type checking target for Python scripts
python_library(
    name = "scripts-typing",
    srcs = [
        "conftest.py",
        "test_bxl_check_dependencies_template.py",
        "test_bxl_template.py",
    ],
    typing = True,
    deps = [
        "fbsource//third-party/pypi/pytest:pytest",
        "//buck2/tests/e2e_util:utilities",
        "//buck2/tests/e2e_util/api:api",
    ],
)

python_unittest(
    name = "golden_test",
    srcs = ["tests/test_golden.py"],
    network_access = network_access_utils.none(),
    deps = [":golden"],
)

python_unittest(
    name = "utils_test",
    srcs = ["tests/test_utils.py"],
    network_access = network_access_utils.none(),
    deps = [":utils"],
)
