load("@fbcode//buck2:proto_defs.bzl", "rust_protobuf_library")

oncall("build_infra")

rust_protobuf_library(
    name = "re_grpc_proto",
    srcs = glob(["src/**/*.rs"]),
    build_script = "build.rs",
    protos = glob(["proto/**/*.proto"]),
    deps = [
        "fbsource//third-party/rust:prost-types",
        "fbsource//third-party/rust:serde",
        "fbsource//third-party/rust:tonic",
        "//buck2/app/buck2_data:buck2_data",
    ],
)
