/*
 * Copyright 2018 The Starlark in Rust Authors.
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//! Function types, including native functions and `object.member` functions.

use allocative::Allocative;
use derivative::Derivative;
use derive_more::Display;
use dupe::Dupe;
use starlark_derive::NoSerialize;
use starlark_derive::starlark_value;

use crate as starlark;
use crate::any::ProvidesStaticType;
use crate::docs::DocItem;
use crate::docs::DocMember;
use crate::docs::DocProperty;
use crate::docs::DocString;
use crate::docs::DocStringKind;
use crate::eval::Arguments;
use crate::eval::Evaluator;
use crate::eval::ParametersSpec;
use crate::private::Private;
use crate::starlark_complex_value_branded;
use crate::typing::Ty;
use crate::typing::TyBasic;
use crate::typing::arc_ty::ArcTy;
use crate::typing::tuple::TyTuple;
use crate::values::AllocFrozenValue;
use crate::values::FreezeBranded;
use crate::values::FreezeResult;
use crate::values::Freezer;
use crate::values::FrozenHeap;
use crate::values::Heap;
use crate::values::StarlarkValue;
use crate::values::Trace;
use crate::values::Value;
use crate::values::ValueError;
use crate::values::ValueLike;
use crate::values::ValueTyped;
use crate::values::types::ellipsis::Ellipsis;
use crate::values::typing::type_compiled::compiled::TypeCompiled;

#[derive(Debug, thiserror::Error)]
enum FunctionError {
    #[error("`tuple[]` is implemented only for `tuple[T, ...]`")]
    TupleOnlyEllipsis,
}

/// Return value of `type(any function)`.
pub const FUNCTION_TYPE: &str = "function";

#[derive(Debug, Allocative, Clone, Copy, Dupe, pagable::Pagable)]
#[doc(hidden)]
pub enum SpecialBuiltinFunction {
    List,
    Dict,
    Tuple,
    Set,
}

/// Type alias for functions generated by macro
#[doc(hidden)]
pub type NativeFuncFn = for<'v> fn(
    eval: &mut Evaluator<'v, '_, '_>,
    sig: &ParametersSpec<Value<'v>>,
    args: &Arguments<'v, '_>,
) -> crate::Result<Value<'v>>;

/// Storage for a `NativeFuncFn` and the parameters spec needed to call it
#[derive(Debug, ProvidesStaticType, Allocative, crate::StarlarkPagable)]
pub(crate) struct NativeFunc<'v>(
    #[allocative(skip)] // Not general enough
    #[starlark_pagable(skip = "{ |_a, _b, _c| { unimplemented!() } }")]
    pub(crate) NativeFuncFn,
    pub(crate) ParametersSpec<Value<'v>>,
);

impl<'v> NativeFunc<'v> {
    #[inline]
    pub(crate) fn invoke(
        &self,
        eval: &mut Evaluator<'v, '_, '_>,
        args: &Arguments<'v, '_>,
    ) -> crate::Result<Value<'v>> {
        (self.0)(eval, &self.1, args)
    }
}

/// Starlark representation of native (Rust) functions.
///
/// Almost always created with [`#[starlark_module]`](macro@crate::starlark_module). The
/// signature's default values are at the brand of the heap the function is allocated in.
#[derive(
    Derivative,
    ProvidesStaticType,
    Display,
    NoSerialize,
    Allocative,
    crate::StarlarkPagable
)]
#[derivative(Debug)]
#[display("{}", name)]
pub(crate) struct NativeFunction<'v> {
    #[derivative(Debug = "ignore")]
    pub(crate) function: NativeFunc<'v>,
    pub(crate) name: String,
    /// `.type` attribute and a type when this function is used in type expression.
    #[starlark_pagable(pagable)]
    pub(crate) as_type: Option<Ty>,
    #[starlark_pagable(pagable)]
    pub(crate) ty: Ty,
    /// Safe to evaluate speculatively.
    pub(crate) speculative_exec_safe: bool,
    #[derivative(Debug = "ignore")]
    #[starlark_pagable(pagable)]
    pub(crate) docs: DocItem,
    #[starlark_pagable(pagable)]
    pub(crate) special_builtin_function: Option<SpecialBuiltinFunction>,
}

impl<'fv> AllocFrozenValue<'fv> for NativeFunction<'fv> {
    fn alloc_frozen_value(self, heap: FrozenHeap<'fv>) -> Value<'fv> {
        heap.alloc_simple_typed(self).to_value()
    }
}

/// Define the function type
#[starlark_value(type = FUNCTION_TYPE, frozen_vtable)]
impl<'v> StarlarkValue<'v> for NativeFunction<'v> {
    fn invoke(
        &self,
        _me: Value<'v>,
        args: &Arguments<'v, '_>,
        eval: &mut Evaluator<'v, '_, '_>,
    ) -> crate::Result<Value<'v>> {
        self.function.invoke(eval, args)
    }

    fn get_attr(&self, attribute: &str, heap: Heap<'v>) -> Option<Value<'v>> {
        if let Some(s) = self.as_type.as_ref().and_then(|t| t.as_name()) {
            if attribute == "type" {
                return Some(heap.alloc(s));
            }
        }
        None
    }

    fn eval_type(&self) -> Option<Ty> {
        self.as_type.clone()
    }

    fn has_attr(&self, _attribute: &str, _heap: Heap<'v>) -> bool {
        // TODO(nga): implement properly.
        false
    }

    fn dir_attr(&self) -> Vec<String> {
        if self.as_type.is_some() {
            vec!["type".to_owned()]
        } else {
            Vec::new()
        }
    }

    fn documentation(&self) -> DocItem {
        self.docs.clone()
    }

    fn typechecker_ty(&self) -> Option<Ty> {
        Some(self.ty.dupe())
    }

    fn at(&self, index: Value<'v>, heap: Heap<'v>) -> crate::Result<Value<'v>> {
        match &self.special_builtin_function {
            Some(SpecialBuiltinFunction::List) => {
                let index = TypeCompiled::new(index, heap)?;
                Ok(TypeCompiled::type_list_of(index, heap).to_inner())
            }
            Some(SpecialBuiltinFunction::Set) => {
                let index = TypeCompiled::new(index, heap)?;
                Ok(TypeCompiled::type_set_of(index, heap).to_inner())
            }
            _ => ValueError::unsupported(self, "[]"),
        }
    }

    fn at2(
        &self,
        index0: Value<'v>,
        index1: Value<'v>,
        heap: Heap<'v>,
        _private: Private,
    ) -> crate::Result<Value<'v>> {
        match &self.special_builtin_function {
            Some(SpecialBuiltinFunction::Dict) => {
                let index0 = TypeCompiled::new(index0, heap)?;
                let index1 = TypeCompiled::new(index1, heap)?;
                Ok(TypeCompiled::type_dict_of(index0, index1, heap).to_inner())
            }
            Some(SpecialBuiltinFunction::Tuple) => {
                let item = TypeCompiled::new(index0, heap)?;
                if index1.downcast_ref::<Ellipsis>().is_some() {
                    Ok(TypeCompiled::from_ty(
                        &Ty::basic(TyBasic::Tuple(TyTuple::Of(ArcTy::new(
                            item.as_ty().clone(),
                        )))),
                        heap,
                    )
                    .to_inner())
                } else {
                    Err(crate::Error::new_other(FunctionError::TupleOnlyEllipsis))
                }
            }
            _ => ValueError::unsupported(self, "[,]"),
        }
    }
}

/// Type alias for functions generated by macro
#[doc(hidden)]
pub type NativeMethFn = for<'v> fn(
    eval: &mut Evaluator<'v, '_, '_>,
    this: Value<'v>,
    sig: &ParametersSpec<Value<'v>>,
    args: &Arguments<'v, '_>,
) -> crate::Result<Value<'v>>;

/// Storage for a `NativeMethFn` and the parameters spec needed to call it
#[derive(Debug, ProvidesStaticType, Allocative, crate::StarlarkPagable)]
pub(crate) struct NativeMeth<'v>(
    #[allocative(skip)] // Not general enough
    #[starlark_pagable(skip = "{ |_a, _b, _c, _d| { unimplemented!() } }")]
    pub(crate) NativeMethFn,
    pub(crate) ParametersSpec<Value<'v>>,
);

impl<'v> NativeMeth<'v> {
    #[inline]
    pub(crate) fn invoke(
        &self,
        eval: &mut Evaluator<'v, '_, '_>,
        this: Value<'v>,
        args: &Arguments<'v, '_>,
    ) -> crate::Result<Value<'v>> {
        (self.0)(eval, this, &self.1, args)
    }
}

/// A method of a type, before it is bound to an instance. Lives in a
/// [`Methods`](crate::environment::Methods) table.
#[derive(
    Derivative,
    Display,
    NoSerialize,
    ProvidesStaticType,
    Allocative,
    crate::StarlarkPagable
)]
#[derivative(Debug)]
#[display("{}", name)]
pub(crate) struct NativeMethod<'v> {
    #[derivative(Debug = "ignore")]
    pub(crate) function: NativeMeth<'v>,
    pub(crate) name: String,
    #[starlark_pagable(pagable)]
    pub(crate) ty: Ty,
    /// Safe to evaluate speculatively.
    pub(crate) speculative_exec_safe: bool,
    #[derivative(Debug = "ignore")]
    #[starlark_pagable(pagable)]
    pub(crate) docs: DocItem,
}

impl<'fv> AllocFrozenValue<'fv> for NativeMethod<'fv> {
    fn alloc_frozen_value(self, heap: FrozenHeap<'fv>) -> Value<'fv> {
        heap.alloc_simple_typed(self).to_value()
    }
}

// Only ever allocated in the frozen heaps of methods tables, so never actually frozen; the impl
// is what lets a `ValueTyped` of it be a field of a freezable type.
impl<'v> FreezeBranded<'v> for NativeMethod<'v> {
    type Frozen<'fv> = NativeMethod<'fv>;

    fn freeze<'fv>(self, freezer: &Freezer<'v, 'fv>) -> FreezeResult<Self::Frozen<'fv>> {
        Ok(NativeMethod {
            function: NativeMeth(self.function.0, self.function.1.freeze(freezer)?),
            name: self.name,
            ty: self.ty,
            speculative_exec_safe: self.speculative_exec_safe,
            docs: self.docs,
        })
    }
}

#[starlark_value(type = "native_method", frozen_vtable)]
impl<'v> StarlarkValue<'v> for NativeMethod<'v> {
    fn documentation(&self) -> DocItem {
        self.docs.clone()
    }

    fn typechecker_ty(&self) -> Option<Ty> {
        Some(self.ty.clone())
    }
}

/// Used by the `#[starlark(attribute)]` tag of [`#[starlark_module]`](macro@starlark_module)
/// to define a function that pretends to be an attribute.
#[derive(
    Derivative,
    Display,
    NoSerialize,
    ProvidesStaticType,
    Allocative,
    crate::StarlarkPagable
)]
#[display("Attribute")]
#[derivative(Debug)]
pub(crate) struct NativeAttribute<'v> {
    /// Safe to evaluate speculatively.
    pub(crate) speculative_exec_safe: bool,
    pub(crate) docstring: Option<String>,
    #[starlark_pagable(pagable)]
    pub(crate) typ: Ty,
    /// Essentially a `&dyn Fn(Value, Heap) -> Result<Value>`, but expanded out by hand, and
    /// with the `Self` hardcoded to always be `Option<Value>`
    ///
    /// We don't use a enum over whether the callable below requires a `data` argument as that
    /// would introduce an additional branch when calling the attribute
    pub(crate) data: Option<Value<'v>>,
    #[allocative(skip)] // "Not general enough"
    #[starlark_pagable(skip = "{ |_a, _b, _c| { unimplemented!() } }")]
    pub(crate) callable:
        for<'v2> fn(Option<Value<'v2>>, Value<'v2>, Heap<'v2>) -> crate::Result<Value<'v2>>,
}

impl<'fv> AllocFrozenValue<'fv> for NativeAttribute<'fv> {
    fn alloc_frozen_value(self, heap: FrozenHeap<'fv>) -> Value<'fv> {
        heap.alloc_simple_typed(self).to_value()
    }
}

impl<'v> NativeAttribute<'v> {
    #[inline]
    pub(crate) fn invoke(&self, this: Value<'v>, heap: Heap<'v>) -> crate::Result<Value<'v>> {
        (self.callable)(self.data, this, heap)
    }
}

#[starlark_value(type = "attribute", frozen_vtable)]
impl<'v> StarlarkValue<'v> for NativeAttribute<'v> {
    fn documentation(&self) -> DocItem {
        let ds = self
            .docstring
            .as_ref()
            .and_then(|ds| DocString::from_docstring(DocStringKind::Rust, ds));
        let typ = self.typ.clone();
        DocItem::Member(DocMember::Property(DocProperty { docs: ds, typ }))
    }
}

/// A wrapper for a method with a self object already bound.
#[derive(
    Clone,
    Debug,
    Trace,
    Display,
    FreezeBranded,
    NoSerialize,
    ProvidesStaticType,
    Allocative,
    crate::StarlarkPagable
)]
#[repr(C)]
#[display("{}", method)]
pub(crate) struct BoundMethod<'v> {
    pub(crate) method: ValueTyped<'v, NativeMethod<'v>>,
    pub(crate) this: Value<'v>,
}

starlark_complex_value_branded!(pub(crate) BoundMethod);

impl<'v> BoundMethod<'v> {
    /// Create a new [`BoundMethod`]. Given the expression `object.function`,
    /// the first argument would be `object`, and the second would be `getattr(object, "function")`.
    pub(crate) fn new(this: Value<'v>, method: ValueTyped<'v, NativeMethod<'v>>) -> Self {
        BoundMethod { method, this }
    }
}

#[starlark_value(type = FUNCTION_TYPE)]
impl<'v> StarlarkValue<'v> for BoundMethod<'v> {
    fn invoke(
        &self,
        _me: Value<'v>,
        args: &Arguments<'v, '_>,
        eval: &mut Evaluator<'v, '_, '_>,
    ) -> crate::Result<Value<'v>> {
        self.method.function.invoke(eval, self.this, args)
    }

    fn documentation(&self) -> DocItem {
        self.method.documentation()
    }
}
