load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("ios_devx")

source_listing()

python_binary(
    name = "codesign_manifest_tree_postprocessor",
    main = "main.py",
    visibility = ["PUBLIC"],
)
