load("@prelude//toolchains/android/tools:build_rules.bzl", "buck_java_library")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

buck_java_library(
    name = "filesystems",
    srcs = glob(["*.java"]),
    tests = ["prelude//toolchains/android/test/com/facebook/buck/core/filesystems:filesystems"],
    visibility = [
        "prelude//toolchains/android/src/com/facebook/buck/...",
        "prelude//toolchains/android/test/...",
    ],
    deps = [
        # Do NOT add deps here. This library is loaded into the JVM bootstrap classloader in Java 9+.
    ],
)
