load("@fbcode_macros//build_defs:native_rules.bzl", "buck_genrule")
load("@fbcode_macros//build_defs:python_binary.bzl", "python_binary")
load("@fbsource//tools/build_defs:glob_defs.bzl", "glob")
load("@fbsource//xplat/third-party/yarn:yarn_offline_mirror_helper.bzl", "yarn_offline_mirror_path")

oncall("scm_client_infra")

python_binary(
    name = "build_html_script",
    main_function = ".build_html.main",
    main_src = "build_html.py",
)

buck_genrule(
    name = "explain_html",
    # While it may be tedious to maintain the list of srcs by hand, it ensures
    # that changes in folders that are not part of 'explain' do not trigger
    # a rebuild.
    srcs = glob(
        [
            "**",
        ],
        exclude = [
            "node_modules/**",
            "dist/**",
        ],
    ),
    out = "explain.html",
    cmd = '$(exe :build_html_script) --yarn "$(exe fbsource//xplat/third-party/yarn:yarn)" --yarn-offline-mirror "{yarn_offline_mirror}" -o "$OUT" --src "$SRCDIR" --tmp "$TMP"'.format(yarn_offline_mirror = yarn_offline_mirror_path()),
)
