load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("build_infra")

source_listing()

config_setting(
    name = "x86_64",
    constraint_values = [
        "prelude//cpu/constraints:cpu[x86_64]",
    ],
    visibility = ["PUBLIC"],
)

config_setting(
    name = "x86_32",
    constraint_values = [
        "prelude//cpu/constraints:cpu[x86_32]",
    ],
    visibility = ["PUBLIC"],
)

config_setting(
    name = "arm64",
    constraint_values = [
        "prelude//cpu/constraints:cpu[arm64]",
    ],
    visibility = ["PUBLIC"],
)

config_setting(
    name = "arm32",
    constraint_values = [
        "prelude//cpu/constraints:cpu[arm32]",
    ],
    visibility = ["PUBLIC"],
)

config_setting(
    name = "wasm32",
    constraint_values = [
        "prelude//cpu/constraints:cpu[wasm32]",
    ],
    visibility = ["PUBLIC"],
)

config_setting(
    name = "riscv64",
    constraint_values = [
        "prelude//cpu/constraints:cpu[riscv64]",
    ],
    visibility = ["PUBLIC"],
)
